/**
 * Serializable schema manifest for TenantThemeConfig v1.
 *
 * Validation is derived from this object. Platform editors and persistence
 * adapters can compare its canonical digest instead of maintaining a second
 * field inventory by hand.
 */

import { MOTION_DIAL_BOUNDS } from "@/foundation/contracts/runtime/motion";
import {
  TENANT_THEME_ANATOMY_VARIANTS,
  TENANT_THEME_EFFECT_INTENSITY_BOUNDS,
  TENANT_THEME_NEUTRAL_OVERRIDE_TOKENS,
  TENANT_THEME_OVERRIDE_TOKENS,
  TENANT_THEME_RADIUS_SCALE_BOUNDS,
  TENANT_THEME_REFERENCE_TOKENS,
  TENANT_THEME_FONT_PACK_IDS,
  TENANT_THEME_SCHEMA_VERSION,
  TENANT_THEME_TYPE_SCALE_BOUNDS,
} from "@/foundation/contracts/composition/tenants/themes/tenant-theme";
import { RECIPE_PROFILES } from "@/foundation/tokens/ts/presentation/recipe-profiles";

export type TenantThemeSchemaNode =
  | {
      type: "object";
      fields: Readonly<Record<string, TenantThemeSchemaNode>>;
      required?: readonly string[];
    }
  | { type: "literal"; value: string | number }
  | { type: "enum"; values: readonly (string | number)[] }
  | {
      type: "string";
      format:
        | "identifier"
        | "slug"
        | "color"
        | "hex-color"
        | "font-family"
        | "visual-value";
    }
  | { type: "number"; integer?: boolean; min?: number; max?: number };

const literal = (value: string | number): TenantThemeSchemaNode => ({
  type: "literal",
  value,
});
const enumeration = (
  ...values: Array<string | number>
): TenantThemeSchemaNode => ({ type: "enum", values });
const string = (
  format: Extract<TenantThemeSchemaNode, { type: "string" }>["format"]
): TenantThemeSchemaNode => ({
  type: "string",
  format,
});
const number = (
  options: Omit<Extract<TenantThemeSchemaNode, { type: "number" }>, "type"> = {}
): TenantThemeSchemaNode => ({
  type: "number",
  ...options,
});
const object = (
  fields: Readonly<Record<string, TenantThemeSchemaNode>>,
  required: readonly string[] = []
): TenantThemeSchemaNode => ({
  type: "object",
  fields,
  ...(required.length > 0 ? { required } : {}),
});

const visualFields = (
  fields: readonly string[]
): Readonly<Record<string, TenantThemeSchemaNode>> =>
  Object.fromEntries(fields.map((field) => [field, string("visual-value")]));

/**
 * Governed recipe-profile selection (DS-S001): the schema is a closed enum
 * over the first-party registry, so a customer document can only SELECT a
 * published profile id — never author one.
 */
const recipeProfile = enumeration(
  ...RECIPE_PROFILES.map((profile) => profile.id)
);

const COLOR = string("color");
const HEX_COLOR = string("hex-color");
const VISUAL = string("visual-value");
const FONT_WEIGHT = number({ min: 1, max: 1000 });
const OPACITY = number({ min: 0, max: 1 });

const general = object({
  palette: object({
    primary: COLOR,
    secondary: COLOR,
    accent: COLOR,
    background: HEX_COLOR,
    foreground: object({
      primary: HEX_COLOR,
      secondary: HEX_COLOR,
      muted: HEX_COLOR,
      disabled: HEX_COLOR,
    }),
    border: object({
      primary: HEX_COLOR,
      secondary: HEX_COLOR,
    }),
    backgroundMode: enumeration("light", "dark", "auto"),
    dark: object({
      primary: COLOR,
      secondary: COLOR,
      accent: COLOR,
      background: HEX_COLOR,
      foreground: object({
        primary: HEX_COLOR,
        secondary: HEX_COLOR,
        muted: HEX_COLOR,
        disabled: HEX_COLOR,
      }),
      border: object({
        primary: HEX_COLOR,
        secondary: HEX_COLOR,
      }),
    }),
  }),
  typography: object({
    fontFamilyBase: string("font-family"),
    fontFamilyHeading: string("font-family"),
    typePairing: enumeration("sober", "editorial", "geometric", "technical"),
    scale: number({
      min: TENANT_THEME_TYPE_SCALE_BOUNDS.min,
      max: TENANT_THEME_TYPE_SCALE_BOUNDS.max,
    }),
  }),
  shape: object({
    buttonStyle: enumeration("sharp", "soft", "pill"),
    radiusScale: number({
      min: TENANT_THEME_RADIUS_SCALE_BOUNDS.min,
      max: TENANT_THEME_RADIUS_SCALE_BOUNDS.max,
    }),
  }),
  density: enumeration("compact", "normal", "spacious"),
  motion: object({
    intensity: number({
      min: MOTION_DIAL_BOUNDS.intensity.min,
      max: MOTION_DIAL_BOUNDS.intensity.max,
    }),
    durationScale: number({
      min: MOTION_DIAL_BOUNDS.durationScale.min,
      max: MOTION_DIAL_BOUNDS.durationScale.max,
    }),
    ambient: enumeration("off", "subtle"),
  }),
  surfaces: object({
    elevation: enumeration("flat", "soft", "elevated"),
    effectIntensity: number({
      min: TENANT_THEME_EFFECT_INTENSITY_BOUNDS.min,
      max: TENANT_THEME_EFFECT_INTENSITY_BOUNDS.max,
    }),
  }),
  navigation: object({
    sidebarTone: enumeration("subtle", "strong", "inverse"),
  }),
});

const anatomy = (
  family: keyof typeof TENANT_THEME_ANATOMY_VARIANTS
): TenantThemeSchemaNode =>
  enumeration(...TENANT_THEME_ANATOMY_VARIANTS[family]);

const sidebar = object({
  anatomy: anatomy("sidebar"),
  ...visualFields([
    "bg",
    "border",
    "text",
    "textMuted",
    "width",
    "collapsedWidth",
    "headerHeight",
    "groupFontSize",
    "groupColor",
    "groupLetterSpacing",
    "itemFontSize",
    "itemColor",
    "itemColorActive",
    "itemBgActive",
    "itemBgHover",
    "itemPadding",
    "iconSize",
    "footerBg",
  ]),
  groupFontWeight: FONT_WEIGHT,
  itemFontWeight: FONT_WEIGHT,
  itemFontWeightActive: FONT_WEIGHT,
});

const shell = object(
  visualFields([
    "gridSize",
    "gridLine",
    "bg",
    "border",
    "overlay",
    "shadow",
    "activeBg",
    "activeGradient",
    "dropdownShadow",
    "shimmerFaint",
    "shimmerSoft",
    "shimmerMedium",
    "shimmerStrong",
    "commandFont",
    "commandLetterSpacing",
    "commandGridSize",
    "commandGridLineSoft",
    "commandGridLine",
    "commandGridLineStrong",
    "commandGridBg",
    "commandGridBgStrong",
    "commandGlow",
    "commandLine",
    "commandRailBg",
    "commandHomeMaxWidth",
    "commandHomeGap",
    "commandHomePanelGap",
    "commandHomeGridLine",
    "commandHomePanelBorder",
    "commandHomePanelBorderSoft",
    "commandHomePanelShadow",
    "commandHomePanelBg",
    "commandHomePanelBgStrong",
    "commandHomeCompactActionHeight",
    "commandHomeConsoleMinHeight",
    "commandHomeConsolePadding",
    "commandHomeConsoleBg",
    "commandHomeSurfaceBg",
    "commandHomeHeroBg",
    "commandHomeIconBg",
    "commandHomeIconBorder",
    "commandHomeControlBg",
    "commandHomeControlBorder",
    "commandHomeControlHoverBg",
    "commandHomeControlHoverBorder",
    "commandHomeMeterBg",
    "commandHomeMeterFill",
  ])
);

const buttonVariant = object(
  visualFields([
    "bg",
    "bgHover",
    "bgActive",
    "color",
    "colorHover",
    "colorActive",
    "text",
    "border",
    "borderHover",
    "borderActive",
    "shadow",
    "shadowHover",
    "shadowActive",
  ])
);

const controlSize = object(
  visualFields([
    "height",
    "paddingX",
    "paddingY",
    "fontSize",
    "lineHeight",
    "iconSize",
    "gap",
    "radius",
  ])
);

const buttonGeometry = object({
  ...visualFields([
    "fontFamily",
    "letterSpacing",
    "textTransform",
    "gap",
    "radius",
    "borderWidth",
    "touchTargetMin",
    "groupGap",
    "groupMobileGap",
    "groupMobileWidth",
    "hoverTransform",
    "activeTransform",
    "iconHoverTransform",
    "iconActiveTransform",
    "labelOffsetY",
    "hoverFilter",
    "activeFilter",
    "focusRingOffset",
    "spinnerDuration",
    "surfaceHighlight",
    "surfaceHighlightOpacity",
    "surfaceHighlightHoverOpacity",
    "surfaceHighlightActiveOpacity",
    "gradient",
    "aiTexture",
    "transitionDuration",
    "transitionTiming",
  ]),
  groupMobileDirection: enumeration("row", "column"),
  fontWeight: FONT_WEIGHT,
  xs: controlSize,
  sm: controlSize,
  md: controlSize,
  lg: controlSize,
  xl: controlSize,
});

const fieldGeometry = object({
  ...visualFields([
    "gap",
    "radius",
    "fontFamily",
    "letterSpacing",
    "borderWidth",
    "borderStyle",
    "messageGap",
    "groupGap",
    "groupGapSeparated",
    "groupOverlap",
    "groupMinItemWidth",
    "formFieldGap",
    "horizontalGap",
    "labelOffsetY",
    "requiredGap",
    "labelFontSize",
    "labelFontFamily",
    "labelLetterSpacing",
    "labelLineHeight",
    "helperFontSize",
    "helperLineHeight",
    "affixSize",
    "affixSizeCompact",
    "affixRadius",
    "actionSize",
    "actionRadius",
    "touchTargetMin",
    "loadingSize",
    "loadingStroke",
    "loadingDuration",
    "textareaMinHeight",
    "textareaMaxHeight",
    "textareaPaddingX",
    "textareaPaddingY",
    "textareaRadius",
    "textareaResize",
    "transitionDuration",
    "transitionTiming",
  ]),
  fontWeight: FONT_WEIGHT,
  labelFontWeight: FONT_WEIGHT,
  formFieldDisabledOpacity: OPACITY,
  xs: controlSize,
  sm: controlSize,
  md: controlSize,
  lg: controlSize,
  xl: controlSize,
});

const segmented = object({
  ...visualFields([
    "bg",
    "border",
    "radius",
    "padding",
    "gap",
    "shadow",
    "itemBg",
    "itemBgHover",
    "itemBgSelected",
    "itemColor",
    "itemColorHover",
    "itemColorSelected",
    "itemRadius",
    "itemShadowSelected",
    "focusRing",
  ]),
  itemFontWeight: FONT_WEIGHT,
  itemFontWeightSelected: FONT_WEIGHT,
  sm: controlSize,
  md: controlSize,
  lg: controlSize,
});

const input = object({
  ...visualFields([
    "bg",
    "bgHover",
    "bgFocus",
    "bgDisabled",
    "color",
    "colorPlaceholder",
    "colorDisabled",
    "border",
    "borderHover",
    "borderFocus",
    "borderDisabled",
    "shadowRest",
    "shadowHover",
    "shadowFocus",
    "insetShadow",
    "caretColor",
    "selectionBg",
    "selectionColor",
    "successBorder",
    "successBg",
    "successShadowFocus",
    "warningBorder",
    "warningBg",
    "warningShadowFocus",
    "errorBorder",
    "errorBg",
    "errorShadowFocus",
    "errorColor",
    "loadingColor",
  ]),
  disabledOpacity: OPACITY,
  placeholderOpacity: OPACITY,
  filled: object(visualFields(["bg", "bgHover", "bgFocus", "border"])),
  addon: object({
    ...visualFields(["bg", "color", "border", "radius"]),
    fontWeight: FONT_WEIGHT,
  }),
  affix: object(visualFields(["bg", "color", "border", "paddingX"])),
  label: object(visualFields(["color", "requiredColor", "disabledColor"])),
  helper: object({
    ...visualFields(["color", "errorColor"]),
    errorFontWeight: FONT_WEIGHT,
  }),
  clear: object(
    visualFields([
      "color",
      "colorHover",
      "bg",
      "bgHover",
      "border",
      "borderHover",
      "shadowHover",
      "focusRing",
      "activeTransform",
    ])
  ),
  readOnly: object(
    visualFields(["bg", "color", "border", "borderStyle", "cursor"])
  ),
  autofill: object(visualFields(["bg", "color", "caret"])),
  count: object(visualFields(["color", "colorWarning", "colorError"])),
});

const controls = object({
  buttonGeometry,
  fieldGeometry,
  segmented,
  buttonPrimary: buttonVariant,
  buttonSecondary: buttonVariant,
  buttonDefault: buttonVariant,
  buttonGhost: buttonVariant,
  buttonText: buttonVariant,
  buttonDashed: buttonVariant,
  buttonLink: buttonVariant,
  buttonSuccess: buttonVariant,
  buttonWarning: buttonVariant,
  buttonError: buttonVariant,
  buttonInfo: buttonVariant,
  buttonAI: buttonVariant,
  disabled: object({
    ...visualFields(["bg", "text", "border", "borderColor"]),
    opacity: OPACITY,
  }),
  focusRing: VISUAL,
  input,
});

const premiumCardFields: Readonly<Record<string, TenantThemeSchemaNode>> =
  visualFields([
    "bg",
    "bgHover",
    "border",
    "borderHover",
    "selectedBorder",
    "selectedRing",
    "shadow",
    "shadowHover",
    "radius",
    "padding",
    "gap",
    "minHeight",
    "glassBg",
    "gridSize",
    "gridLine",
    "gridBg",
    "overlay",
    "sheen",
    "depth",
    "hoverTransform",
    "transition",
    "iconBg",
    "iconBorder",
    "iconColor",
    "titleColor",
    "bodyColor",
    "labelColor",
    "valueColor",
    "valueHoverColor",
    "footerBg",
    "footerBorder",
    "footerColor",
    "statusBg",
    "statusBorder",
    "statusColor",
    "actionBg",
    "actionBorder",
    "actionColor",
    "meterTrack",
    "meterTrackBorder",
    "meterFill",
    "numberMinWidth",
    "numberFontVariant",
  ]);

const chrome = object({
  sidebar,
  layout: object({
    anatomy: anatomy("layout"),
    ...visualFields([
      "bg",
      "headerBg",
      "headerHeight",
      "headerBackdrop",
      "headerBorder",
      "siderBg",
      "siderBorder",
      "containerBackground",
      "containerBorder",
      "containerRadius",
      "containerShadow",
      "containerMotionDuration",
      "containerMotionEasing",
      "aspectRatioBackground",
      "aspectRatioBorder",
      "aspectRatioRadius",
      "aspectRatioShadow",
      "aspectRatioOverflow",
      "aspectRatioMotionDuration",
      "aspectRatioMotionEasing",
      "dividerColor",
      "dividerThicknessThin",
      "dividerThicknessMedium",
      "dividerThicknessThick",
      "dividerContentGap",
      "dividerEdgeSegment",
      "dividerMinSegment",
      "dividerLabelMaxWidth",
      "dividerLabelFontSize",
      "dividerLabelFontWeight",
      "dividerLabelLineHeight",
      "dividerLabelTransform",
      "dividerLabelTracking",
      "dividerMotionDuration",
      "dividerMotionEasing",
      "stackDividerSize",
      "stackDividerColor",
      "stackDividerOpacity",
      "spaceMotionDuration",
      "spaceMotionEasing",
    ]),
  }),
  shell,
  toolbar: object(
    visualFields([
      "bg",
      "border",
      "borderBottom",
      "color",
      "shadow",
      "solidBg",
      "solidColor",
      "solidBorder",
      "softBg",
      "softColor",
      "softBorder",
      "ghostBg",
      "ghostColor",
      "ghostBorder",
      "ghostShadow",
      "outlineBg",
      "outlineColor",
      "outlineBorder",
      "outlineShadow",
      "radius",
      "padding",
      "gap",
      "controlBg",
      "controlBorder",
      "controlColor",
      "divider",
    ])
  ),
  filterPill: object(
    visualFields([
      "bg",
      "border",
      "color",
      "shadow",
      "frameBg",
      "frameBorder",
      "frameShadow",
      "hoverBg",
      "hoverBorder",
      "activeBg",
      "activeBorder",
      "activeColor",
      "activeShadow",
      "focusRing",
      "countBg",
      "countActiveBg",
      "countBorder",
      "countActiveBorder",
      "countRing",
      "countActiveRing",
    ])
  ),
  badge: object({
    ...visualFields([
      "lineHeight",
      "letterSpacing",
      "gap",
      "maxInlineSize",
      "chipMaxInlineSize",
      "pillMaxInlineSize",
      "frameWidth",
      "radius",
      "chipRadius",
      "pillRadius",
      "surface",
      "ink",
      "frame",
      "highlight",
      "shadow",
      "solidBg",
      "solidColor",
      "solidBorder",
      "softBg",
      "softColor",
      "softBorder",
      "ghostBg",
      "ghostColor",
      "ghostBorder",
      "ghostShadow",
      "outlineBg",
      "outlineColor",
      "outlineBorder",
      "outlineShadow",
      "surfaceHover",
      "inkHover",
      "frameHover",
      "highlightHover",
      "shadowHover",
      "hoverTransform",
      "surfacePressed",
      "inkPressed",
      "framePressed",
      "shadowPressed",
      "pressTransform",
      "focusRing",
      "selectedSurface",
      "selectedInk",
      "selectedFrame",
      "selectedShadow",
      "borderedRing",
      "iconSize",
      "iconColor",
      "iconBg",
      "iconBorder",
      "iconBorderWidth",
      "iconRadius",
      "iconShadow",
      "avatarSize",
      "avatarBleed",
      "avatarBg",
      "avatarBorder",
      "avatarBorderWidth",
      "avatarRadius",
      "avatarShadow",
      "dotSize",
      "dotBg",
      "dotBorder",
      "dotBorderWidth",
      "dotShadow",
      "countMinSize",
      "countSize",
      "countPaddingInline",
      "countBg",
      "countColor",
      "countBorder",
      "countBorderWidth",
      "countRadius",
      "countRing",
      "countFontSize",
      "countSelectedBg",
      "countSelectedBorder",
      "countSelectedRing",
      "removeSize",
      "removeTouchSize",
      "removeBleed",
      "removeBg",
      "removeColor",
      "removeBorder",
      "removeBorderWidth",
      "removeRadius",
      "removeHoverBg",
      "removeHoverTransform",
      "removeFocusRing",
      "disabledFilter",
      "motionDuration",
      "motionEasing",
      "pulseDuration",
      "pulseTiming",
      "spinnerDuration",
      "touchTarget",
      "containerPaddingInline",
      "indicatorMaxInlineSize",
      "indicatorRadius",
    ]),
    fontFamily: string("font-family"),
    countFontFamily: string("font-family"),
    fontWeight: FONT_WEIGHT,
    countFontWeight: FONT_WEIGHT,
    removeOpacity: OPACITY,
    disabledOpacity: OPACITY,
    loadingOpacity: OPACITY,
    pulseScale: number({ min: 1, max: 2 }),
  }),
  breadcrumb: object({
    ...visualFields([
      "bg",
      "border",
      "color",
      "linkColor",
      "itemColor",
      "colorHover",
      "colorActive",
      "separatorColor",
      "fontSize",
      "padding",
    ]),
    fontWeight: FONT_WEIGHT,
  }),
  search: object(
    visualFields([
      "bg",
      "border",
      "color",
      "shadow",
      "radius",
      "inputBg",
      "inputBorder",
      "inputColor",
      "placeholderColor",
      "iconColor",
      "clearColor",
      "clearColorHover",
      "resultBg",
      "resultBgHover",
      "resultBorder",
      "resultShadow",
      "resultTitleColor",
      "resultMetaColor",
      "categoryColor",
      "emptyBg",
    ])
  ),
  controls,
  table: object({
    anatomy: anatomy("table"),
    ...visualFields([
      "bg",
      "border",
      "radius",
      "headerBg",
      "headerBgHover",
      "headerColor",
      "headerFontSize",
      "headerLetterSpacing",
      "headerTextTransform",
      "headerBlockSize",
      "headerBorder",
      "headerShadow",
      "rowBg",
      "rowBgHover",
      "rowBgStriped",
      "rowBgSelected",
      "rowBgExpanded",
      "rowBorder",
      "rowHoverShadow",
      "cellPadding",
      "cellPaddingCompact",
      "cellPaddingComfortable",
      "cellPaddingSpacious",
      "cellFontSize",
      "cellColor",
      "filterRowBg",
      "filterFocusShadow",
      "resizeBg",
      "resizeBgHover",
      "reorderBg",
      "actionBg",
      "actionBorder",
      "sheen",
      "pageButtonHoverShadow",
      "loadingOverlayBg",
    ]),
    headerFontWeight: FONT_WEIGHT,
  }),
  cardComponent: object({
    anatomy: anatomy("cardComponent"),
    ...visualFields([
      "padding",
      "paddingSm",
      "paddingMd",
      "paddingLg",
      "paddingXl",
      "bg",
      "bgHover",
      "bgActive",
      "bgSelected",
      "bgDisabled",
      "color",
      "colorHover",
      "colorActive",
      "colorSelected",
      "colorDisabled",
      "colorMuted",
      "border",
      "borderColor",
      "borderWidth",
      "borderStyle",
      "borderHover",
      "borderColorHover",
      "borderActive",
      "borderSelected",
      "borderDisabled",
      "borderAccentHover",
      "radius",
      "radiusSm",
      "radiusLg",
      "radiusXl",
      "shadow",
      "shadowHover",
      "shadowActive",
      "shadowSelected",
      "shadowElevated",
      "focusRing",
      "focusRingColor",
      "focusRingWidth",
      "focusRingOffset",
      "selectedOutlineWidth",
      "hoverTransform",
      "activeTransform",
      "transitionDuration",
      "transitionTiming",
      "texture",
      "textureSize",
      "overlay",
      "surfaceGradient",
      "stateOverlay",
      "elevatedBg",
      "elevatedBorderWidth",
      "elevatedShadow",
      "elevatedShadowHover",
      "outlinedBg",
      "outlinedBorderWidth",
      "outlinedBorderColor",
      "outlinedShadow",
      "filledBg",
      "filledBorderWidth",
      "filledShadow",
      "ghostBg",
      "ghostBorderColor",
      "ghostShadow",
      "headerBorder",
      "headerBorderColor",
      "headerBorderWidth",
      "headerBg",
      "headerColor",
      "headerPadding",
      "headerPaddingSm",
      "headerPaddingLg",
      "headerGap",
      "headerActionsGap",
      "headerMinHeight",
      "headerCopyMaxWidth",
      "headerEyebrowSize",
      "headerEyebrowTracking",
      "headerIconSize",
      "headerIconRadius",
      "headerIconBg",
      "headerIconBorder",
      "headerIconColor",
      "headerExtraBg",
      "headerExtraBorder",
      "headerExtraRadius",
      "headerExtraPadding",
      "titleColor",
      "titleFontSize",
      "titleLineHeight",
      "titleLetterSpacing",
      "subtitleColor",
      "subtitleFontSize",
      "subtitleMarginTop",
      "bodyColor",
      "bodyPadding",
      "bodyPaddingSm",
      "bodyPaddingLg",
      "bodyFontSize",
      "bodyLineHeight",
      "footerBorder",
      "footerBorderColor",
      "footerBorderWidth",
      "footerBg",
      "footerColor",
      "footerPadding",
      "footerPaddingSm",
      "footerPaddingLg",
      "footerActionsGap",
      "actionsGap",
      "actionsMarginTop",
      "actionsPaddingTop",
      "coverInlineSize",
      "coverInlineMinSize",
      "coverBlockMinSize",
      "coverAspectRatio",
      "coverObjectPosition",
      "coverObjectFit",
      "bodyInlineMinSize",
      "imagePlaceholderBg",
      "imagePlaceholderColor",
      "imageHeight",
      "imageLoadingTrack",
      "imageLoadingActive",
      "imageLoadingSize",
      "imageLoadingStroke",
      "imageLoadingDuration",
      "imageErrorIconSize",
      "spinnerSize",
      "spinnerStroke",
      "spinnerTrack",
      "spinnerColor",
      "spinnerDuration",
      "loadingOverlayBg",
      "loadingBackdropBlur",
      "skeletonBg",
      "skeletonHighlight",
      "skeletonRadius",
      "skeletonDuration",
    ]),
    titleFontWeight: FONT_WEIGHT,
    disabledOpacity: OPACITY,
    textureOpacity: OPACITY,
    stateOverlayHoverOpacity: OPACITY,
    stateOverlayActiveOpacity: OPACITY,
    stateOverlaySelectedOpacity: OPACITY,
    loadingCoverOpacity: OPACITY,
    loadingSkeletonOpacity: OPACITY,
  }),
  metricCard: object({
    ...premiumCardFields,
    ...visualFields([
      "trendColor",
      "trendColorWarning",
      "trendColorError",
      "trendErrorBg",
      "trendErrorBorder",
      "meterFillSuccess",
      "meterFillWarning",
      "meterFillError",
      "meterFillNeutral",
      "meterHeight",
    ]),
  }),
  signalCard: object({
    ...premiumCardFields,
    ...visualFields([
      "accent",
      "soft",
      "badgeBg",
      "badgeBorder",
      "badgeColor",
      "sectionBg",
      "sectionAltBg",
      "topLineDisplay",
    ]),
  }),
  workspaceCard: object(premiumCardFields),
  compactCard: object(premiumCardFields),
  tallCard: object(premiumCardFields),
  collectionCard: object(premiumCardFields),
  listingGrid: object(
    visualFields([
      "gap",
      "minCardWidth",
      "minCompactWidth",
      "minTallWidth",
      "columns",
      "cardGap",
      "cardBg",
      "cardBorder",
      "cardShadow",
      "selectedRing",
      "emptyBg",
      "emptyBorder",
      "skeletonBg",
    ])
  ),
  modal: object(
    visualFields([
      "bg",
      "color",
      "shadow",
      "overlayBg",
      "overlayBackdrop",
      "headerBg",
      "headerBorder",
      "titleColor",
      "subtitleColor",
      "bodyColor",
      "footerBorder",
      "footerBg",
      "closeColor",
      "closeColorHover",
      "closeBgHover",
    ])
  ),
  tooltip: object(
    visualFields([
      "borderedBackground",
      "borderedForeground",
      "borderedBorder",
      "borderedBorderWidth",
      "borderedShadow",
      "borderedTexture",
      "borderedHighlight",
      "borderedRadius",
      "borderedMaxWidth",
      "borderedPaddingBlock",
      "borderedPaddingInline",
      "minimalBackground",
      "minimalForeground",
      "minimalBorder",
      "minimalBorderWidth",
      "minimalShadow",
      "minimalTexture",
      "minimalHighlight",
      "minimalRadius",
      "minimalMaxWidth",
      "minimalPaddingBlock",
      "minimalPaddingInline",
      "inverseBackground",
      "inverseForeground",
      "inverseBorder",
      "inverseBorderWidth",
      "inverseShadow",
      "inverseTexture",
      "inverseHighlight",
      "inverseRadius",
      "inverseMaxWidth",
      "inversePaddingBlock",
      "inversePaddingInline",
      "richBackground",
      "richForeground",
      "richBorder",
      "richBorderWidth",
      "richShadow",
      "richTexture",
      "richHighlight",
      "richRadius",
      "richMaxWidth",
      "richPaddingBlock",
      "richPaddingInline",
      "richType",
      "richLetterSpacing",
      "compactPaddingBlock",
      "compactPaddingInline",
      "compactType",
      "comfortablePaddingBlock",
      "comfortablePaddingInline",
      "spaciousPaddingBlock",
      "spaciousPaddingInline",
      "spaciousType",
      "arrowSize",
      "arrowHalfSize",
      "arrowOverlap",
      "viewportGap",
      "touchTarget",
      "shortcutGap",
      "shortcutChipGap",
      "shortcutKeyBackground",
      "shortcutKeyBorder",
      "shortcutKeyBorderWidth",
      "shortcutKeyRadius",
      "shortcutKeyShadow",
      "shortcutKeyType",
      "motionDistance",
      "motionScale",
      "enterDuration",
      "enterEasing",
      "exitDuration",
      "exitEasing",
    ])
  ),
  popover: object(
    visualFields([
      "borderedBackground",
      "borderedForeground",
      "borderedMutedForeground",
      "borderedBorder",
      "borderedBorderWidth",
      "borderedShadow",
      "borderedTexture",
      "borderedHighlight",
      "borderedRadius",
      "borderedMaxWidth",
      "borderedPaddingBlock",
      "borderedPaddingInline",
      "borderedTitleGap",
      "minimalBackground",
      "minimalForeground",
      "minimalMutedForeground",
      "minimalBorder",
      "minimalBorderWidth",
      "minimalShadow",
      "minimalTexture",
      "minimalHighlight",
      "minimalRadius",
      "minimalMaxWidth",
      "minimalPaddingBlock",
      "minimalPaddingInline",
      "inverseBackground",
      "inverseForeground",
      "inverseMutedForeground",
      "inverseBorder",
      "inverseShadow",
      "inverseTexture",
      "inverseHighlight",
      "inverseRadius",
      "richBackground",
      "richForeground",
      "richMutedForeground",
      "richBorder",
      "richShadow",
      "richTexture",
      "richHighlight",
      "richRadius",
      "richMaxWidth",
      "richPaddingBlock",
      "richPaddingInline",
      "compactPaddingBlock",
      "compactPaddingInline",
      "compactTitleGap",
      "compactMaxHeight",
      "comfortablePaddingBlock",
      "comfortablePaddingInline",
      "spaciousPaddingBlock",
      "spaciousPaddingInline",
      "spaciousTitleGap",
      "minWidth",
      "maxWidth",
      "maxHeight",
      "bodyMaxHeight",
      "viewportGap",
      "touchTarget",
      "arrowSize",
      "titleBackground",
      "titleColor",
      "titleDivider",
      "titleDividerWidth",
      "titlePaddingBlock",
      "titlePaddingInline",
      "titleGap",
      "titleType",
      "titleLetterSpacing",
      "bodyType",
      "motionDistance",
      "motionScale",
      "enterDuration",
      "enterEasing",
      "exitDuration",
      "exitEasing",
    ])
  ),
  tabs: object({
    ...visualFields([
      "border",
      "color",
      "colorHover",
      "colorActive",
      "bgHover",
      "borderActive",
      "listBg",
      "underlineListBg",
      "containedListBg",
      "segmentedListBg",
      "pillsListBg",
      "underlineHoverBg",
      "underlineActiveBg",
      "underlineItemRadius",
      "listBorder",
      "listRadius",
      "listPadding",
      "listWidth",
      "listMaxWidth",
      "underlineListWidth",
      "listShadow",
      "listBlur",
      "listTexture",
      "listTextureSize",
      "listHighlight",
      "gap",
      "itemGap",
      "itemRadius",
      "itemMaxWidth",
      "itemLineHeight",
      "itemLetterSpacing",
      "activeBg",
      "activeShadow",
      "activeTransform",
      "activeHighlight",
      "pressedTransform",
      "containedActiveBg",
      "containedActiveShadow",
      "segmentedActiveBg",
      "segmentedActiveShadow",
      "pillsActiveBg",
      "pillsActiveColor",
      "pillsActiveBorder",
      "pillsActiveShadow",
      "disabledColor",
      "disabledBg",
      "iconColor",
      "iconBg",
      "iconBgActive",
      "iconPadding",
      "iconRadius",
      "iconShadow",
      "iconShadowActive",
      "iconTransformActive",
      "badgeBg",
      "badgeColor",
      "badgeBorder",
      "badgeRadius",
      "badgeHeight",
      "badgeMinWidth",
      "badgePadding",
      "badgeFontSize",
      "badgeBgActive",
      "badgeColorActive",
      "badgeBorderActive",
      "indicatorHeight",
      "indicatorGradient",
      "indicatorRadius",
      "indicatorShadow",
      "panelPadding",
      "panelGap",
      "panelBg",
      "panelBorder",
      "panelRadius",
      "panelShadow",
      "panelFocusRing",
      "panelTexture",
      "panelHighlight",
      "panelMotionDistance",
      "overflowControlSize",
      "overflowControlBg",
      "overflowControlColor",
      "overflowControlBorder",
      "overflowControlShadow",
      "overflowControlBgHover",
      "overflowControlShadowHover",
      "overflowFadeWidth",
      "overflowFadeColor",
      "mobilePadding",
      "mobileGap",
      "mobileItemMaxWidth",
      "motionDuration",
      "motionEasing",
      "activeRevealDuration",
      "panelMotionDuration",
      "panelMotionEasing",
      "smHeight",
      "smPadding",
      "smFontSize",
      "smIconSize",
      "mdHeight",
      "mdPadding",
      "mdFontSize",
      "mdIconSize",
      "lgHeight",
      "lgPadding",
      "lgFontSize",
      "lgIconSize",
    ]),
    itemFontFamily: string("font-family"),
    itemFontWeight: FONT_WEIGHT,
    itemFontWeightActive: FONT_WEIGHT,
    badgeFontWeight: FONT_WEIGHT,
    listTextureOpacity: OPACITY,
    activeHighlightOpacity: OPACITY,
    disabledOpacity: OPACITY,
  }),
});

const NEUTRAL_OVERRIDE_TOKENS = new Set<string>(
  TENANT_THEME_NEUTRAL_OVERRIDE_TOKENS
);

const tokenValueRules: Readonly<Record<string, TenantThemeSchemaNode>> =
  Object.fromEntries(
    TENANT_THEME_OVERRIDE_TOKENS.map((token) => {
      if (token.startsWith("--ds-chart-category-")) return [token, HEX_COLOR];
      if (NEUTRAL_OVERRIDE_TOKENS.has(token)) return [token, HEX_COLOR];
      if (token.startsWith("--ds-color-") || token.startsWith("--ds-overlay-"))
        return [token, COLOR];
      if (token.startsWith("--ds-font-family-"))
        return [token, string("font-family")];
      if (token.startsWith("--ds-line-height-"))
        return [token, number({ min: 0.5, max: 3 })];
      if (token === "--ds-density-scale")
        return [token, number({ min: 0.75, max: 1.25 })];
      if (token === "--ds-effect-intensity")
        return [token, number({ min: 0, max: 1 })];
      return [token, VISUAL];
    })
  );

const advanced = object({
  chrome,
  tokenOverrides: object(tokenValueRules),
});

const documentFields: Readonly<Record<string, TenantThemeSchemaNode>> = {
  schemaVersion: literal(TENANT_THEME_SCHEMA_VERSION),
};

const identityFields: Readonly<Record<string, TenantThemeSchemaNode>> = {
  tenantId: string("identifier"),
  slug: string("slug"),
  verticalKey: string("slug"),
  rowVersion: number({ integer: true, min: 0 }),
};

function deepFreeze<T>(value: T): Readonly<T> {
  if (value !== null && typeof value === "object") {
    for (const child of Object.values(value as Record<string, unknown>))
      deepFreeze(child);
    if (!Object.isFrozen(value)) Object.freeze(value);
  }
  return value;
}

export const TENANT_THEME_CONFIG_SCHEMA = deepFreeze({
  id: "rottay.tenant-theme-config",
  schemaVersion: TENANT_THEME_SCHEMA_VERSION,
  documents: Object.freeze({
    simple: object(
      { ...documentFields, mode: literal("simple"), appearance: general },
      ["schemaVersion", "mode", "appearance"]
    ),
    advanced: object(
      {
        ...documentFields,
        mode: literal("advanced"),
        visualFoundation: object({ general, advanced, recipeProfile }),
      },
      ["schemaVersion", "mode", "visualFoundation"]
    ),
  }),
  modes: Object.freeze({
    simple: object(
      {
        ...documentFields,
        ...identityFields,
        mode: literal("simple"),
        appearance: general,
      },
      [
        "schemaVersion",
        "tenantId",
        "slug",
        "verticalKey",
        "rowVersion",
        "mode",
        "appearance",
      ]
    ),
    advanced: object(
      {
        ...documentFields,
        ...identityFields,
        mode: literal("advanced"),
        visualFoundation: object({ general, advanced, recipeProfile }),
      },
      [
        "schemaVersion",
        "tenantId",
        "slug",
        "verticalKey",
        "rowVersion",
        "mode",
        "visualFoundation",
      ]
    ),
  }),
  scopeAttributes: Object.freeze([
    "data-ds-root",
    "data-vertical",
    "data-tenant",
  ]),
  forbiddenCapabilities: Object.freeze([
    "rawCss",
    "selectors",
    "engine",
    "componentPack",
    "topology",
    "permissions",
    "semanticMappings",
    "iconGlyphs",
    "iconContainers",
    "motionRecipes",
    "chartRenderer",
    "chartDataSemantics",
  ]),
  overrideTokens: TENANT_THEME_OVERRIDE_TOKENS,
  referenceTokens: TENANT_THEME_REFERENCE_TOKENS,
  fontPackIds: TENANT_THEME_FONT_PACK_IDS,
  limits: Object.freeze({
    maxDocumentBytes: 65_536,
    maxDepth: 10,
    maxObjectFields: 512,
    // Advanced can legally project broad chrome plus 70 compiler-owned color
    // ramp variables. The adversarial max-byte v2 fixture emits 69,894 bytes:
    // 64 KiB is 4,358 bytes too small; 88 KiB leaves 20,218 bytes of headroom
    // while remaining a hard SSR/hydration ceiling.
    maxCompiledVariables: 512,
    maxCompiledVariableBytes: 90_112,
    // Single authority for the raw tokenOverrides entry cap. The appearance
    // compiler and the skin-pack registrar import this value; a second literal
    // 200 anywhere is a cascade-integrity defect.
    maxTokenOverrides: 200,
    maxStringLength: 512,
    maxFontFamilyLength: 200,
    maxShadowLayers: 4,
    maxGradientStops: 8,
    maxPaddingPx: 128,
    maxRadiusPx: 64,
    maxGapPx: 64,
    maxGridSizePx: 256,
  }),
});

export const TENANT_THEME_GENERAL_SCHEMA = general;
export const TENANT_THEME_ADVANCED_SCHEMA = advanced;
