import { ComponentBehaviorScene, type ComponentBehaviorCase } from '../../sections/component-behaviors';
import { JudgeOverlay } from '../../judge';

const CASES: ComponentBehaviorCase[] = [
  'datepicker',
  'timepicker',
  'tabs',
  'stepper',
  'upload',
  'splitter',
  'textarea',
  'radio',
  'checkbox',
  'toggle',
  'inputnumber',
  'passwordinput',
  'mentions',
  'otpinput',
  'collapse',
  'backtop',
  'floatbutton',
  'switch',
  'scrollarea',
  'breadcrumb',
  'anchor',
  'formfield',
  'layout',
  'rate',
  'affix',
  'result',
  'link',
  'segmented',
  'popover',
  'drawer',
  'skeleton',
  'form',
  'watermark',
  'alert',
  'input',
  'grid',
  'dropdown',
  'pricingtable',
  'livefeed',
  'brandingpreview',
  'userprofilecard',
  'workbenchheader',
  'gridtrack',
  'gallerytrack',
  'savedviewsfocus',
  'bulkselectcount',
  'cellreveal',
  'celleditorerror',
  'detailpanellate',
  'filemanagerrows',
  'formbuilderresolve',
  'filterpanelnames',
  'adaptiveoverlay',
  'invoicetemplate',
  'stepwizard',
  'localeswitcher',
  'patterntimeline',
  'patternkanban',
  'presence',
  'brand-studio',
  'tenant-preview',
  'token-inspector',
  'column-settings',
  'workspace-switcher',
  'cockpit-header',
  'page-shell',
  'approval-inbox',
  'moderation-gallery',
  'operational-ledger',
  'calendar-view',
  'tree-view',
  'button',
  'divider',
  'space',
  'stack',
  'empty',
  'container',
  'flex',
  'box',
  'aspectratio',
  'semanticsurface',
  'responsiveslot',
  'showhide',
  'iconframe',
  'treeselect',
  'resizehandle',
  'loadingindicator',
  'voiceinput',
  'meter',
  'visuallyhidden',
];

export default async function ComponentBehaviorsPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const raw = Array.isArray(params.only) ? params.only[0] : params.only;
  const only = (CASES as string[]).includes(raw ?? '') ? (raw as ComponentBehaviorCase) : 'tabs';
  return (
    <>
      <JudgeOverlay searchParams={searchParams} />
      <ComponentBehaviorScene only={only} />
    </>
  );
}
