/**
 * @fileoverview Type-safe column builder utilities for constructing ColumnDef
 * arrays with type inference. Provides `column()`, `columns()`, and
 * `actionsColumn()` helpers that infer accessor keys from the row type.
 *
 * These helpers are a convenience layer over raw `ColumnDef` objects.
 * Use them to get compile-time key validation and auto-generated headers.
 *
 * @example
 * ```tsx
 * const cols = columns<User>([
 *   column('name', { sortable: true }),
 *   column('email'),
 *   actionsColumn((row) => <Button onClick={() => edit(row)}>Edit</Button>),
 * ]);
 * ```
 */

import type { ReactNode } from 'react';
import type { ColumnDef } from '../types';

type ColumnOptions<T, K extends keyof T & string> = Omit<ColumnDef<T>, 'key' | 'accessorKey'> & {
  header?: ReactNode;
};

/**
 * Creates a single column definition with type-safe key inference.
 *
 * The `key` parameter is constrained to `keyof T & string`, so passing a
 * key that doesn't exist on the row type causes a compile error. When no
 * explicit `header` is provided, one is generated by capitalizing the key.
 *
 * @param key - A string property name of the row type `T`.
 * @param options - Optional overrides (header, render, sortable, width, etc.).
 * @returns A fully-formed `ColumnDef<T>`.
 *
 * @example
 * ```tsx
 * column<User>('email', { sortable: true, width: 250 })
 * ```
 */
export function column<T, K extends keyof T & string>(
  key: K,
  options: ColumnOptions<T, K> = {} as ColumnOptions<T, K>
): ColumnDef<T> {
  const { header, ...rest } = options;
  // Auto-generate a human-readable header from the key when not provided.
  return {
    key,
    accessorKey: key,
    header: header ?? key.charAt(0).toUpperCase() + key.slice(1),
    ...rest,
  };
}

/**
 * Identity function that narrows a `ColumnDef` array to a specific row type.
 *
 * Useful when constructing column arrays inline -- without this wrapper,
 * TypeScript would widen the array to `ColumnDef<unknown>[]`.
 *
 * @param defs - Array of column definitions.
 * @returns The same array, typed as `ColumnDef<T>[]`.
 */
export function columns<T>(defs: ColumnDef<T>[]): ColumnDef<T>[] {
  return defs;
}

/**
 * Creates a special column for row-level action buttons (edit, delete, etc.).
 *
 * The column has no data accessor -- its `render` callback receives the full
 * row object. It defaults to right-aligned with an auto width and the
 * reserved key `__actions`.
 *
 * @param render - Callback that receives the row and index, returns action UI.
 * @param options - Optional overrides (key, width, header, etc.).
 * @returns A `ColumnDef<T>` configured for action rendering.
 *
 * @example
 * ```tsx
 * actionsColumn<User>((user) => (
 *   <Button size="sm" onClick={() => deleteUser(user.id)}>Delete</Button>
 * ))
 * ```
 */
export function actionsColumn<T>(
  render: (row: T, index: number) => ReactNode,
  options: Partial<ColumnDef<T>> = {}
): ColumnDef<T> {
  return {
    key: '__actions',
    header: '',
    align: 'right',
    width: 'auto',
    render: (_value, row, index) => render(row, index),
    ...options,
  };
}
