/**
 * The drill for `theme-decision-schema`: a generator whose `--check` cannot go
 * red is a generator nobody is verifying.
 */

import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import test from 'node:test';

import { OUTPUT_PATH, check, parseCommand, render, enforceableDomains } from './index.mjs';
import { readThemeCatalog } from '../../../libraries/theme-catalog/index.mjs';

test('the grammar is closed and rejects everything else', () => {
  assert.deepEqual(parseCommand(['--check']), { ok: true, command: 'check' });
  assert.deepEqual(parseCommand(['--write']), { ok: true, command: 'write' });
  for (const argv of [[], ['--check', '--write'], ['--drill'], ['--check=1'], ['x']]) {
    assert.equal(parseCommand(argv).ok, false, `${JSON.stringify(argv)} must be rejected`);
  }
});

test('the live tree is fresh', () => {
  assert.deepEqual(check(), []);
});

test('every enforceable domain comes from the catalog and nothing is invented', () => {
  const rows = new Map(readThemeCatalog().map((row) => [row.id, row]));
  for (const entry of enforceableDomains()) {
    const row = rows.get(entry.id);
    assert.ok(row, `${entry.id} must be a catalog row`);
    if (entry.kind === 'enum') assert.deepEqual(entry.values, row.domain.values);
    if (entry.kind === 'scale') assert.deepEqual(entry.bounds, row.domain.bounds);
    if (entry.kind === 'color-set') assert.deepEqual(entry.roles, row.domain.roles);
  }
  // A `registered` or `record` domain must NOT reach the schema: restating a
  // registry's ids here would make this file a second registry.
  const enforced = new Set(enforceableDomains().map((entry) => entry.id));
  for (const row of readThemeCatalog()) {
    if (row.domain.kind === 'registered' || row.domain.kind === 'record') {
      assert.equal(enforced.has(row.id), false, `${row.id} must stay with its own owner`);
    }
  }
});

test('DRILL: a catalog whose domain moved makes --check go red', () => {
  const box = mkdtempSync(join(tmpdir(), 'theme-schema-drill-'));
  try {
    // The mutant is the OUTPUT, which is what `--check` compares: a byte that
    // drifts from the catalog must be caught, whichever side moved it.
    const original = readFileSync(OUTPUT_PATH, 'utf8');
    const mutant = original.replace('"compact", "normal", "spacious"', '"compact", "normal", "spacious", "roomy"');
    assert.notEqual(mutant, original, 'the drill must actually plant something');
    writeFileSync(OUTPUT_PATH, mutant);
    try {
      const failures = check();
      assert.equal(failures.length, 1);
      assert.match(failures[0], /is STALE relative to/u);
    } finally {
      writeFileSync(OUTPUT_PATH, original);
    }
    assert.deepEqual(check(), []);
  } finally {
    rmSync(box, { recursive: true, force: true });
  }
});

test('DRILL: a missing module is reported as missing, not as fresh', () => {
  const original = readFileSync(OUTPUT_PATH, 'utf8');
  rmSync(OUTPUT_PATH);
  try {
    const failures = check();
    assert.equal(failures.length, 1);
    assert.match(failures[0], /is missing — run --write/u);
  } finally {
    mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
    writeFileSync(OUTPUT_PATH, original);
  }
  assert.deepEqual(check(), []);
});

test('the rendered module carries the generated banner the structure audit reads', () => {
  assert.match(render(), /^\/\*\*\n \* @generated by/u);
});
