#!/usr/bin/env node
/**
 * theme-decision-schema — the DB validator, GENERATED from the typed catalog.
 *
 * WHAT IT CLOSES. `assertTenantThemeDocumentV2` owns the KEY SETS (version,
 * plan, decision ids, tier entitlement, the D-03 walk) and deliberately does
 * not check values: a document contract cannot depend on the numeric envelope
 * a vertical narrows. The VALUES are the catalog's closed domains, and this
 * generator projects them into the compiler-side schema so the two can never
 * disagree -- there is one domain table and it is not written by hand.
 *
 * WHAT IT DOES NOT CHECK. `registered` domains (experience profile, recipe
 * profile, font packs) resolve fail-closed in the registry that owns their ids;
 * restating those ids here would be a second registry. `record` domains have
 * their key sets closed by the document contract and their values owned by the
 * family contract.
 *
 * COMMAND GRAMMAR (closed, exactly ONE token):
 *   --write   regenerate the schema module
 *   --check   fail if the emitted module is not byte-identical to the catalog's
 *
 * Exit codes: 0 = ok · 1 = stale or missing · 2 = invalid usage.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { packageRoot as findPackageRoot } from '../../../libraries/repo-root/index.mjs';
import { readThemeCatalog } from '../../../libraries/theme-catalog/index.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const CORE_ROOT = findPackageRoot(HERE);

export const OUTPUT_PATH = join(
  CORE_ROOT,
  'src/infrastructure/compilers/kernel/foundation/schemas/tenant-theme/decisions/index.ts',
);

export const USAGE =
  'theme-decision-schema USAGE — exactly ONE command: --check | --write';

export function parseCommand(argv) {
  if (!Array.isArray(argv) || argv.length === 0) {
    return { ok: false, error: 'no command: exactly ONE token is required' };
  }
  if (argv.length > 1) {
    return { ok: false, error: `${argv.length} tokens received: the grammar admits exactly ONE` };
  }
  const [token] = argv;
  if (token === '--check') return { ok: true, command: 'check' };
  if (token === '--write') return { ok: true, command: 'write' };
  return { ok: false, error: `unrecognised token ${JSON.stringify(token)}` };
}

const literal = (value) => JSON.stringify(value);

/** The domain entries the schema can actually enforce. */
export function enforceableDomains(rows = readThemeCatalog()) {
  const entries = [];
  for (const row of rows) {
    const domain = row.domain ?? {};
    if (domain.kind === 'enum') {
      entries.push({ id: row.id, kind: 'enum', values: domain.values });
    } else if (domain.kind === 'scale') {
      entries.push({ id: row.id, kind: 'scale', bounds: domain.bounds });
    } else if (domain.kind === 'color-set') {
      entries.push({ id: row.id, kind: 'color-set', roles: domain.roles });
    }
  }
  return entries;
}

export function render(rows = readThemeCatalog()) {
  const entries = enforceableDomains(rows);
  const lines = entries.map((entry) => {
    if (entry.kind === 'enum') {
      return `  ${literal(entry.id)}: { kind: "enum", values: [${entry.values
        .map(literal)
        .join(', ')}] },`;
    }
    if (entry.kind === 'scale') {
      return `  ${literal(entry.id)}: { kind: "scale", min: ${entry.bounds.min}, max: ${entry.bounds.max} },`;
    }
    return `  ${literal(entry.id)}: { kind: "color-set", roles: [${entry.roles
      .map(literal)
      .join(', ')}] },`;
  });
  const source = relative(CORE_ROOT, OUTPUT_PATH).replaceAll('\\', '/');
  return `/**
 * @generated by \`packages/core/scripts/generate/theme/schema/index.mjs --write\`.
 * Do not edit: the domains are the typed catalog's, and \`--check\` fails on drift.
 *
 * The DB-side value schema for a v2 decision document. The document contract
 * closes the KEY sets; this module closes the VALUES of every domain the
 * catalog states in full. \`registered\` domains stay with their registry and
 * \`record\` domains with their family contract, so neither is restated here.
 *
 * @module Compilers/Kernel/Foundation/Schemas/TenantTheme/Decisions
 * @category Compilers
 * @package @rottay/design-system
 */

import type { ThemeDecisionId } from "@/contracts/theme/foundation/decisions";

export type ThemeDecisionDomain =
  | { readonly kind: "enum"; readonly values: readonly string[] }
  | { readonly kind: "scale"; readonly min: number; readonly max: number }
  | { readonly kind: "color-set"; readonly roles: readonly string[] };

export const THEME_DECISION_DOMAIN_SCHEMA: Readonly<
  Partial<Record<ThemeDecisionId, ThemeDecisionDomain>>
> = Object.freeze({
${lines.join('\n')}
});

/** Refusals name the decision, the value and the domain it left. */
export class ThemeDecisionDomainError extends Error {
  constructor(message: string) {
    super(\`TenantThemeDocument v2: \${message}\`);
    this.name = "ThemeDecisionDomainError";
  }
}

const HEX = /^#(?:[0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/iu;

/**
 * Closes the VALUES of a validated v2 decision map, fail-closed and by name.
 *
 * Called by the v2 admission, after the document contract has closed the key
 * sets. A value outside its domain is refused rather than clamped: clamping is
 * an envelope decision and belongs to admission, not to a schema.
 */
export function assertThemeDecisionDomains(
  decisions: Readonly<Record<string, unknown>>
): void {
  for (const [id, value] of Object.entries(decisions)) {
    if (value === undefined) continue;
    const domain = THEME_DECISION_DOMAIN_SCHEMA[id as ThemeDecisionId];
    if (!domain) continue;
    if (domain.kind === "enum") {
      if (!domain.values.includes(value as string)) {
        throw new ThemeDecisionDomainError(
          \`decision "\${id}" value \${JSON.stringify(value)} is outside its closed domain \` +
            domain.values.join(" | ")
        );
      }
      continue;
    }
    if (domain.kind === "scale") {
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new ThemeDecisionDomainError(
          \`decision "\${id}" must be a finite number; got \${JSON.stringify(value)}\`
        );
      }
      if (value < domain.min || value > domain.max) {
        throw new ThemeDecisionDomainError(
          \`decision "\${id}" value \${value} is outside its closed range \` +
            \`[\${domain.min}, \${domain.max}]\`
        );
      }
      continue;
    }
    for (const [role, seed] of Object.entries(
      (value ?? {}) as Record<string, unknown>
    )) {
      if (seed === undefined) continue;
      if (typeof seed !== "string" || !HEX.test(seed)) {
        throw new ThemeDecisionDomainError(
          \`decision "\${id}" role "\${role}" must be a hex colour; got \${JSON.stringify(seed)}\`
        );
      }
    }
  }
}

/** The source this module is generated from, for a reader who lands here. */
export const THEME_DECISION_SCHEMA_SOURCE =
  "src/contracts/theme/runtime/catalog (generated into ${source})";
`;
}

export function check() {
  const expected = render();
  if (!existsSync(OUTPUT_PATH)) {
    return [`theme-decision-schema: ${relative(CORE_ROOT, OUTPUT_PATH)} is missing — run --write`];
  }
  const actual = readFileSync(OUTPUT_PATH, 'utf8');
  if (actual !== expected) {
    return [
      `theme-decision-schema: ${relative(CORE_ROOT, OUTPUT_PATH)} is STALE relative to ` +
        'src/contracts/theme/runtime/catalog — regenerate with --write',
    ];
  }
  return [];
}

export function write() {
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, render());
  return OUTPUT_PATH;
}

const invokedDirectly =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];

if (invokedDirectly) {
  const parsed = parseCommand(process.argv.slice(2));
  if (!parsed.ok) {
    console.error(`${parsed.error}\n${USAGE}`);
    process.exit(2);
  }
  if (parsed.command === 'write') {
    console.log(`theme-decision-schema written: ${relative(CORE_ROOT, write())}`);
    process.exit(0);
  }
  const failures = check();
  for (const failure of failures) console.error(failure);
  if (failures.length > 0) process.exit(1);
  console.log(
    `theme-decision-schema OK — ${enforceableDomains().length} closed domains projected from the catalog`,
  );
}
