/** @deprecated Import from 'tenancy/' instead */
export {
  isValidTenantConfig,
  isValidBranding,
  isValidPlan,
  isValidEngineName,
  createTenantSchemaConfig as createTenantSchemaConfig,
  DEFAULT_TENANT_CONFIG,
  getDefaultTenantConfig,
  resolveTenant,
  resolveFromSubdomain,
  resolveFromDomain,
  resolveFromHeader,
  configureDomainLookup,
  setServerHeaders,
  clearServerHeaders,
  getTenantConfig,
  loadStaticTenantConfig,
  generateTenantCss,
  generateTenantCssFile,
  buildTenantSelector,
  fetchRemoteTenantConfig,
  configureTenantApi,
  clearTenantCache,
  preloadTenantConfig,
  getKnownTenantConfig,
  isKnownTenant,
  getKnownTenantSlugs,
  getDefaultTenant,
  DEFAULT_TENANT_SLUG,
} from '../../tenancy';
export type { ResolverOptions, GenerateTenantCssOptions } from '../../tenancy';
