'use client';

/**
 * PlMfaSetup - Wizard Preset
 * Multi-step wizard guiding users through MFA setup:
 * Select Method → Configure → Verify → Backup Codes → Complete
 */

import { useState, useMemo, useCallback, useEffect, useRef } from 'react';
import { createPreset, type PresetContext } from '../../../factory';
import {
  createCardStyle,
  createBadgeStyle,
  createSurfaceStyle,
  createProgressBarStyle,
  createStatusDotStyle,
  createAccentBarStyle,
} from '../../../helpers';
import type { PlMfaSetupProps, MfaMethodType, SetupStep } from '../../core';
import { PL_MFA_SETUP_DEFAULTS } from '../../core';
import type { DesignTokens } from '../../../../../core/types/tokens';
import {
  Smartphone,
  Mail,
  Key,
  Fingerprint,
  Shield,
  ShieldCheck,
  QrCode,
  CheckCircle,
  ChevronRight,
  ChevronLeft,
  Download,
  Copy,
  Check,
  Printer,
  AlertTriangle,
  Lock,
  Clock,
  ArrowRight,
  RefreshCw,
  Eye,
  EyeOff,
  Info,
  Sparkles,
  X,
} from 'lucide-react';

// ─── Step Labels ──────────────────────────────────────────────────────────

const STEP_LABELS: Record<SetupStep, string> = {
  select_method: 'Select Method',
  configure: 'Configure',
  verify: 'Verify',
  backup_codes: 'Backup Codes',
  complete: 'Complete',
};

const STEPS: SetupStep[] = ['select_method', 'configure', 'verify', 'backup_codes', 'complete'];

// ─── Method Config ────────────────────────────────────────────────────────

interface MethodConfig {
  icon: React.ComponentType<{ size?: number; color?: string }>;
  name: string;
  description: string;
  longDescription: string;
  securityLevel: 'low' | 'medium' | 'high' | 'critical';
  securityLabel: string;
  setupTime: string;
  recommended?: boolean;
}

function getMethodConfig(tokens: DesignTokens): Record<MfaMethodType, MethodConfig> {
  return {
    totp: {
      icon: Smartphone,
      name: 'Authenticator App',
      description: 'Use Google Authenticator, Authy, or 1Password',
      longDescription: 'Time-based one-time passwords generated by an authenticator app on your device. Works offline and provides strong security.',
      securityLevel: 'critical',
      securityLabel: 'Highest',
      setupTime: '2 min',
      recommended: true,
    },
    sms: {
      icon: Smartphone,
      name: 'SMS Verification',
      description: 'Receive verification codes via text message',
      longDescription: 'A verification code will be sent to your phone number each time you sign in. Requires cellular service.',
      securityLevel: 'medium',
      securityLabel: 'Medium',
      setupTime: '1 min',
    },
    email: {
      icon: Mail,
      name: 'Email Verification',
      description: 'Receive verification codes via email',
      longDescription: 'A one-time code will be sent to your verified email address. Convenient but less secure than app-based methods.',
      securityLevel: 'low',
      securityLabel: 'Basic',
      setupTime: '1 min',
    },
    webauthn: {
      icon: Fingerprint,
      name: 'Biometric / Security Key',
      description: 'Use Touch ID, Face ID, YubiKey, or Windows Hello',
      longDescription: 'Hardware-based authentication using biometrics or a physical security key. Phishing-resistant and highly secure.',
      securityLevel: 'critical',
      securityLabel: 'Highest',
      setupTime: '1 min',
      recommended: true,
    },
    backup_codes: {
      icon: Shield,
      name: 'Backup Codes',
      description: 'One-time use recovery codes for emergencies',
      longDescription: 'Generate a set of single-use codes to access your account if you lose access to your primary MFA method.',
      securityLevel: 'medium',
      securityLabel: 'Recovery',
      setupTime: '1 min',
    },
  };
}

// ─── Security Level Colors ────────────────────────────────────────────────

function getSecurityColor(level: string, tokens: DesignTokens): { bg: string; text: string; fill: string } {
  switch (level) {
    case 'critical':
      return { bg: tokens.colors.successScale[50], text: tokens.colors.successScale[700], fill: tokens.colors.successScale[500] };
    case 'high':
      return { bg: tokens.colors.infoScale[50], text: tokens.colors.infoScale[700], fill: tokens.colors.infoScale[500] };
    case 'medium':
      return { bg: tokens.colors.warningScale[50], text: tokens.colors.warningScale[700], fill: tokens.colors.warningScale[500] };
    case 'low':
    default:
      return { bg: tokens.colors.errorScale[50], text: tokens.colors.errorScale[700], fill: tokens.colors.errorScale[500] };
  }
}

function getSecurityBars(level: string): number {
  switch (level) {
    case 'critical': return 4;
    case 'high': return 3;
    case 'medium': return 2;
    case 'low': return 1;
    default: return 0;
  }
}

// ─── Wizard Preset ────────────────────────────────────────────────────────

export const WizardPlMfaSetup = createPreset<PlMfaSetupProps>({
  name: 'PlMfaSetup.Wizard',
  render: ({ primitives, props, tokens, engine }: PresetContext<PlMfaSetupProps>) => {
    const { Box, Stack } = primitives;
    const isModern = tokens.surface.useGlass;

    const {
      methods,
      setupState,
      onMethodSelect,
      onVerify,
      onDownloadBackupCodes,
      onComplete,
      className,
      style,
    } = props;

    // ─── Internal State ─────────────────────────────────────────────────

    const [verificationCode, setVerificationCode] = useState(['', '', '', '', '', '']);
    const [copiedCode, setCopiedCode] = useState<string | null>(null);
    const [copiedAll, setCopiedAll] = useState(false);
    const [codesVisible, setCodesVisible] = useState(true);
    const [resendTimer, setResendTimer] = useState(0);
    const [hoveredMethod, setHoveredMethod] = useState<MfaMethodType | null>(null);
    const [selectedInfoMethod, setSelectedInfoMethod] = useState<MfaMethodType | null>(null);
    const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

    const currentStep = setupState?.currentStep || 'select_method';
    const selectedMethod = setupState?.selectedMethod;
    const qrCodeUrl = setupState?.qrCodeUrl;
    const backupCodes = setupState?.backupCodes || [];
    const currentStepIndex = STEPS.indexOf(currentStep);

    const methodConfig = useMemo(() => getMethodConfig(tokens), [tokens]);

    // ─── Countdown Timer ────────────────────────────────────────────────

    useEffect(() => {
      if (resendTimer <= 0) return;
      const interval = setInterval(() => {
        setResendTimer(prev => Math.max(0, prev - 1));
      }, 1000);
      return () => clearInterval(interval);
    }, [resendTimer]);

    // ─── Glass Style ────────────────────────────────────────────────────

    const glassCardStyle = isModern && tokens.glass ? {
      backdropFilter: tokens.glass.blur,
      WebkitBackdropFilter: tokens.glass.blur,
      backgroundColor: tokens.glass.bg,
      border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.glass.border}`,
    } : {};

    // ─── Handlers ───────────────────────────────────────────────────────

    const handleCodeInput = useCallback((index: number, value: string) => {
      if (!/^\d?$/.test(value)) return;
      const newCode = [...verificationCode];
      newCode[index] = value;
      setVerificationCode(newCode);
      if (value && index < 5) {
        inputRefs.current[index + 1]?.focus();
      }
    }, [verificationCode]);

    const handleCodeKeyDown = useCallback((index: number, e: React.KeyboardEvent) => {
      if (e.key === 'Backspace' && !verificationCode[index] && index > 0) {
        inputRefs.current[index - 1]?.focus();
      }
    }, [verificationCode]);

    const handleCodePaste = useCallback((e: React.ClipboardEvent) => {
      e.preventDefault();
      const pasted = e.clipboardData.getData('text').replace(/\D/g, '').slice(0, 6);
      if (pasted.length > 0) {
        const newCode = [...verificationCode];
        for (let i = 0; i < pasted.length && i < 6; i++) {
          newCode[i] = pasted[i];
        }
        setVerificationCode(newCode);
        const nextIdx = Math.min(pasted.length, 5);
        inputRefs.current[nextIdx]?.focus();
      }
    }, [verificationCode]);

    const fullCode = verificationCode.join('');

    const handleCopySingle = useCallback((code: string) => {
      navigator.clipboard?.writeText(code);
      setCopiedCode(code);
      setTimeout(() => setCopiedCode(null), 2000);
    }, []);

    const handleCopyAll = useCallback(() => {
      navigator.clipboard?.writeText(backupCodes.join('\n'));
      setCopiedAll(true);
      setTimeout(() => setCopiedAll(false), 2500);
    }, [backupCodes]);

    const handleResend = useCallback(() => {
      setResendTimer(30);
    }, []);

    // ─── Progress Percentage ────────────────────────────────────────────

    const progressPercent = ((currentStepIndex + 1) / STEPS.length) * 100;

    // ─── Render: Progress Bar ───────────────────────────────────────────

    const renderProgressBar = () => {
      const progressStyles = createProgressBarStyle(tokens, { percent: progressPercent });
      return (
        <div style={{ marginBottom: tokens.spacing[6] }}>
          <div style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: tokens.spacing[2],
          }}>
            <span style={{
              fontSize: tokens.typography.fontSize.xs,
              fontWeight: tokens.typography.fontWeight.medium,
              color: tokens.colors.neutral[500],
            }}>
              Step {currentStepIndex + 1} of {STEPS.length}
            </span>
            <span style={{
              fontSize: tokens.typography.fontSize.xs,
              fontWeight: tokens.typography.fontWeight.semibold,
              color: tokens.colors.primaryScale[600],
            }}>
              {Math.round(progressPercent)}%
            </span>
          </div>
          <div style={{
            ...progressStyles.track,
            height: 4,
          }}>
            <div style={progressStyles.fill} />
          </div>
        </div>
      );
    };

    // ─── Render: Step Indicator ──────────────────────────────────────────

    const renderStepIndicator = () => (
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 0,
        marginBottom: tokens.spacing[8],
        padding: `0 ${tokens.spacing[4]}px`,
      }}>
        {STEPS.map((step, idx) => {
          const isActive = idx === currentStepIndex;
          const isCompleted = idx < currentStepIndex;
          const label = STEP_LABELS[step];

          return (
            <div key={step} style={{ display: 'flex', alignItems: 'center', flex: idx < STEPS.length - 1 ? 1 : 'none' }}>
              <div style={{
                display: 'flex',
                flexDirection: 'column' as const,
                alignItems: 'center',
                gap: tokens.spacing[2],
                position: 'relative' as const,
                zIndex: 1,
              }}>
                <div style={{
                  width: 44,
                  height: 44,
                  borderRadius: tokens.borderRadius.full,
                  backgroundColor: isCompleted
                    ? tokens.colors.successScale[500]
                    : isActive
                      ? tokens.colors.primaryScale[500]
                      : tokens.colors.neutral[100],
                  color: isCompleted || isActive
                    ? tokens.colors.common.white
                    : tokens.colors.neutral[400],
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontWeight: tokens.typography.fontWeight.bold,
                  fontSize: tokens.typography.fontSize.sm,
                  transition: `all ${tokens.motion.hover}`,
                  boxShadow: isActive ? `0 0 0 4px ${tokens.colors.primaryScale[100]}` : 'none',
                  border: isCompleted
                    ? 'none'
                    : isActive
                      ? 'none'
                      : `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[200]}`,
                }}>
                  {isCompleted ? <Check size={20} /> : idx + 1}
                </div>
                <span style={{
                  fontSize: tokens.typography.fontSize.xs,
                  color: isActive
                    ? tokens.colors.primaryScale[700]
                    : isCompleted
                      ? tokens.colors.successScale[600]
                      : tokens.colors.neutral[500],
                  fontWeight: isActive
                    ? tokens.typography.fontWeight.semibold
                    : tokens.typography.fontWeight.normal,
                  whiteSpace: 'nowrap' as const,
                }}>
                  {label}
                </span>
              </div>
              {idx < STEPS.length - 1 && (
                <div style={{
                  flex: 1,
                  height: 2,
                  backgroundColor: idx < currentStepIndex
                    ? tokens.colors.successScale[400]
                    : tokens.colors.neutral[200],
                  marginBottom: tokens.spacing[5],
                  marginLeft: tokens.spacing[2],
                  marginRight: tokens.spacing[2],
                  transition: `background-color ${tokens.motion.hover}`,
                  borderRadius: tokens.borderRadius.full,
                }} />
              )}
            </div>
          );
        })}
      </div>
    );

    // ─── Render: Security Bars ──────────────────────────────────────────

    const renderSecurityBars = (level: string) => {
      const bars = getSecurityBars(level);
      const color = getSecurityColor(level, tokens);
      return (
        <div style={{ display: 'flex', alignItems: 'flex-end', gap: 2, height: 16 }}>
          {[1, 2, 3, 4].map(bar => (
            <div
              key={bar}
              style={{
                width: 4,
                height: 4 + bar * 3,
                borderRadius: tokens.borderRadius.sm,
                backgroundColor: bar <= bars ? color.fill : tokens.colors.neutral[200],
                transition: `all ${tokens.motion.hover}`,
              }}
            />
          ))}
        </div>
      );
    };

    // ─── Render: Method Selection ────────────────────────────────────────

    const renderMethodSelection = () => {
      const availableMethods: MfaMethodType[] = ['totp', 'sms', 'email', 'webauthn', 'backup_codes'];

      return (
        <div>
          <div style={{
            textAlign: 'center' as const,
            marginBottom: tokens.spacing[8],
          }}>
            <div style={{
              width: 64,
              height: 64,
              borderRadius: tokens.borderRadius.full,
              backgroundColor: tokens.colors.primaryScale[50],
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              margin: '0 auto',
              marginBottom: tokens.spacing[4],
            }}>
              <ShieldCheck size={32} color={tokens.colors.primaryScale[600]} />
            </div>
            <h2 style={{
              fontSize: tokens.typography.fontSize['2xl'],
              fontWeight: tokens.typography.fontWeight.bold,
              color: tokens.colors.neutral[900],
              margin: 0,
              marginBottom: tokens.spacing[2],
            }}>
              Choose Your Authentication Method
            </h2>
            <p style={{
              fontSize: tokens.typography.fontSize.sm,
              color: tokens.colors.neutral[500],
              margin: 0,
              maxWidth: 480,
              marginLeft: 'auto',
              marginRight: 'auto',
              lineHeight: tokens.typography.lineHeight.relaxed,
            }}>
              Protect your account with an additional layer of security. Select the method that works best for you.
            </p>
          </div>

          {/* Method Cards */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(2, 1fr)',
            gap: tokens.spacing[4],
            marginBottom: tokens.spacing[6],
          }}>
            {availableMethods.filter(m => m !== 'backup_codes').map((methodType) => {
              const config = methodConfig[methodType];
              const Icon = config.icon;
              const secColor = getSecurityColor(config.securityLevel, tokens);
              const isHovered = hoveredMethod === methodType;
              const isAlreadyConfigured = methods.some(m => m.type === methodType && m.status === 'active');

              return (
                <button
                  key={methodType}
                  onClick={() => !isAlreadyConfigured && onMethodSelect?.(methodType)}
                  onMouseEnter={() => setHoveredMethod(methodType)}
                  onMouseLeave={() => setHoveredMethod(null)}
                  disabled={isAlreadyConfigured}
                  style={{
                    ...createCardStyle(tokens, { elevation: isHovered && !isAlreadyConfigured ? 'md' : 'sm', interactive: !isAlreadyConfigured }),
                    padding: 0,
                    textAlign: 'left' as const,
                    cursor: isAlreadyConfigured ? 'default' : 'pointer',
                    border: isAlreadyConfigured
                      ? `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.successScale[200]}`
                      : isHovered
                        ? `2px solid ${tokens.colors.primaryScale[300]}`
                        : `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[200]}`,
                    backgroundColor: isAlreadyConfigured
                      ? tokens.colors.successScale[50]
                      : tokens.colors.common.white,
                    transition: `all ${tokens.motion.hover}`,
                    outline: 'none',
                    position: 'relative' as const,
                    overflow: 'hidden' as const,
                    opacity: isAlreadyConfigured ? 0.7 : 1,
                    transform: isHovered && !isAlreadyConfigured ? tokens.motion.transform : 'none',
                    ...(isModern ? glassCardStyle : {}),
                  }}
                >
                  {/* Accent bar */}
                  <div style={createAccentBarStyle(tokens, { position: 'top', color: secColor.fill })} />

                  <div style={{ padding: tokens.spacing[5] }}>
                    {/* Recommended badge */}
                    {config.recommended && !isAlreadyConfigured && (
                      <div style={{
                        position: 'absolute' as const,
                        top: tokens.spacing[3],
                        right: tokens.spacing[3],
                        display: 'flex',
                        alignItems: 'center',
                        gap: tokens.spacing[1],
                        ...createBadgeStyle(tokens, 'success'),
                        padding: `2px ${tokens.spacing[2]}px`,
                        fontSize: '10px',
                      }}>
                        <Sparkles size={10} />
                        Recommended
                      </div>
                    )}

                    {/* Already configured badge */}
                    {isAlreadyConfigured && (
                      <div style={{
                        position: 'absolute' as const,
                        top: tokens.spacing[3],
                        right: tokens.spacing[3],
                        display: 'flex',
                        alignItems: 'center',
                        gap: tokens.spacing[1],
                        ...createBadgeStyle(tokens, 'success'),
                        padding: `2px ${tokens.spacing[2]}px`,
                        fontSize: '10px',
                      }}>
                        <CheckCircle size={10} />
                        Configured
                      </div>
                    )}

                    {/* Icon */}
                    <div style={{
                      width: 52,
                      height: 52,
                      borderRadius: tokens.borderRadius.lg,
                      backgroundColor: isAlreadyConfigured ? tokens.colors.successScale[100] : tokens.colors.primaryScale[50],
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      marginBottom: tokens.spacing[4],
                    }}>
                      <Icon size={26} color={isAlreadyConfigured ? tokens.colors.successScale[600] : tokens.colors.primaryScale[600]} />
                    </div>

                    {/* Name + Description */}
                    <div style={{
                      fontSize: tokens.typography.fontSize.md,
                      fontWeight: tokens.typography.fontWeight.semibold,
                      color: tokens.colors.neutral[900],
                      marginBottom: tokens.spacing[1],
                    }}>
                      {config.name}
                    </div>
                    <div style={{
                      fontSize: tokens.typography.fontSize.sm,
                      color: tokens.colors.neutral[500],
                      marginBottom: tokens.spacing[4],
                      lineHeight: tokens.typography.lineHeight.relaxed,
                      minHeight: 40,
                    }}>
                      {config.description}
                    </div>

                    {/* Footer: Security + Setup Time */}
                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      paddingTop: tokens.spacing[3],
                      borderTop: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[100]}`,
                    }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: tokens.spacing[2] }}>
                        {renderSecurityBars(config.securityLevel)}
                        <span style={{
                          fontSize: tokens.typography.fontSize.xs,
                          fontWeight: tokens.typography.fontWeight.medium,
                          color: secColor.text,
                          backgroundColor: secColor.bg,
                          padding: `1px ${tokens.spacing[2]}px`,
                          borderRadius: tokens.borderRadius.full,
                        }}>
                          {config.securityLabel}
                        </span>
                      </div>
                      <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: tokens.spacing[1],
                        fontSize: tokens.typography.fontSize.xs,
                        color: tokens.colors.neutral[500],
                      }}>
                        <Clock size={12} />
                        {config.setupTime}
                      </div>
                    </div>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Info panel for selected method */}
          {selectedInfoMethod && (
            <div style={{
              ...createCardStyle(tokens, { elevation: 'sm' }),
              backgroundColor: tokens.colors.infoScale[50],
              border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.infoScale[200]}`,
              padding: tokens.spacing[4],
              marginBottom: tokens.spacing[4],
              display: 'flex',
              alignItems: 'flex-start',
              gap: tokens.spacing[3],
            }}>
              <Info size={18} color={tokens.colors.infoScale[600]} style={{ flexShrink: 0, marginTop: 2 }} />
              <div>
                <div style={{
                  fontSize: tokens.typography.fontSize.sm,
                  fontWeight: tokens.typography.fontWeight.semibold,
                  color: tokens.colors.infoScale[800],
                  marginBottom: tokens.spacing[1],
                }}>
                  About {methodConfig[selectedInfoMethod].name}
                </div>
                <div style={{
                  fontSize: tokens.typography.fontSize.sm,
                  color: tokens.colors.infoScale[700],
                  lineHeight: tokens.typography.lineHeight.relaxed,
                }}>
                  {methodConfig[selectedInfoMethod].longDescription}
                </div>
              </div>
              <button
                onClick={() => setSelectedInfoMethod(null)}
                style={{
                  background: 'none',
                  border: 'none',
                  cursor: 'pointer',
                  padding: tokens.spacing[1],
                  flexShrink: 0,
                  display: 'flex',
                  alignItems: 'center',
                }}
              >
                <X size={14} color={tokens.colors.infoScale[500]} />
              </button>
            </div>
          )}

          {/* Backup codes note */}
          <div style={{
            ...createCardStyle(tokens, { elevation: 'sm' }),
            backgroundColor: tokens.colors.warningScale[50],
            border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.warningScale[200]}`,
            padding: tokens.spacing[4],
            display: 'flex',
            alignItems: 'center',
            gap: tokens.spacing[3],
          }}>
            <Shield size={20} color={tokens.colors.warningScale[600]} style={{ flexShrink: 0 }} />
            <div style={{ flex: 1 }}>
              <div style={{
                fontSize: tokens.typography.fontSize.sm,
                fontWeight: tokens.typography.fontWeight.semibold,
                color: tokens.colors.warningScale[800],
                marginBottom: tokens.spacing[1],
              }}>
                Backup codes will be generated automatically
              </div>
              <div style={{
                fontSize: tokens.typography.fontSize.xs,
                color: tokens.colors.warningScale[700],
                lineHeight: tokens.typography.lineHeight.relaxed,
              }}>
                After verifying your primary method, you will receive backup codes for account recovery.
              </div>
            </div>
          </div>
        </div>
      );
    };

    // ─── Render: Configure Step ──────────────────────────────────────────

    const renderConfigureStep = () => {
      if (!selectedMethod) return null;
      const config = methodConfig[selectedMethod];
      const Icon = config.icon;

      return (
        <div>
          {/* Header */}
          <div style={{
            textAlign: 'center' as const,
            marginBottom: tokens.spacing[6],
          }}>
            <div style={{
              width: 56,
              height: 56,
              borderRadius: tokens.borderRadius.full,
              backgroundColor: tokens.colors.primaryScale[50],
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              margin: '0 auto',
              marginBottom: tokens.spacing[3],
            }}>
              <Icon size={28} color={tokens.colors.primaryScale[600]} />
            </div>
            <h2 style={{
              fontSize: tokens.typography.fontSize['2xl'],
              fontWeight: tokens.typography.fontWeight.bold,
              color: tokens.colors.neutral[900],
              margin: 0,
              marginBottom: tokens.spacing[2],
            }}>
              Configure {config.name}
            </h2>
            <p style={{
              fontSize: tokens.typography.fontSize.sm,
              color: tokens.colors.neutral[500],
              margin: 0,
            }}>
              Follow the instructions below to set up your authentication method
            </p>
          </div>

          {/* TOTP Setup */}
          {selectedMethod === 'totp' && (
            <div style={{
              ...createCardStyle(tokens, { elevation: 'md' }),
              backgroundColor: tokens.colors.common.white,
              padding: tokens.spacing[8],
              maxWidth: 520,
              margin: '0 auto',
              ...(isModern ? glassCardStyle : {}),
            }}>
              {/* Step instructions */}
              <div style={{
                display: 'flex',
                flexDirection: 'column' as const,
                gap: tokens.spacing[5],
              }}>
                {/* Step 1: Install app */}
                <div style={{ display: 'flex', gap: tokens.spacing[3] }}>
                  <div style={{
                    width: 28,
                    height: 28,
                    borderRadius: tokens.borderRadius.full,
                    backgroundColor: tokens.colors.primaryScale[100],
                    color: tokens.colors.primaryScale[700],
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: tokens.typography.fontSize.xs,
                    fontWeight: tokens.typography.fontWeight.bold,
                    flexShrink: 0,
                  }}>
                    1
                  </div>
                  <div>
                    <div style={{
                      fontSize: tokens.typography.fontSize.sm,
                      fontWeight: tokens.typography.fontWeight.semibold,
                      color: tokens.colors.neutral[800],
                      marginBottom: tokens.spacing[1],
                    }}>
                      Install an authenticator app
                    </div>
                    <div style={{
                      fontSize: tokens.typography.fontSize.xs,
                      color: tokens.colors.neutral[500],
                      lineHeight: tokens.typography.lineHeight.relaxed,
                    }}>
                      Download{' '}
                      <span style={{ color: tokens.colors.primaryScale[600], fontWeight: tokens.typography.fontWeight.medium }}>
                        Google Authenticator
                      </span>,{' '}
                      <span style={{ color: tokens.colors.primaryScale[600], fontWeight: tokens.typography.fontWeight.medium }}>
                        Authy
                      </span>, or{' '}
                      <span style={{ color: tokens.colors.primaryScale[600], fontWeight: tokens.typography.fontWeight.medium }}>
                        1Password
                      </span>
                    </div>
                  </div>
                </div>

                {/* Step 2: Scan QR */}
                <div style={{ display: 'flex', gap: tokens.spacing[3] }}>
                  <div style={{
                    width: 28,
                    height: 28,
                    borderRadius: tokens.borderRadius.full,
                    backgroundColor: tokens.colors.primaryScale[100],
                    color: tokens.colors.primaryScale[700],
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: tokens.typography.fontSize.xs,
                    fontWeight: tokens.typography.fontWeight.bold,
                    flexShrink: 0,
                  }}>
                    2
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{
                      fontSize: tokens.typography.fontSize.sm,
                      fontWeight: tokens.typography.fontWeight.semibold,
                      color: tokens.colors.neutral[800],
                      marginBottom: tokens.spacing[3],
                    }}>
                      Scan the QR code with your app
                    </div>

                    {/* QR Code display */}
                    <div style={{
                      display: 'flex',
                      justifyContent: 'center',
                      marginBottom: tokens.spacing[4],
                    }}>
                      <div style={{
                        width: 200,
                        height: 200,
                        backgroundColor: tokens.colors.neutral[50],
                        borderRadius: tokens.borderRadius.lg,
                        border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[200]}`,
                        display: 'flex',
                        flexDirection: 'column' as const,
                        alignItems: 'center',
                        justifyContent: 'center',
                        gap: tokens.spacing[2],
                      }}>
                        <QrCode size={80} color={tokens.colors.neutral[400]} />
                        <span style={{
                          fontSize: tokens.typography.fontSize.xs,
                          color: tokens.colors.neutral[500],
                        }}>
                          {qrCodeUrl ? 'Scan with app' : 'Loading QR code...'}
                        </span>
                      </div>
                    </div>

                    {/* Manual entry code */}
                    <div style={{
                      padding: tokens.spacing[4],
                      borderRadius: tokens.borderRadius.md,
                      backgroundColor: tokens.colors.neutral[50],
                      border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[200]}`,
                    }}>
                      <div style={{
                        fontSize: tokens.typography.fontSize.xs,
                        color: tokens.colors.neutral[500],
                        marginBottom: tokens.spacing[2],
                        display: 'flex',
                        alignItems: 'center',
                        gap: tokens.spacing[1],
                      }}>
                        <Key size={12} />
                        Can't scan? Enter this code manually:
                      </div>
                      <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                      }}>
                        <span style={{
                          fontSize: tokens.typography.fontSize.lg,
                          fontWeight: tokens.typography.fontWeight.bold,
                          color: tokens.colors.neutral[900],
                          fontFamily: 'monospace',
                          letterSpacing: '0.15em',
                        }}>
                          JBSW Y3DP EHPK 3PXP
                        </span>
                        <button
                          onClick={() => handleCopySingle('JBSWY3DPEHPK3PXP')}
                          style={{
                            display: 'flex',
                            alignItems: 'center',
                            gap: tokens.spacing[1],
                            padding: `${tokens.spacing[1]}px ${tokens.spacing[2]}px`,
                            borderRadius: tokens.borderRadius.md,
                            border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[300]}`,
                            backgroundColor: tokens.colors.common.white,
                            cursor: 'pointer',
                            fontSize: tokens.typography.fontSize.xs,
                            color: tokens.colors.neutral[600],
                            transition: `all ${tokens.motion.hover}`,
                            outline: 'none',
                          }}
                        >
                          {copiedCode === 'JBSWY3DPEHPK3PXP' ? (
                            <><Check size={12} color={tokens.colors.successScale[600]} /> Copied</>
                          ) : (
                            <><Copy size={12} /> Copy</>
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Step 3: Verify */}
                <div style={{ display: 'flex', gap: tokens.spacing[3] }}>
                  <div style={{
                    width: 28,
                    height: 28,
                    borderRadius: tokens.borderRadius.full,
                    backgroundColor: tokens.colors.primaryScale[100],
                    color: tokens.colors.primaryScale[700],
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: tokens.typography.fontSize.xs,
                    fontWeight: tokens.typography.fontWeight.bold,
                    flexShrink: 0,
                  }}>
                    3
                  </div>
                  <div style={{
                    fontSize: tokens.typography.fontSize.sm,
                    color: tokens.colors.neutral[600],
                    lineHeight: tokens.typography.lineHeight.relaxed,
                    paddingTop: tokens.spacing[1],
                  }}>
                    Click <strong>Next</strong> to verify the setup with a code from your app
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* SMS Setup */}
          {selectedMethod === 'sms' && (
            <div style={{
              ...createCardStyle(tokens, { elevation: 'md' }),
              backgroundColor: tokens.colors.common.white,
              padding: tokens.spacing[8],
              maxWidth: 520,
              margin: '0 auto',
              ...(isModern ? glassCardStyle : {}),
            }}>
              <div style={{ marginBottom: tokens.spacing[5] }}>
                <label style={{
                  display: 'block',
                  fontSize: tokens.typography.fontSize.sm,
                  fontWeight: tokens.typography.fontWeight.semibold,
                  color: tokens.colors.neutral[700],
                  marginBottom: tokens.spacing[2],
                }}>
                  Phone Number
                </label>
                <div style={{
                  display: 'flex',
                  gap: tokens.spacing[2],
                }}>
                  <div style={{
                    padding: `${tokens.spacing[2]}px ${tokens.spacing[3]}px`,
                    borderRadius: tokens.borderRadius.md,
                    border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[300]}`,
                    backgroundColor: tokens.colors.neutral[50],
                    fontSize: tokens.typography.fontSize.sm,
                    color: tokens.colors.neutral[600],
                    display: 'flex',
                    alignItems: 'center',
                  }}>
                    +1
                  </div>
                  <input
                    type="tel"
                    placeholder="(555) 123-4567"
                    value={setupState?.phoneNumber || ''}
                    readOnly
                    style={{
                      flex: 1,
                      padding: `${tokens.spacing[2]}px ${tokens.spacing[3]}px`,
                      borderRadius: tokens.borderRadius.md,
                      border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[300]}`,
                      fontSize: tokens.typography.fontSize.sm,
                      color: tokens.colors.neutral[900],
                      outline: 'none',
                      boxSizing: 'border-box' as const,
                      transition: `border-color ${tokens.motion.hover}`,
                    }}
                  />
                </div>
                <div style={{
                  fontSize: tokens.typography.fontSize.xs,
                  color: tokens.colors.neutral[500],
                  marginTop: tokens.spacing[2],
                }}>
                  Standard messaging rates may apply. We will send a verification code to this number.
                </div>
              </div>

              {/* SMS Warning */}
              <div style={{
                padding: tokens.spacing[3],
                borderRadius: tokens.borderRadius.md,
                backgroundColor: tokens.colors.warningScale[50],
                border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.warningScale[200]}`,
                display: 'flex',
                alignItems: 'flex-start',
                gap: tokens.spacing[2],
              }}>
                <AlertTriangle size={16} color={tokens.colors.warningScale[600]} style={{ flexShrink: 0, marginTop: 2 }} />
                <div style={{
                  fontSize: tokens.typography.fontSize.xs,
                  color: tokens.colors.warningScale[700],
                  lineHeight: tokens.typography.lineHeight.relaxed,
                }}>
                  SMS codes are less secure than authenticator apps due to SIM swapping risks.
                  Consider using an authenticator app for better protection.
                </div>
              </div>
            </div>
          )}

          {/* Email Setup */}
          {selectedMethod === 'email' && (
            <div style={{
              ...createCardStyle(tokens, { elevation: 'md' }),
              backgroundColor: tokens.colors.common.white,
              padding: tokens.spacing[8],
              maxWidth: 520,
              margin: '0 auto',
              ...(isModern ? glassCardStyle : {}),
            }}>
              <div style={{
                textAlign: 'center' as const,
                padding: tokens.spacing[6],
                borderRadius: tokens.borderRadius.lg,
                backgroundColor: tokens.colors.primaryScale[50],
                marginBottom: tokens.spacing[4],
              }}>
                <Mail size={40} color={tokens.colors.primaryScale[500]} style={{ marginBottom: tokens.spacing[3] }} />
                <div style={{
                  fontSize: tokens.typography.fontSize.md,
                  fontWeight: tokens.typography.fontWeight.semibold,
                  color: tokens.colors.neutral[900],
                  marginBottom: tokens.spacing[1],
                }}>
                  Verification email will be sent to
                </div>
                <div style={{
                  fontSize: tokens.typography.fontSize.sm,
                  color: tokens.colors.primaryScale[600],
                  fontWeight: tokens.typography.fontWeight.medium,
                }}>
                  {setupState?.recoveryEmail || 'your registered email'}
                </div>
              </div>
              <div style={{
                fontSize: tokens.typography.fontSize.xs,
                color: tokens.colors.neutral[500],
                textAlign: 'center' as const,
                lineHeight: tokens.typography.lineHeight.relaxed,
              }}>
                Click <strong>Next</strong> to send a verification code to your email address.
                The code will expire in 10 minutes.
              </div>
            </div>
          )}

          {/* WebAuthn Setup */}
          {selectedMethod === 'webauthn' && (
            <div style={{
              ...createCardStyle(tokens, { elevation: 'md' }),
              backgroundColor: tokens.colors.common.white,
              padding: tokens.spacing[8],
              maxWidth: 520,
              margin: '0 auto',
              ...(isModern ? glassCardStyle : {}),
            }}>
              <div style={{
                textAlign: 'center' as const,
                marginBottom: tokens.spacing[5],
              }}>
                <div style={{
                  width: 80,
                  height: 80,
                  borderRadius: tokens.borderRadius.full,
                  backgroundColor: tokens.colors.successScale[50],
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  margin: '0 auto',
                  marginBottom: tokens.spacing[4],
                }}>
                  <Fingerprint size={40} color={tokens.colors.successScale[600]} />
                </div>
                <div style={{
                  fontSize: tokens.typography.fontSize.md,
                  fontWeight: tokens.typography.fontWeight.semibold,
                  color: tokens.colors.neutral[900],
                  marginBottom: tokens.spacing[2],
                }}>
                  Register your device
                </div>
                <div style={{
                  fontSize: tokens.typography.fontSize.sm,
                  color: tokens.colors.neutral[500],
                  lineHeight: tokens.typography.lineHeight.relaxed,
                }}>
                  Click <strong>Next</strong> to begin the registration process.
                  Your browser will prompt you to authenticate.
                </div>
              </div>

              {/* Supported methods */}
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(3, 1fr)',
                gap: tokens.spacing[3],
              }}>
                {[
                  { name: 'Touch ID', icon: Fingerprint },
                  { name: 'Face ID', icon: Eye },
                  { name: 'Security Key', icon: Key },
                ].map((item) => {
                  const ItemIcon = item.icon;
                  return (
                    <div key={item.name} style={{
                      textAlign: 'center' as const,
                      padding: tokens.spacing[3],
                      borderRadius: tokens.borderRadius.md,
                      backgroundColor: tokens.colors.neutral[50],
                      border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[200]}`,
                    }}>
                      <ItemIcon size={20} color={tokens.colors.neutral[600]} style={{ marginBottom: tokens.spacing[1] }} />
                      <div style={{
                        fontSize: tokens.typography.fontSize.xs,
                        color: tokens.colors.neutral[600],
                        fontWeight: tokens.typography.fontWeight.medium,
                      }}>
                        {item.name}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      );
    };

    // ─── Render: Verify Step ────────────────────────────────────────────

    const renderVerifyStep = () => {
      const isCodeFull = fullCode.length === 6;

      return (
        <div>
          <div style={{
            textAlign: 'center' as const,
            marginBottom: tokens.spacing[6],
          }}>
            <div style={{
              width: 56,
              height: 56,
              borderRadius: tokens.borderRadius.full,
              backgroundColor: tokens.colors.infoScale[50],
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              margin: '0 auto',
              marginBottom: tokens.spacing[3],
            }}>
              <Lock size={28} color={tokens.colors.infoScale[600]} />
            </div>
            <h2 style={{
              fontSize: tokens.typography.fontSize['2xl'],
              fontWeight: tokens.typography.fontWeight.bold,
              color: tokens.colors.neutral[900],
              margin: 0,
              marginBottom: tokens.spacing[2],
            }}>
              Enter Verification Code
            </h2>
            <p style={{
              fontSize: tokens.typography.fontSize.sm,
              color: tokens.colors.neutral[500],
              margin: 0,
              lineHeight: tokens.typography.lineHeight.relaxed,
            }}>
              {selectedMethod === 'totp'
                ? 'Enter the 6-digit code from your authenticator app'
                : selectedMethod === 'sms'
                  ? 'Enter the 6-digit code sent to your phone'
                  : 'Enter the 6-digit code sent to your email'}
            </p>
          </div>

          <div style={{
            ...createCardStyle(tokens, { elevation: 'md' }),
            backgroundColor: tokens.colors.common.white,
            padding: tokens.spacing[8],
            maxWidth: 440,
            margin: '0 auto',
            ...(isModern ? glassCardStyle : {}),
          }}>
            {/* 6-digit input grid */}
            <div style={{
              display: 'flex',
              justifyContent: 'center',
              gap: tokens.spacing[2],
              marginBottom: tokens.spacing[5],
            }}>
              {verificationCode.map((digit, idx) => (
                <div key={idx} style={{ position: 'relative' as const }}>
                  <input
                    ref={(el) => { inputRefs.current[idx] = el; }}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    value={digit}
                    onChange={(e) => handleCodeInput(idx, e.target.value)}
                    onKeyDown={(e) => handleCodeKeyDown(idx, e)}
                    onPaste={idx === 0 ? handleCodePaste : undefined}
                    style={{
                      width: 48,
                      height: 56,
                      textAlign: 'center' as const,
                      fontSize: tokens.typography.fontSize['2xl'],
                      fontWeight: tokens.typography.fontWeight.bold,
                      fontFamily: 'monospace',
                      color: tokens.colors.neutral[900],
                      borderRadius: tokens.borderRadius.md,
                      border: `2px solid ${digit ? tokens.colors.primaryScale[400] : tokens.colors.neutral[300]}`,
                      backgroundColor: digit ? tokens.colors.primaryScale[50] : tokens.colors.common.white,
                      outline: 'none',
                      transition: `all ${tokens.motion.hover}`,
                      boxSizing: 'border-box' as const,
                    }}
                  />
                  {/* Separator after 3rd digit */}
                  {idx === 2 && (
                    <div style={{
                      position: 'absolute' as const,
                      right: -tokens.spacing[2],
                      top: '50%',
                      transform: 'translateY(-50%)',
                      width: 8,
                      height: 2,
                      backgroundColor: tokens.colors.neutral[300],
                      borderRadius: tokens.borderRadius.full,
                    }} />
                  )}
                </div>
              ))}
            </div>

            {/* Verify button */}
            <button
              onClick={() => onVerify?.(fullCode)}
              disabled={!isCodeFull}
              style={{
                width: '100%',
                padding: `${tokens.spacing[3]}px ${tokens.spacing[4]}px`,
                borderRadius: tokens.borderRadius.md,
                fontSize: tokens.typography.fontSize.sm,
                fontWeight: tokens.typography.fontWeight.semibold,
                backgroundColor: isCodeFull ? tokens.colors.primaryScale[600] : tokens.colors.neutral[200],
                color: isCodeFull ? tokens.colors.common.white : tokens.colors.neutral[500],
                border: 'none',
                cursor: isCodeFull ? 'pointer' : 'not-allowed',
                transition: `all ${tokens.motion.hover}`,
                outline: 'none',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: tokens.spacing[2],
              }}
            >
              <ShieldCheck size={16} />
              Verify and Continue
            </button>

            {/* Timer / Resend */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              gap: tokens.spacing[2],
              marginTop: tokens.spacing[4],
              paddingTop: tokens.spacing[4],
              borderTop: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[100]}`,
            }}>
              {resendTimer > 0 ? (
                <span style={{
                  fontSize: tokens.typography.fontSize.sm,
                  color: tokens.colors.neutral[500],
                  display: 'flex',
                  alignItems: 'center',
                  gap: tokens.spacing[1],
                }}>
                  <Clock size={14} />
                  Resend in {resendTimer}s
                </span>
              ) : (
                <button
                  onClick={handleResend}
                  style={{
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    fontSize: tokens.typography.fontSize.sm,
                    color: tokens.colors.primaryScale[600],
                    fontWeight: tokens.typography.fontWeight.medium,
                    display: 'flex',
                    alignItems: 'center',
                    gap: tokens.spacing[1],
                    padding: 0,
                    transition: `color ${tokens.motion.hover}`,
                  }}
                >
                  <RefreshCw size={14} />
                  Resend code
                </button>
              )}
            </div>

            {/* Help text */}
            <div style={{
              marginTop: tokens.spacing[3],
              padding: tokens.spacing[3],
              borderRadius: tokens.borderRadius.md,
              backgroundColor: tokens.colors.neutral[50],
              fontSize: tokens.typography.fontSize.xs,
              color: tokens.colors.neutral[500],
              lineHeight: tokens.typography.lineHeight.relaxed,
              textAlign: 'center' as const,
            }}>
              {selectedMethod === 'totp'
                ? 'Open your authenticator app to find the verification code. Codes refresh every 30 seconds.'
                : 'Did not receive the code? Check your spam folder or try resending.'}
            </div>
          </div>
        </div>
      );
    };

    // ─── Render: Backup Codes Step ──────────────────────────────────────

    const renderBackupCodesStep = () => (
      <div>
        <div style={{
          textAlign: 'center' as const,
          marginBottom: tokens.spacing[6],
        }}>
          <div style={{
            width: 56,
            height: 56,
            borderRadius: tokens.borderRadius.full,
            backgroundColor: tokens.colors.warningScale[50],
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto',
            marginBottom: tokens.spacing[3],
          }}>
            <Shield size={28} color={tokens.colors.warningScale[600]} />
          </div>
          <h2 style={{
            fontSize: tokens.typography.fontSize['2xl'],
            fontWeight: tokens.typography.fontWeight.bold,
            color: tokens.colors.neutral[900],
            margin: 0,
            marginBottom: tokens.spacing[2],
          }}>
            Save Your Backup Codes
          </h2>
          <p style={{
            fontSize: tokens.typography.fontSize.sm,
            color: tokens.colors.neutral[500],
            margin: 0,
            maxWidth: 420,
            marginLeft: 'auto',
            marginRight: 'auto',
            lineHeight: tokens.typography.lineHeight.relaxed,
          }}>
            Each code can only be used once. Keep them somewhere safe in case you lose access to your primary method.
          </p>
        </div>

        {/* Warning banner */}
        <div style={{
          ...createCardStyle(tokens, { elevation: 'sm' }),
          backgroundColor: tokens.colors.errorScale[50],
          border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.errorScale[200]}`,
          padding: tokens.spacing[4],
          maxWidth: 560,
          margin: '0 auto',
          marginBottom: tokens.spacing[4],
          display: 'flex',
          alignItems: 'flex-start',
          gap: tokens.spacing[3],
        }}>
          <AlertTriangle size={20} color={tokens.colors.errorScale[600]} style={{ flexShrink: 0, marginTop: 2 }} />
          <div>
            <div style={{
              fontSize: tokens.typography.fontSize.sm,
              fontWeight: tokens.typography.fontWeight.semibold,
              color: tokens.colors.errorScale[800],
              marginBottom: tokens.spacing[1],
            }}>
              Important: Save these codes now
            </div>
            <div style={{
              fontSize: tokens.typography.fontSize.xs,
              color: tokens.colors.errorScale[700],
              lineHeight: tokens.typography.lineHeight.relaxed,
            }}>
              You will not be able to see these codes again after leaving this page.
              Without these codes, you may lose access to your account permanently.
            </div>
          </div>
        </div>

        <div style={{
          ...createCardStyle(tokens, { elevation: 'md' }),
          backgroundColor: tokens.colors.common.white,
          padding: tokens.spacing[6],
          maxWidth: 560,
          margin: '0 auto',
          ...(isModern ? glassCardStyle : {}),
        }}>
          {/* Toggle visibility */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: tokens.spacing[4],
          }}>
            <div style={{
              fontSize: tokens.typography.fontSize.sm,
              fontWeight: tokens.typography.fontWeight.semibold,
              color: tokens.colors.neutral[700],
            }}>
              Recovery Codes ({backupCodes.length})
            </div>
            <button
              onClick={() => setCodesVisible(!codesVisible)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: tokens.spacing[1],
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                fontSize: tokens.typography.fontSize.xs,
                color: tokens.colors.neutral[600],
                padding: `${tokens.spacing[1]}px ${tokens.spacing[2]}px`,
                borderRadius: tokens.borderRadius.md,
                transition: `all ${tokens.motion.hover}`,
              }}
            >
              {codesVisible ? <EyeOff size={14} /> : <Eye size={14} />}
              {codesVisible ? 'Hide' : 'Show'}
            </button>
          </div>

          {/* Codes grid */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(2, 1fr)',
            gap: tokens.spacing[2],
            marginBottom: tokens.spacing[5],
          }}>
            {backupCodes.map((code, idx) => (
              <div
                key={idx}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  padding: `${tokens.spacing[2]}px ${tokens.spacing[3]}px`,
                  borderRadius: tokens.borderRadius.md,
                  backgroundColor: tokens.colors.neutral[50],
                  border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[200]}`,
                  transition: `all ${tokens.motion.hover}`,
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: tokens.spacing[2] }}>
                  <span style={{
                    fontSize: tokens.typography.fontSize.xs,
                    color: tokens.colors.neutral[400],
                    fontWeight: tokens.typography.fontWeight.medium,
                    width: 16,
                  }}>
                    {idx + 1}
                  </span>
                  <span style={{
                    fontSize: tokens.typography.fontSize.sm,
                    fontWeight: tokens.typography.fontWeight.semibold,
                    fontFamily: 'monospace',
                    color: tokens.colors.neutral[900],
                    letterSpacing: '0.05em',
                    filter: codesVisible ? 'none' : 'blur(4px)',
                    userSelect: codesVisible ? 'text' as const : 'none' as const,
                    transition: `filter ${tokens.motion.hover}`,
                  }}>
                    {code}
                  </span>
                </div>
                <button
                  onClick={() => handleCopySingle(code)}
                  style={{
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    padding: tokens.spacing[1],
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    borderRadius: tokens.borderRadius.sm,
                    transition: `all ${tokens.motion.hover}`,
                  }}
                >
                  {copiedCode === code ? (
                    <Check size={14} color={tokens.colors.successScale[600]} />
                  ) : (
                    <Copy size={14} color={tokens.colors.neutral[400]} />
                  )}
                </button>
              </div>
            ))}
          </div>

          {/* Action buttons */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: tokens.spacing[3],
          }}>
            <button
              onClick={handleCopyAll}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: tokens.spacing[2],
                padding: `${tokens.spacing[2]}px ${tokens.spacing[3]}px`,
                borderRadius: tokens.borderRadius.md,
                fontSize: tokens.typography.fontSize.sm,
                fontWeight: tokens.typography.fontWeight.medium,
                border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[300]}`,
                backgroundColor: tokens.colors.common.white,
                color: tokens.colors.neutral[700],
                cursor: 'pointer',
                transition: `all ${tokens.motion.hover}`,
                outline: 'none',
              }}
            >
              {copiedAll ? <Check size={14} color={tokens.colors.successScale[600]} /> : <Copy size={14} />}
              {copiedAll ? 'Copied!' : 'Copy All'}
            </button>
            <button
              onClick={onDownloadBackupCodes}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: tokens.spacing[2],
                padding: `${tokens.spacing[2]}px ${tokens.spacing[3]}px`,
                borderRadius: tokens.borderRadius.md,
                fontSize: tokens.typography.fontSize.sm,
                fontWeight: tokens.typography.fontWeight.medium,
                backgroundColor: tokens.colors.primaryScale[600],
                color: tokens.colors.common.white,
                border: 'none',
                cursor: 'pointer',
                transition: `all ${tokens.motion.hover}`,
                outline: 'none',
              }}
            >
              <Download size={14} />
              Download
            </button>
            <button
              onClick={() => window.print?.()}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: tokens.spacing[2],
                padding: `${tokens.spacing[2]}px ${tokens.spacing[3]}px`,
                borderRadius: tokens.borderRadius.md,
                fontSize: tokens.typography.fontSize.sm,
                fontWeight: tokens.typography.fontWeight.medium,
                border: `${tokens.surface.borderWidth} ${tokens.surface.borderStyle} ${tokens.colors.neutral[300]}`,
                backgroundColor: tokens.colors.common.white,
                color: tokens.colors.neutral[700],
                cursor: 'pointer',
                transition: `all ${tokens.motion.hover}`,
                outline: 'none',
              }}
            >
              <Printer size={14} />
              Print
            </button>
          </div>
        </div>
      </div>
    );

    // ─── Render: Complete Step ───────────────────────────────────────────

    const renderCompleteStep = () => {
      const configuredMethod = selectedMethod ? methodConfig[selectedMethod] : null;
      const ConfiguredIcon = configuredMethod?.icon;

      return (
        <div style={{ textAlign: 'center' as const }}>
          {/* Success animation area */}
          <div style={{
            width: 96,
            height: 96,
            borderRadius: tokens.borderRadius.full,
            backgroundColor: tokens.colors.successScale[50],
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto',
            marginBottom: tokens.spacing[5],
            boxShadow: `0 0 0 8px ${tokens.colors.successScale[100]}`,
          }}>
            <CheckCircle size={48} color={tokens.colors.successScale[500]} />
          </div>

          <h2 style={{
            fontSize: tokens.typography.fontSize['2xl'],
            fontWeight: tokens.typography.fontWeight.bold,
            color: tokens.colors.neutral[900],
            margin: 0,
            marginBottom: tokens.spacing[2],
          }}>
            MFA Setup Complete!
          </h2>
          <p style={{
            fontSize: tokens.typography.fontSize.sm,
            color: tokens.colors.neutral[500],
            marginBottom: tokens.spacing[6],
            margin: 0,
            maxWidth: 440,
            marginLeft: 'auto',
            marginRight: 'auto',
            lineHeight: tokens.typography.lineHeight.relaxed,
          }}>
            Your account is now protected with multi-factor authentication. You will need to verify your identity each time you sign in.
          </p>

          {/* Summary card */}
          <div style={{
            ...createCardStyle(tokens, { elevation: 'md' }),
            backgroundColor: tokens.colors.common.white,
            padding: tokens.spacing[5],
            maxWidth: 480,
            margin: '0 auto',
            marginBottom: tokens.spacing[6],
            textAlign: 'left' as const,
            ...(isModern ? glassCardStyle : {}),
          }}>
            <div style={{
              fontSize: tokens.typography.fontSize.xs,
              fontWeight: tokens.typography.fontWeight.semibold,
              color: tokens.colors.neutral[500],
              textTransform: 'uppercase' as const,
              letterSpacing: '0.05em',
              marginBottom: tokens.spacing[4],
            }}>
              Setup Summary
            </div>

            {/* Primary method */}
            {configuredMethod && ConfiguredIcon && (
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: tokens.spacing[3],
                padding: tokens.spacing[3],
                borderRadius: tokens.borderRadius.md,
                backgroundColor: tokens.colors.successScale[50],
                marginBottom: tokens.spacing[3],
              }}>
                <div style={{
                  width: 40,
                  height: 40,
                  borderRadius: tokens.borderRadius.md,
                  backgroundColor: tokens.colors.successScale[100],
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}>
                  <ConfiguredIcon size={20} color={tokens.colors.successScale[700]} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{
                    fontSize: tokens.typography.fontSize.sm,
                    fontWeight: tokens.typography.fontWeight.semibold,
                    color: tokens.colors.successScale[800],
                  }}>
                    {configuredMethod.name}
                  </div>
                  <div style={{
                    fontSize: tokens.typography.fontSize.xs,
                    color: tokens.colors.successScale[600],
                  }}>
                    Primary method
                  </div>
                </div>
                <CheckCircle size={18} color={tokens.colors.successScale[600]} />
              </div>
            )}

            {/* Backup codes */}
            {backupCodes.length > 0 && (
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: tokens.spacing[3],
                padding: tokens.spacing[3],
                borderRadius: tokens.borderRadius.md,
                backgroundColor: tokens.colors.neutral[50],
              }}>
                <div style={{
                  width: 40,
                  height: 40,
                  borderRadius: tokens.borderRadius.md,
                  backgroundColor: tokens.colors.neutral[100],
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}>
                  <Shield size={20} color={tokens.colors.neutral[600]} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{
                    fontSize: tokens.typography.fontSize.sm,
                    fontWeight: tokens.typography.fontWeight.semibold,
                    color: tokens.colors.neutral[800],
                  }}>
                    {backupCodes.length} Backup Codes
                  </div>
                  <div style={{
                    fontSize: tokens.typography.fontSize.xs,
                    color: tokens.colors.neutral[500],
                  }}>
                    Recovery method
                  </div>
                </div>
                <Check size={18} color={tokens.colors.neutral[500]} />
              </div>
            )}
          </div>

          {/* Done button */}
          <button
            onClick={onComplete}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: tokens.spacing[2],
              padding: `${tokens.spacing[3]}px ${tokens.spacing[8]}px`,
              borderRadius: tokens.borderRadius.md,
              fontSize: tokens.typography.fontSize.md,
              fontWeight: tokens.typography.fontWeight.semibold,
              backgroundColor: tokens.colors.primaryScale[600],
              color: tokens.colors.common.white,
              border: 'none',
              cursor: 'pointer',
              transition: `all ${tokens.motion.hover}`,
              boxShadow: tokens.shadows.md,
              outline: 'none',
            }}
          >
            Continue to Dashboard
            <ArrowRight size={18} />
          </button>
        </div>
      );
    };

    // ─── Render: Current Step ───────────────────────────────────────────

    const renderCurrentStep = () => {
      switch (currentStep) {
        case 'select_method':
          return renderMethodSelection();
        case 'configure':
          return renderConfigureStep();
        case 'verify':
          return renderVerifyStep();
        case 'backup_codes':
          return renderBackupCodesStep();
        case 'complete':
          return renderCompleteStep();
        default:
          return renderMethodSelection();
      }
    };

    // ─── Main Render ────────────────────────────────────────────────────

    return (
      <div
        className={className}
        style={{
          padding: tokens.spacing[6],
          backgroundColor: tokens.colors.neutral[50],
          minHeight: '100%',
          fontFamily: 'inherit',
          ...style,
        }}
      >
        <div style={{ maxWidth: 900, margin: '0 auto' }}>
          {renderProgressBar()}
          {renderStepIndicator()}
          {renderCurrentStep()}
        </div>
      </div>
    );
  },
});
