/**
 * @fileoverview Deterministic renderer for first-party tenant CSS artifacts.
 *
 * Dynamic, DB-driven tenant visual composition belongs to the composition
 * tier. This compiler owns only the static artifact format and selector-scope
 * projection, so it remains independent of runtime registries and peer
 * compilers.
 */

import type {
  BrandTheme,
  CompiledBrand,
  CompiledBrandModeBlock,
} from '@/foundation/contracts/composition/tenants/themes';
import type { FirstPartyVerticalId } from '@/foundation/contracts/kernel/verticals';
import { FIRST_PARTY_VERTICAL_ROSTER } from '@/foundation/tokens/ts/presentation/brand-themes';
import {
  brandModeSelector,
  compileBrandTheme,
} from '../../../kernel/runtime/brand-theme';
import { projectFirstPartyArtifactScopes } from '../../../kernel/foundation/css/scope-projection';

/** Marker written at the top of every generated vertical artifact. */
export const GENERATED_ARTIFACT_BANNER = 'GENERATED — do not edit';

/** Command shown in generated headers and used by the artifact guard. */
export const FIRST_PARTY_ARTIFACT_REGENERATE_COMMAND =
  'pnpm -C ui-design-system/packages/core build:vertical-css';

/** Static description of a first-party vertical artifact this generator owns. */
export interface FirstPartyArtifactSpec {
  /** Tenant slug, e.g. `'bithire'`. */
  slug: FirstPartyVerticalId;
  /**
   * Vertical baseline projected onto provider roots.
   *
   * Equal to `slug`, always. It is kept as its own field because the renderer
   * and the scope projection both read it by name, but it is DERIVED, never
   * authored: this field is where the roster inversion lived, spelling
   * a mismatched vertical key under the Rottay slug and forcing every
   * downstream consumer to carry both keys to survive.
   */
  verticalKey: FirstPartyVerticalId;
  /** Human-facing product name for the header banner. */
  displayName: string;
  /** Selector the compiled variable block is scoped to. */
  selector: string;
  /** Path to the authored theme, relative to `packages/core/src`. */
  authoredThemePath: string;
}

/**
 * The document-root arm of a vertical's scope.
 *
 * The roster's `selector` is the full two-arm form — a legacy
 * `html[data-tenant]` arm plus a nested `[data-ds-root][data-vertical]` arm.
 * A generated artifact is scoped to the DOCUMENT-ROOT arm only, because the
 * artifact is the top-level stylesheet a host page loads. Deriving it here
 * rather than restating a literal keeps the two spellings one fact;
 * `tests/roster-projection.test.ts` asserts this string is literally a
 * substring of the roster's own selector for the same slug, so the two cannot
 * drift into disagreement.
 */
function artifactRootSelector(slug: FirstPartyVerticalId): string {
  return `html[data-tenant='${slug}']`;
}

/**
 * First-party vertical artifacts regenerated by `build:vertical-artifacts`.
 *
 * PROJECTED FROM THE ROSTER, not restated. Every field below is a function of
 * one roster row. This array used to be a hand-maintained table, which is how
 * it came to claim a Rottay slug with a mismatched vertical key — a mapping no
 * other authority agreed with, pinned in place by a scope-projection test that
 * asserted the inversion was correct.
 *
 * Customer tenants are deliberately excluded: their DB-owned documents are
 * compiled dynamically and must never receive a precompiled artifact.
 */
export const FIRST_PARTY_ARTIFACT_SPECS: readonly FirstPartyArtifactSpec[] =
  Object.freeze(
    FIRST_PARTY_VERTICAL_ROSTER.map((row) =>
      Object.freeze({
        slug: row.slug,
        verticalKey: row.verticalKey,
        displayName: row.name,
        authoredThemePath: row.themeSourcePath,
        selector: artifactRootSelector(row.slug),
      }),
    ),
  );

/** Inputs for {@link renderVerticalArtifact}. */
export interface RenderVerticalArtifactInput {
  tenantSlug: string;
  verticalKey: string;
  authoredThemePath: string;
  displayName: string;
  selector: string;
  compiledCssVariables: Record<string, string>;
  /** Declared default mode of the compiled values; emitted as `color-scheme`. */
  colorScheme?: 'light' | 'dark';
  /** Compiled deltas for every mode the theme authors beyond its default. */
  modeBlocks?: readonly CompiledBrandModeBlock[];
  regenerateCommand: string;
}

/** Render a first-party vertical CSS artifact as a deterministic build output. */
export function renderVerticalArtifact(input: RenderVerticalArtifactInput): string {
  const {
    tenantSlug,
    verticalKey,
    authoredThemePath,
    displayName,
    selector,
    compiledCssVariables,
    colorScheme,
    modeBlocks,
    regenerateCommand,
  } = input;

  const header = [
    `/* ${GENERATED_ARTIFACT_BANNER} */`,
    '/*',
    ` * ${displayName} tenant theme.`,
    ' *',
    ' * This file is a BUILD OUTPUT compiled from ONE authored source; any manual',
    ' * edit is reverted by the DS artifact parity/guard gates:',
    ` *   ${authoredThemePath} (compiled via compileBrandTheme)`,
    ' *',
    ` * Regenerate: ${regenerateCommand}`,
    ' */',
  ].join('\n');

  // The document-root ink is artifact-format semantics, not theme content: this
  // file is the top-level stylesheet a host page loads, so it owns the root
  // chrome declaration. It is welded to the channel NAME and never to a value —
  // a DB tenant moves the same ink by moving --ds-color-text-primary through the
  // shared compileTheme lowering, with no slug branch and no second authority
  // here. Fail closed rather than paint an unauthored root: a literal fallback
  // would silently become a second theme author for every theme that lost the
  // channel, which is the exact failure this severance exists to end.
  const rootInk = compiledCssVariables['--ds-color-text-primary'];
  if (!rootInk || rootInk.trim() === '') {
    throw new Error(
      `renderVerticalArtifact: ${tenantSlug} has no compiled --ds-color-text-primary; ` +
        'the artifact cannot author the document root ink without it.',
    );
  }

  const compiledDecls = [
    ...(colorScheme ? [`  color-scheme: ${colorScheme};`] : []),
    '  color: var(--ds-color-text-primary);',
    ...Object.keys(compiledCssVariables)
      .sort()
      .map((key) => `  ${key}: ${compiledCssVariables[key]};`),
  ].join('\n');
  const compiledBlock = [
    '/* === Compiled from BrandTheme via compileBrandTheme — do not edit === */',
    `${selector} {`,
    compiledDecls,
    '}',
  ].join('\n');

  // One block per authored non-default mode, from BrandTheme.modes. Each holds
  // only the channels that mode moves; the base block above still supplies the
  // rest. These used to be hand-written blocks in the declared extension source,
  // which made that source a second theme author for every state but the default
  // one. That authority no longer exists: this renderer has one authored input.
  const modeBlockSections = (modeBlocks ?? []).map((block) =>
    [
      `/* === Compiled from BrandTheme.modes.${block.mode} — do not edit === */`,
      `${brandModeSelector(tenantSlug, block.mode)} {`,
      [
        `  color-scheme: ${block.colorScheme};`,
        ...Object.keys(block.cssVariables)
          .sort()
          .map((key) => `  ${key}: ${block.cssVariables[key]};`),
      ].join('\n'),
      '}',
    ].join('\n'),
  );

  return projectFirstPartyArtifactScopes(
    [header, compiledBlock, ...modeBlockSections].join('\n\n') + '\n',
    tenantSlug,
    verticalKey,
  );
}

/** Inputs for {@link renderFirstPartyArtifact}. */
export interface RenderFirstPartyArtifactInput {
  spec: FirstPartyArtifactSpec;
  brandTheme: BrandTheme;
  regenerateCommand?: string;
}

/**
 * Compile a first-party BrandTheme and render its artifact in one call.
 *
 * The build script, the parity tests and the gates each used to assemble
 * {@link RenderVerticalArtifactInput} by hand from the same spec. Three copies
 * of one mapping means a field added to the contract reaches some of them and
 * not others, and the artifact each produces silently disagrees — which is how
 * a caller ends up "regenerating" an artifact into a different file than the
 * build writes. There is one assembly, and it lives here.
 */
export function renderFirstPartyArtifact(input: RenderFirstPartyArtifactInput): {
  css: string;
  compiled: CompiledBrand;
} {
  const { spec, brandTheme, regenerateCommand } = input;
  const compiled = compileBrandTheme({ brandTheme, tenantSlug: spec.slug });
  return {
    compiled,
    css: renderVerticalArtifact({
      tenantSlug: spec.slug,
      verticalKey: spec.verticalKey,
      authoredThemePath: spec.authoredThemePath,
      displayName: spec.displayName,
      selector: spec.selector,
      compiledCssVariables: compiled.cssVariables,
      colorScheme: compiled.colorScheme,
      modeBlocks: compiled.modeBlocks,
      regenerateCommand: regenerateCommand ?? FIRST_PARTY_ARTIFACT_REGENERATE_COMMAND,
    }),
  };
}
