/**
 * @fileoverview Deterministic renderer for first-party tenant CSS artifacts.
 *
 * Dynamic, DB-driven tenant visual composition belongs to the composition
 * tier. This compiler owns only the static artifact format and selector-scope
 * projection, so it remains independent of runtime registries and peer
 * compilers.
 */

import type {
  BrandTheme,
  CompiledBrand,
  CompiledBrandModeBlock,
} from '@/foundation/contracts/composition/tenants/themes';
import {
  brandModeSelector,
  compileBrandTheme,
} from '../../../kernel/runtime/brand-theme';
import { projectFirstPartyArtifactScopes } from '../../../kernel/foundation/css/scope-projection';

/** Marker written at the top of every generated vertical artifact. */
export const GENERATED_ARTIFACT_BANNER = 'GENERATED — do not edit';

/** Command shown in generated headers and used by the artifact guard. */
export const FIRST_PARTY_ARTIFACT_REGENERATE_COMMAND =
  'pnpm -C ui-design-system/packages/core build:vertical-css';

/** Static description of a first-party vertical artifact this generator owns. */
export interface FirstPartyArtifactSpec {
  /** Tenant slug, e.g. `'bithire'`. */
  slug: string;
  /** Vertical baseline projected onto provider roots, e.g. `'platform'`. */
  verticalKey: string;
  /** Human-facing product name for the header banner. */
  displayName: string;
  /** Selector the compiled variable block is scoped to. */
  selector: string;
  /**
   * Path to the authored theme, relative to `packages/core/src`.
   *
   * Named rather than derived from the slug because the authored baseline lives
   * inside the vertical that owns it. A public slug cannot identify that source
   * directory reliably.
   */
  authoredThemePath: string;
}

/**
 * First-party vertical artifacts regenerated by `build:vertical-artifacts`.
 *
 * Customer tenants are deliberately excluded: their DB-owned documents are
 * compiled dynamically and must never receive a precompiled artifact.
 */
export const FIRST_PARTY_ARTIFACT_SPECS: readonly FirstPartyArtifactSpec[] = [
  {
    slug: 'bithire',
    verticalKey: 'bithire',
    displayName: 'BitHire',
    authoredThemePath: 'foundation/tokens/ts/presentation/brand-themes/bithire/index.ts',
    selector: "html[data-tenant='bithire']",
  },
  {
    slug: 'evnto',
    verticalKey: 'evnto',
    displayName: 'Evnto',
    authoredThemePath: 'foundation/tokens/ts/presentation/brand-themes/evnto/index.ts',
    selector: "html[data-tenant='evnto']",
  },
  {
    slug: 'rottay',
    verticalKey: 'platform',
    displayName: 'Rottay',
    authoredThemePath: 'foundation/tokens/ts/presentation/brand-themes/platform/index.ts',
    selector: "html[data-tenant='rottay']",
  },
];

/** Inputs for {@link renderVerticalArtifact}. */
export interface RenderVerticalArtifactInput {
  tenantSlug: string;
  verticalKey: string;
  authoredThemePath: string;
  displayName: string;
  selector: string;
  compiledCssVariables: Record<string, string>;
  /** Declared default mode of the compiled values; emitted as `color-scheme`. */
  colorScheme?: 'light' | 'dark';
  /** Compiled deltas for every mode the theme authors beyond its default. */
  modeBlocks?: readonly CompiledBrandModeBlock[];
  extensionCss: string;
  regenerateCommand: string;
}

/** Render a first-party vertical CSS artifact as a deterministic build output. */
export function renderVerticalArtifact(input: RenderVerticalArtifactInput): string {
  const {
    tenantSlug,
    verticalKey,
    authoredThemePath,
    displayName,
    selector,
    compiledCssVariables,
    colorScheme,
    modeBlocks,
    extensionCss,
    regenerateCommand,
  } = input;

  const header = [
    `/* ${GENERATED_ARTIFACT_BANNER} */`,
    '/*',
    ` * ${displayName} tenant theme.`,
    ' *',
    ' * This file is a BUILD OUTPUT assembled from two authored sources; any manual',
    ' * edit is reverted by the DS artifact parity/guard gates:',
    ` *   1. ${authoredThemePath} (compiled via compileBrandTheme)`,
    ` *   2. foundation/tokens/css/facade/artifacts/${tenantSlug}/_source/extension.css (declared extension)`,
    ' *',
    ` * Regenerate: ${regenerateCommand}`,
    ' */',
  ].join('\n');

  const compiledDecls = [
    ...(colorScheme ? [`  color-scheme: ${colorScheme};`] : []),
    ...Object.keys(compiledCssVariables)
      .sort()
      .map((key) => `  ${key}: ${compiledCssVariables[key]};`),
  ].join('\n');
  const compiledBlock = [
    '/* === Compiled from BrandTheme via compileBrandTheme — do not edit === */',
    `${selector} {`,
    compiledDecls,
    '}',
  ].join('\n');

  // One block per authored non-default mode, from BrandTheme.modes. Each holds
  // only the channels that mode moves; the base block above still supplies the
  // rest. These used to be hand-written blocks in the extension, which made the
  // extension a second theme author for every state but the default one.
  const modeBlockSections = (modeBlocks ?? []).map((block) =>
    [
      `/* === Compiled from BrandTheme.modes.${block.mode} — do not edit === */`,
      `${brandModeSelector(tenantSlug, block.mode)} {`,
      [
        `  color-scheme: ${block.colorScheme};`,
        ...Object.keys(block.cssVariables)
          .sort()
          .map((key) => `  ${key}: ${block.cssVariables[key]};`),
      ].join('\n'),
      '}',
    ].join('\n'),
  );

  const extensionSection = [
    '/* === Declared artifact extension (authored source, mechanically scoped) === */',
    extensionCss.replace(/^\s+/, '').replace(/\s+$/, ''),
  ].join('\n');

  return projectFirstPartyArtifactScopes(
    [header, compiledBlock, ...modeBlockSections, extensionSection].join(
      '\n\n',
    ) + '\n',
    tenantSlug,
    verticalKey,
  );
}

/** Inputs for {@link renderFirstPartyArtifact}. */
export interface RenderFirstPartyArtifactInput {
  spec: FirstPartyArtifactSpec;
  brandTheme: BrandTheme;
  extensionCss: string;
  regenerateCommand?: string;
}

/**
 * Compile a first-party BrandTheme and render its artifact in one call.
 *
 * The build script, the parity tests and the gates each used to assemble
 * {@link RenderVerticalArtifactInput} by hand from the same spec. Three copies
 * of one mapping means a field added to the contract reaches some of them and
 * not others, and the artifact each produces silently disagrees — which is how
 * a caller ends up "regenerating" an artifact into a different file than the
 * build writes. There is one assembly, and it lives here.
 */
export function renderFirstPartyArtifact(input: RenderFirstPartyArtifactInput): {
  css: string;
  compiled: CompiledBrand;
} {
  const { spec, brandTheme, extensionCss, regenerateCommand } = input;
  const compiled = compileBrandTheme({ brandTheme, tenantSlug: spec.slug });
  return {
    compiled,
    css: renderVerticalArtifact({
      tenantSlug: spec.slug,
      verticalKey: spec.verticalKey,
      authoredThemePath: spec.authoredThemePath,
      displayName: spec.displayName,
      selector: spec.selector,
      compiledCssVariables: compiled.cssVariables,
      colorScheme: compiled.colorScheme,
      modeBlocks: compiled.modeBlocks,
      extensionCss,
      regenerateCommand: regenerateCommand ?? FIRST_PARTY_ARTIFACT_REGENERATE_COMMAND,
    }),
  };
}
