/** Render the P1 classification ledger as markdown. */
import { readFileSync, writeFileSync } from 'node:fs';

const OUT = '/Users/daniel/Developer/Rottay/ui-design-system/test-artifacts/rottay-design-platform/r1p-round3-evidence/r1p/closure/remediation';
const L = JSON.parse(readFileSync(`${OUT}/p1-ledger.json`, 'utf-8'));
const twins = JSON.parse(readFileSync(`${OUT}/p1-value-twins.json`, 'utf-8'));
const coh = JSON.parse(readFileSync(`${OUT}/p1-alias-coherence.json`, 'utf-8'));
const grammar = JSON.parse(readFileSync(`${OUT}/p1-role-grammar.json`, 'utf-8'));
const slotRoles = JSON.parse(readFileSync(`${OUT}/p1-slot-roles.json`, 'utf-8'));
const dsDelta = JSON.parse(readFileSync(`${OUT}/p1-ds-default-delta.json`, 'utf-8'));
const fallback = JSON.parse(readFileSync(`${OUT}/p1-fallback-redundancy.json`, 'utf-8'));
const dsDeclared = JSON.parse(readFileSync(`${OUT}/p1-ds-declared.json`, 'utf-8'));

const CLASSES = [
  'existing-BrandTheme-field',
  'component-literal',
  'semantic-vocabulary',
  'unclassified-semantic',
  'obsolete',
  'legitimate-media-reduced-motion',
  'non-custom-property',
];

let md = `# P1 classification ledger — every declaration in the three static vertical extensions

Generated by \`r1p/scripts/p1/classify.mjs\` over the extensions as they stood at
the start of P1. Machine data: \`p1-ledger.json\` (per-declaration),
\`p1-contract-map.json\`, \`p1-consumer-census.json\`, \`p1-value-twins.json\`,
\`p1-alias-coherence.json\`, \`p1-slot-roles.json\`, \`p1-role-grammar.json\`,
\`p1-ds-default-delta.json\`, \`p1-fallback-redundancy.json\`, \`p1-ds-declared.json\`.

## Method

Capability is measured two ways and unioned, because either alone lies:

* **contract probe** — a sentinel value substituted into every BrandTheme leaf
  found across the three authored themes and four fixtures (947 paths), compiled,
  and diffed against the unmodified compile. Blind to a contract field that no
  donor theme happens to set.
* **emitter inventory** — \`Object.keys(chromeToVariables(populatedChrome))\`,
  1,307 names, every one conforming to \`--ds-[a-z0-9-]+\` (checked: the
  interpolated emission keys in \`chrome-variables\` do not corrupt it).

Reality is measured by a repo-wide \`var()\` consumer census over DS core,
showroom and the three apps, excluding the declaring artifacts and all test
files. A channel nothing reads is not a channel.

## Classification

| class | ${Object.keys(L.verticals).join(' | ')} |
|---|${Object.keys(L.verticals).map(() => '---:').join('|')}|
`;
for (const c of CLASSES) {
  const cells = Object.values(L.verticals).map((v) => v.tally[c] ?? 0);
  if (cells.every((n) => n === 0)) continue;
  md += `| ${c} | ${cells.join(' | ')} |\n`;
}
md += `| **total** | ${Object.values(L.verticals).map((v) => `**${v.totalDecls}**`).join(' | ')} |\n`;

md += `
## The verdict on rottay's generic block

Codex named one region carrying 1,343 declarations behind
\`purpose="flat channels the BrandTheme contract cannot express at this
granularity"\`. Four independent measurements say what it actually is, and all
four say the same thing: **it is the DS's own default component-token layer,
re-authored by hand for dark mode at tenant scope.**

1. **It is not a concentrated role vocabulary.** The ${slotRoles.total}
   component-literal declarations decompose into ${slotRoles.coverage.length}
   distinct roles across ${Object.keys(slotRoles.slots).length - 1} widget slots.
   It takes ${slotRoles.coverage.findIndex((c) => c.cumPct >= 80) + 1} roles to
   cover 80% of the corpus. A reusable role interface cannot carry a tail that long.
2. **A closed slot x role subcontract would be 96.5% empty.**
   ${Object.keys(slotRoles.slots).length - 1} slots x ${slotRoles.coverage.length}
   roles is 13,662 typed fields to carry
   ${Object.values(slotRoles.slots).reduce((a, b) => a + b.props.length, 0)} real
   channels — a density of 3.48%. Typing it moves the second UI system into
   TypeScript instead of removing it, which is exactly what Codex rejected.
3. **The channels are not coherent aliases of governed vocabulary.** rottay
   declares each channel twice, once per mode, so alias coherence is testable:
   does a channel equal the SAME governed channel in both states? Of 671 distinct
   props, ${coh.rottay.coherent.length} are coherent — but with a median of 4
   candidate twins each and only
   ${coh.rottay.coherent.filter((r) => r.sharedTwins.length === 1).length}
   resolving to exactly one. In a near-monochrome dark palette, value equality is
   collision, not meaning. A compiler-side derivation would be guessing.
4. **The DS already declares them.** ${dsDeclared.undeclared.length + Object.keys(dsDeclared.declared).length} distinct
   component channels appear in the rottay extension;
   **${Object.keys(dsDeclared.declared).length} of them are declared by the DS
   itself**, 392 in the single file
   \`foundation/tokens/css/foundation/themes/default.css\`. That file has a
   \`:root\` block of 1,429 declarations and an \`html.dark\` block of **69**.

The gap is therefore ONE gap with ONE owner, not 671 contract gaps: *the DS's
default component-token layer has no dark counterpart*, so a dark-default tenant
has to restate it. Its owner is the Modern/foundation token layer (C6.3, "generic
Modern component paint lives in Modern"), **not** BrandTheme. Neither typing the
671 fields nor deriving them is the fix, and both were considered and measured
out here rather than argued about.

That file is outside P1's declared write scope and is dirty from the concurrent
visual WIP, so P1 does not edit it. What P1 does instead is make the debt
impossible to hide: see the L-G/L-H/L-I gate laws below.

## Why the declarations cannot simply be deleted

For each declaration the ledger resolves the consuming component's own
\`var(--X, <fallback>)\` chain against the artifact's effective map with the
channel removed. If the fallback already resolves to the declared value, deleting
is a no-op and the deletion is its own death proof.

| vertical | redundant (deletable) | load-bearing | read without any fallback | unresolvable |
|---|---:|---:|---:|---:|
${['bithire', 'evnto', 'rottay'].map((s) => `| ${s} | ${fallback[s].redundant.length} | ${fallback[s].loadBearing.length} | ${fallback[s].noConsumerFallback.length} | ${fallback[s].unresolvable.length} |`).join('\n')}

rottay has **zero** redundant declarations: every one carries a value its
consumer's fallback does not reproduce. Deleting them without first giving the DS
a dark component layer would repaint the product.

## Obsolete inventory (retirable with a death proof)

Declarations whose channel has zero non-declarer, non-test readers anywhere in
DS core, showroom, app-bithire, app-evnto or app-platform:

| vertical | declarations | distinct channels | referenced by another artifact | referenced by a test |
|---|---:|---:|---:|---:|
${['bithire', 'evnto', 'rottay'].map((s) => {
  const ob = L.verticals[s].rows.filter((r) => r.cls === 'obsolete');
  return `| ${s} | ${ob.length} | ${new Set(ob.map((r) => r.prop)).size} | 0 | 0 |`;
}).join('\n')}

All three cross-checks are clean, so this set is safe to retire as a block. P1
retires one of them end to end (\`--ds-sidebar-group-border\`, below) and leaves
the rest inventoried: retiring 466 declarations is a volume drain whose acid test
belongs with the dark-layer work that has to move the same channels anyway.

## Product vocabulary (stays out of the DS)

\`--ds-ticket-*\` (6) and \`--ds-event-*\` (10) in evnto, and the
\`--ds-premium-card-*\` / \`--ds-detail-*\` / \`--ds-action-rail-*\` families in
bithire, are product semantics. CLAUDE.md is explicit ("Domain-specific tokens
\`--ds-ticket-*\`, \`--ds-event-*\` belong in consuming apps, not DS core"), so
they are residue by law, not by capability, and their retirement condition is an
app-side move — which is app-evnto / app-bithire write scope, not P1's.
`;

writeFileSync(`${OUT}/p1-ledger.md`, md);
console.log(`wrote ${OUT}/p1-ledger.md (${md.split('\n').length} lines)`);
