'use client';
import React, { forwardRef, useState, useCallback, useRef, useEffect } from 'react';
import type { InputTextAreaProps } from '../../types';
import { SIZE_MAP } from '../../types';
export const InputTextArea = forwardRef<HTMLTextAreaElement, InputTextAreaProps>((props, ref) => {
  const { value: controlledValue, defaultValue, placeholder, size = "md", variant = "outline", status = "default", disabled = false, readOnly = false, required = false, error = false, errorMessage, maxLength, minLength, rows = 4, resize = true, showCount = false, onChange, onFocus, onBlur, onKeyDown, onPressEnter, className = "", style = {}, id, name, autoComplete, autoFocus, "data-testid": dataTestId, "aria-label": ariaLabel, "aria-describedby": ariaDescribedBy } = props;
  const [internalValue, setInternalValue] = useState(defaultValue ?? "");
  const isControlled = controlledValue !== undefined;
  const currentValue = isControlled ? controlledValue : internalValue;
  const [isFocused, setIsFocused] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { if (ref) { if (typeof ref === "function") { ref(textareaRef.current); } else { (ref as React.MutableRefObject<HTMLTextAreaElement | null>).current = textareaRef.current; } } }, [ref]);
  const handleChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => { const newValue = e.target.value; if (!isControlled) { setInternalValue(newValue); } onChange?.(newValue, e as any); }, [isControlled, onChange]);
  const handleFocus = useCallback((e: React.FocusEvent<HTMLTextAreaElement>) => { setIsFocused(true); onFocus?.(e as any); }, [onFocus]);
  const handleBlur = useCallback((e: React.FocusEvent<HTMLTextAreaElement>) => { setIsFocused(false); onBlur?.(e as any); }, [onBlur]);
  const handleKeyDown = useCallback((e: React.KeyboardEvent<HTMLTextAreaElement>) => { if (e.key === "Enter" && !e.shiftKey) { onPressEnter?.(e as any); } onKeyDown?.(e as any); }, [onKeyDown, onPressEnter]);
  const hasError = error || status === "error";
  const sizeValues = SIZE_MAP[size as keyof typeof SIZE_MAP] || SIZE_MAP.md;
  const containerStyle: React.CSSProperties = { position: "relative", display: "block", width: "100%", ...style };
  const textareaStyle: React.CSSProperties = { width: "100%", padding: sizeValues.paddingX, fontSize: sizeValues.fontSize, fontFamily: "inherit", backgroundColor: variant === "filled" ? "#f5f5f5" : "transparent", borderRadius: variant === "flushed" ? 0 : 6, border: variant === "unstyled" ? "none" : variant === "flushed" ? "none" : `1px solid ${hasError ? "#ff4d4f" : isFocused ? "#1890ff" : "#d9d9d9"}`, borderBottom: variant === "flushed" ? `${isFocused ? 2 : 1}px solid ${hasError ? "#ff4d4f" : isFocused ? "#1890ff" : "#d9d9d9"}` : undefined, outline: "none", resize: resize ? "vertical" : "none", transition: "all 0.2s ease", opacity: disabled ? 0.6 : 1, cursor: disabled ? "not-allowed" : "text", boxShadow: isFocused && !hasError && variant !== "unstyled" ? "0 0 0 2px rgba(24, 144, 255, 0.2)" : hasError && variant !== "unstyled" ? "0 0 0 2px rgba(255, 77, 79, 0.2)" : "none" };
  const containerClasses = ["rottay-textarea", `rottay-textarea--${size}`, `rottay-textarea--${variant}`, isFocused && "rottay-textarea--focused", hasError && "rottay-textarea--error", disabled && "rottay-textarea--disabled", className].filter(Boolean).join(" ");
  return (<div className={containerClasses} style={containerStyle}><textarea ref={textareaRef} id={id} name={name} value={currentValue} placeholder={placeholder} disabled={disabled} readOnly={readOnly} required={required} maxLength={maxLength} minLength={minLength} rows={rows} autoComplete={autoComplete} autoFocus={autoFocus} aria-label={ariaLabel} aria-describedby={ariaDescribedBy} aria-invalid={hasError} data-testid={dataTestId} style={textareaStyle} onChange={handleChange} onFocus={handleFocus} onBlur={handleBlur} onKeyDown={handleKeyDown} />{showCount && maxLength && <span style={{ position: "absolute", right: 8, bottom: -20, fontSize: 12, color: hasError ? "#ff4d4f" : "#bfbfbf" }}>{currentValue.length}/{maxLength}</span>}{hasError && errorMessage && <span style={{ display: "block", marginTop: 4, fontSize: 12, color: "#ff4d4f" }}>{errorMessage}</span>}</div>);
});
InputTextArea.displayName = "Input.TextArea";
