/**
 * @fileoverview Wave G0 — Regression Harness And Baseline Capture
 *
 * Safety net capturing current first-party premium outputs and shared
 * generator coverage BEFORE any structural refactoring.
 *
 * Coverage matrix:
 * - palette: SHARED (generated via color scale)
 * - personality: SHARED (animation, chart, card, accent, typography)
 * - density: SHARED (--ds-density-scale)
 * - sidebar: FIRST-PARTY-ONLY (--ds-sidebar-* only in CSS snapshots)
 * - controls: FIRST-PARTY-ONLY (--ds-button-*, --ds-input-* only in CSS)
 * - table: FIRST-PARTY-ONLY (--ds-table-header-* only in CSS)
 * - layout: FIRST-PARTY-ONLY (--ds-layout-* only in CSS)
 * - shell: FIRST-PARTY-ONLY (--ds-shell-* only in CSS)
 *
 * When the shared pipeline is extended in G1, tests in the
 * "currently first-party-only" sections should start passing through
 * the shared path too.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import type { TenantConfig } from '../../contracts';
import { generateTenantCss } from '../tenancy/storage/static/generator';
import { bithireBrandTheme, evntoBrandTheme, rottayBrandTheme } from '../../tokens/ts/brand-themes';

// ── Helpers ─────────────────────────────────────────────

/** Extract all CSS variable declarations from a CSS string. */
function extractVars(css: string): string[] {
  const matches = css.match(/--[\w-]+(?=\s*:)/g);
  return matches ? [...new Set(matches)] : [];
}

/** Check that a CSS string contains all expected variable prefixes. */
function expectVarPrefixes(css: string, prefixes: string[]) {
  const vars = extractVars(css);
  for (const prefix of prefixes) {
    const found = vars.some((v) => v.startsWith(prefix));
    expect(found, `expected CSS to contain vars starting with ${prefix}`).toBe(true);
  }
}

/** Read a first-party CSS file and return its content. */
function readTenantCss(tenant: string): string {
  const cssPath = resolve(
    __dirname,
    `../../tokens/css/tenants/${tenant}/index.css`
  );
  return readFileSync(cssPath, 'utf-8');
}

// ── First-party tenant configs for testing ──────────────

const BITHIRE_CONFIG: TenantConfig = {
  slug: 'bithire',
  name: 'BitHire',
  engine: 'classic',
  theme: 'base',
  plan: 'enterprise',
  features: ['*'],
  branding: {
    companyName: 'BitHire',
    primaryColor: '#0A66C2',
    secondaryColor: '#004182',
    accentColor: '#7FC15E',
  },
  brandTheme: bithireBrandTheme,
};

const EVNTO_CONFIG: TenantConfig = {
  slug: 'evnto',
  name: 'Evnto',
  engine: 'classic',
  theme: 'base',
  plan: 'enterprise',
  features: ['*'],
  branding: {
    companyName: 'Evnto',
    primaryColor: '#171717',
    secondaryColor: '#b8a898',
    accentColor: '#b8a898',
  },
  vertical: 'evnto',
  brandTheme: evntoBrandTheme,
};

const ROTTAY_CONFIG: TenantConfig = {
  slug: 'rottay',
  name: 'Rottay',
  engine: 'classic',
  theme: 'base',
  plan: 'enterprise',
  features: ['*'],
  branding: { companyName: 'Rottay' },
  brandTheme: rottayBrandTheme,
};

// ══════════════════════════════════════════════════════════
// SECTION 1: Shared Pipeline Baseline
// These vars are generated by generateTenantCss() today.
// If any of these break, the shared pipeline regressed.
// ══════════════════════════════════════════════════════════

describe('shared pipeline: palette baseline', () => {
  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates full primary color scale',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      for (const step of [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]) {
        expect(css).toContain(`--ds-color-primary-${step}`);
      }
    }
  );
});

describe('shared pipeline: personality baseline', () => {
  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates animation personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-animation-intensity');
      expect(css).toContain('--ds-personality-animation-entrance');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates chart personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-chart-line-style');
      expect(css).toContain('--ds-personality-chart-tooltip-style');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates card personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-card-padding-density');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates accent personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-accent-bar-style');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates typography personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-typography-heading-letter-spacing');
    }
  );
});

describe('shared pipeline: density baseline', () => {
  it('bithire generates density scale from brandTheme', () => {
    const css = generateTenantCss(BITHIRE_CONFIG, { includeDarkSelector: false });
    expect(css).toContain('--ds-density-scale: 0.95');
  });

  it('evnto generates density scale from vertical + brandTheme', () => {
    const css = generateTenantCss(EVNTO_CONFIG, { includeDarkSelector: false });
    // evnto brandTheme has 1.125, evnto vertical has 1.125 too
    expect(css).toContain('--ds-density-scale: 1.125');
  });
});

// ══════════════════════════════════════════════════════════
// SECTION 2: First-Party CSS Snapshot Baseline
// These premium vars exist in handwritten CSS but are NOT yet
// generated by the shared pipeline. When G1 completes, some
// of these should move to Section 1.
// ══════════════════════════════════════════════════════════

describe('first-party CSS baseline: sidebar vars', () => {
  it('bithire CSS has sidebar chrome', () => {
    const css = readTenantCss('bithire');
    expectVarPrefixes(css, [
      '--ds-sidebar-bg',
      '--ds-sidebar-text',
      '--ds-sidebar-item-color',
      '--ds-sidebar-item-bg-active',
      '--ds-sidebar-group-font-size',
      '--ds-sidebar-icon-size',
    ]);
  });

  it('rottay CSS has sidebar chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-sidebar-bg',
      '--ds-sidebar-border',
      '--ds-sidebar-width',
      '--ds-sidebar-collapsed-width',
      '--ds-sidebar-header-height',
      '--ds-sidebar-item-font-size',
      '--ds-sidebar-footer-bg',
    ]);
  });

  it('evnto CSS has sidebar chrome', () => {
    const css = readTenantCss('evnto');
    expectVarPrefixes(css, [
      '--ds-sidebar-bg',
      '--ds-sidebar-text',
      '--ds-sidebar-item-color',
      '--ds-sidebar-group-font-size',
    ]);
  });
});

describe('first-party CSS baseline: controls vars', () => {
  it('bithire CSS has button chrome', () => {
    const css = readTenantCss('bithire');
    expectVarPrefixes(css, [
      '--ds-button-primary-bg',
      '--ds-button-primary-text',
      '--ds-button-secondary-bg',
      '--ds-button-secondary-text',
    ]);
  });

  it('bithire CSS has input chrome', () => {
    const css = readTenantCss('bithire');
    expectVarPrefixes(css, [
      '--ds-input-bg',
      '--ds-input-border',
      '--ds-input-border-focus',
    ]);
  });

  it('rottay CSS has full button variant chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-button-primary-bg',
      '--ds-button-secondary-bg',
      '--ds-button-default-bg',
      '--ds-button-ghost-bg',
      '--ds-button-success-bg',
    ]);
  });

  it('evnto CSS has button and input chrome', () => {
    const css = readTenantCss('evnto');
    expectVarPrefixes(css, [
      '--ds-button-primary-bg',
      '--ds-button-secondary-bg',
      '--ds-input-bg',
      '--ds-input-border',
    ]);
  });
});

describe('first-party CSS baseline: table vars', () => {
  it.each(['bithire', 'rottay', 'evnto'] as const)(
    '%s CSS has table header chrome',
    (tenant) => {
      const css = readTenantCss(tenant);
      expectVarPrefixes(css, ['--ds-table-header-bg']);
    }
  );
});

describe('first-party CSS baseline: layout vars', () => {
  it('rottay CSS has layout chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-layout-bg',
      '--ds-layout-header-bg',
      '--ds-layout-header-backdrop',
      '--ds-layout-sider-bg',
    ]);
  });
});

describe('first-party CSS baseline: shell vars', () => {
  it('rottay CSS has shell grid chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-shell-grid-size',
      '--ds-shell-grid-line',
    ]);
  });
});

// ══════════════════════════════════════════════════════════
// SECTION 3: Gap documentation
// Verify that the shared pipeline does NOT yet generate
// these categories — so we know what G1 needs to close.
// ══════════════════════════════════════════════════════════

describe('shared pipeline gap: vars NOT yet generated', () => {
  // Use ROTTAY_CONFIG for layout/shell/sidebar gaps because rottayBrandTheme
  // actually defines those chrome categories. Bithire is used for controls
  // since it defines button/input chrome.
  const rottayCss = generateTenantCss(ROTTAY_CONFIG, { includeDarkSelector: false });
  const bithireCss = generateTenantCss(BITHIRE_CONFIG, { includeDarkSelector: false });

  it('shared pipeline does NOT generate sidebar vars (rottay)', () => {
    expect(rottayCss).not.toContain('--ds-sidebar-bg');
    expect(rottayCss).not.toContain('--ds-sidebar-item-color');
  });

  it('shared pipeline does NOT generate button variant vars (bithire)', () => {
    expect(bithireCss).not.toContain('--ds-button-primary-bg:');
    expect(bithireCss).not.toContain('--ds-button-secondary-border');
  });

  it('shared pipeline does NOT generate input vars (bithire)', () => {
    expect(bithireCss).not.toContain('--ds-input-bg:');
    expect(bithireCss).not.toContain('--ds-input-border-focus');
  });

  it('shared pipeline does NOT generate layout vars (rottay)', () => {
    expect(rottayCss).not.toContain('--ds-layout-bg');
    expect(rottayCss).not.toContain('--ds-layout-header-bg');
  });

  it('shared pipeline does NOT generate shell vars (rottay)', () => {
    expect(rottayCss).not.toContain('--ds-shell-grid-size');
  });
});
