import type { CSSProperties } from "react";
import type { TransformTemplate } from "motion/react";

export interface ResolvedMotionTransformStyle {
  style: CSSProperties | undefined;
  transformTemplate: TransformTemplate | undefined;
}

/**
 * Compose the transform generated by Motion with a caller-owned CSS transform.
 * The generated entrance transform stays first so directional translation is
 * expressed in screen coordinates, while the consumer transform remains the
 * stable final visual state once Motion settles back to `none`.
 */
export function composeMotionTransform(
  generatedTransform: string,
  consumerTransform: string,
): string {
  const generated = generatedTransform.trim();
  const consumer = consumerTransform.trim();
  const parts = [
    generated && generated !== "none" ? generated : "",
    consumer && consumer !== "none" ? consumer : "",
  ].filter(Boolean);

  return parts.join(" ") || "none";
}

/**
 * Move a caller-owned `style.transform` into Motion's `transformTemplate`.
 * Leaving the raw transform in `style` makes Motion skip its generated x/y/
 * scale transform entirely, so entrance primitives must explicitly compose it.
 */
export function resolveMotionTransformStyle(
  style: CSSProperties | undefined,
): ResolvedMotionTransformStyle {
  if (!style) {
    return { style: undefined, transformTemplate: undefined };
  }

  const consumerTransform = style.transform?.trim();
  if (!consumerTransform) {
    return { style, transformTemplate: undefined };
  }

  const { transform: _transform, ...styleWithoutTransform } = style;
  if (consumerTransform === "none") {
    return { style: styleWithoutTransform, transformTemplate: undefined };
  }

  return {
    style: styleWithoutTransform,
    transformTemplate: (_latest, generatedTransform) =>
      composeMotionTransform(generatedTransform, consumerTransform),
  };
}
