/**
 * Self-test for engine-freeze-gate.mjs.
 *
 * The gate's whole value is that it audits HISTORY against a sealed base rather
 * than the dirty worktree, so the fixture is a real throwaway Git repository:
 * a base commit, then a second commit that edits a frozen-engine file. A
 * dirty-tree linter reports that repo as clean (nothing is uncommitted); this
 * gate must fail it. Pure-function tests drill the collectors and the verdict
 * in isolation, mirroring container-query-gate.test.mjs's direct-import style.
 *
 * Nothing here touches the real repository: every fixture lives in a temp dir
 * and the gate is always invoked with --repo/--baseline overrides.
 */
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

import {
  FROZEN,
  evaluateFreeze,
  isGeneratedPath,
  mergeChangeSets,
  parseNameStatus,
  parsePorcelainUntracked,
  sha256,
} from './engine-freeze-gate.mjs';
import { FROZEN_ENGINE_PATH } from './tenant-channel-consumer-gate.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const gate = join(scriptDir, 'engine-freeze-gate.mjs');

const FROZEN_FILE = 'packages/core/src/ui/primitives/layout/Box/engines/classic/index.tsx';
const OTHER_FROZEN_FILE = 'packages/core/src/ui/primitives/layout/Flex/engines/rustic/index.tsx';
const MODERN_FILE = 'packages/core/src/ui/primitives/layout/Box/engines/modern/index.tsx';

/* ------------------------------------------------------------------------ */
/* pure functions                                                           */
/* ------------------------------------------------------------------------ */

test('FROZEN matches classic/rustic engine folders and nothing else', () => {
  assert.ok(FROZEN.test(FROZEN_FILE));
  assert.ok(FROZEN.test(OTHER_FROZEN_FILE));
  assert.ok(!FROZEN.test(MODERN_FILE));
  // A folder that merely CONTAINS the word is not an engine folder.
  assert.ok(!FROZEN.test('packages/core/src/ui/classic-layouts/index.tsx'));
  assert.ok(!FROZEN.test('packages/core/src/ui/engines/custom/index.tsx'));
});

test('the freeze law and the consumer gate restate the SAME frozen-path regex', () => {
  // The two gates deliberately keep their own copy rather than importing each
  // other; this assertion is what stops the copies from drifting apart.
  assert.equal(FROZEN.source, FROZEN_ENGINE_PATH.source);
  assert.equal(FROZEN.flags, FROZEN_ENGINE_PATH.flags);
});

test('parseNameStatus keeps frozen paths with their status letter and drops the rest', () => {
  const rows = parseNameStatus(
    [`M\t${FROZEN_FILE}`, `A\t${OTHER_FROZEN_FILE}`, `M\t${MODERN_FILE}`, ''].join('\n'),
  );
  assert.deepEqual(rows, [
    { status: 'M', path: FROZEN_FILE, untracked: false },
    { status: 'A', path: OTHER_FROZEN_FILE, untracked: false },
  ]);
});

test('parsePorcelainUntracked reads only ?? rows (tracked edits come from the diff)', () => {
  const rows = parsePorcelainUntracked(
    [`?? ${FROZEN_FILE}`, ` M ${OTHER_FROZEN_FILE}`, `?? ${MODERN_FILE}`].join('\n'),
  );
  assert.deepEqual(rows, [{ status: 'A', path: FROZEN_FILE, untracked: true }]);
});

test('mergeChangeSets deduplicates a path reported by both collectors', () => {
  const merged = mergeChangeSets(
    [{ status: 'M', path: FROZEN_FILE, untracked: false }],
    [{ status: 'A', path: FROZEN_FILE, untracked: true }],
  );
  assert.equal(merged.length, 1);
  assert.equal(merged[0].untracked, false);
});

test('isGeneratedPath catches artifact paths and generation markers', () => {
  assert.ok(isGeneratedPath('packages/core/src/foundation/tokens/css/facade/artifacts/x.css', ''));
  assert.ok(isGeneratedPath(FROZEN_FILE, '/* @generated by the vertical CSS builder */'));
  assert.ok(isGeneratedPath(FROZEN_FILE, '// DO NOT EDIT — regenerate with pnpm icons:generate'));
  assert.ok(!isGeneratedPath(FROZEN_FILE, 'export const Box = () => null;'));
  assert.ok(!isGeneratedPath(FROZEN_FILE, null));
});

test('evaluateFreeze: an unlisted change is unauthorized, a pinned one passes', () => {
  const content = 'export const Box = () => null;\n';
  const entries = { [FROZEN_FILE]: { blob: sha256(content), reason: 'sealed' } };
  const verdict = evaluateFreeze({
    changes: [
      { status: 'M', path: FROZEN_FILE, untracked: false },
      { status: 'M', path: OTHER_FROZEN_FILE, untracked: false },
    ],
    entries,
    read: (path) => (path === FROZEN_FILE ? content : 'anything else'),
  });
  assert.deepEqual(verdict.unauthorized.map((c) => c.path), [OTHER_FROZEN_FILE]);
  assert.equal(verdict.drifted.length, 0);
});

test('evaluateFreeze: an authorized path that changed AGAIN drifts past its exception', () => {
  const entries = { [FROZEN_FILE]: { blob: sha256('reviewed'), reason: 'sealed' } };
  const verdict = evaluateFreeze({
    changes: [{ status: 'M', path: FROZEN_FILE, untracked: false }],
    entries,
    read: () => 'reviewed + a new edit',
  });
  assert.equal(verdict.unauthorized.length, 0);
  assert.deepEqual(verdict.drifted.map((c) => c.path), [FROZEN_FILE]);
});

test('evaluateFreeze: deleting an authorized file is a violation; a generated file never authorizes', () => {
  const entries = {
    [FROZEN_FILE]: { blob: sha256('reviewed'), reason: 'sealed' },
    [OTHER_FROZEN_FILE]: { blob: sha256('gen'), reason: 'sealed' },
  };
  const verdict = evaluateFreeze({
    changes: [
      { status: 'D', path: FROZEN_FILE, untracked: false },
      { status: 'M', path: OTHER_FROZEN_FILE, untracked: false },
    ],
    entries,
    read: (path) => (path === FROZEN_FILE ? null : '/* @generated */ gen'),
  });
  assert.deepEqual(verdict.deletedAuthorized.map((c) => c.path), [FROZEN_FILE]);
  assert.deepEqual(verdict.generated.map((c) => c.path), [OTHER_FROZEN_FILE]);
});

test('evaluateFreeze: an entry whose path no longer differs from the base is stale, not a failure', () => {
  const verdict = evaluateFreeze({
    changes: [],
    entries: { [FROZEN_FILE]: { blob: sha256('x'), reason: 'sealed' } },
    read: () => 'x',
  });
  assert.deepEqual(verdict.stale, [FROZEN_FILE]);
  assert.equal(verdict.unauthorized.length, 0);
});

/* ------------------------------------------------------------------------ */
/* fixture repository (CLI, end to end)                                     */
/* ------------------------------------------------------------------------ */

function fixture() {
  // The baseline lives OUTSIDE the fixture repository so the repo's worktree
  // stays pristine — the tests below assert on `git status` being empty.
  const home = mkdtempSync(join(tmpdir(), 'engine-freeze-gate-'));
  const dir = join(home, 'repo');
  mkdirSync(dir, { recursive: true });
  const git = (...args) =>
    execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8' }).trim();
  const write = (rel, source) => {
    const full = join(dir, rel);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, source);
    return full;
  };
  git('init', '-q');
  git('config', 'user.email', 'gate@rottay.test');
  git('config', 'user.name', 'gate');
  git('config', 'commit.gpgsign', 'false');
  write(FROZEN_FILE, 'export const Box = () => null;\n');
  write(MODERN_FILE, 'export const Box = () => null;\n');
  git('add', '-A');
  git('commit', '-q', '-m', 'base');
  const base = git('rev-parse', 'HEAD');

  const baselinePath = join(home, 'baseline.json');
  const writeBaseline = (entries, baseRevision = base) =>
    writeFileSync(
      baselinePath,
      `${JSON.stringify({ schemaVersion: 2, baseRevision, entries }, null, 2)}\n`,
    );
  writeBaseline({});

  const run = (...args) =>
    spawnSync(process.execPath, [gate, '--repo', dir, '--baseline', baselinePath, ...args], {
      encoding: 'utf8',
    });

  return {
    dir,
    base,
    git,
    write,
    baselinePath,
    writeBaseline,
    readBaseline: () => JSON.parse(readFileSync(baselinePath, 'utf8')),
    run,
    cleanup: () => rmSync(home, { recursive: true, force: true }),
  };
}

test('a COMMITTED classic edit fails --check even though the worktree is clean', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    f.git('commit', '-q', '-am', 'edit a frozen engine after the freeze');
    assert.equal(f.git('status', '--porcelain'), '', 'precondition: the worktree is clean');

    const result = f.run('--check');
    assert.equal(result.status, 1, result.stdout + result.stderr);
    assert.match(result.stdout, /UNAUTHORIZED frozen-engine change \[M\]/);
    assert.match(result.stdout, new RegExp(FROZEN_FILE.replace(/[/.]/g, '\\$&')));
    assert.match(result.stderr, /FAIL — 1 frozen-engine violation/);
  } finally {
    f.cleanup();
  }
});

test('an edit to a MODERN engine file is never a violation', () => {
  const f = fixture();
  try {
    f.write(MODERN_FILE, 'export const Box = () => "modern work is allowed";\n');
    f.git('commit', '-q', '-am', 'modern work');
    const result = f.run('--check');
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.match(result.stdout, /changed since base: 0/);
  } finally {
    f.cleanup();
  }
});

test('an UNTRACKED frozen file is a violation (a diff against a commit cannot see it)', () => {
  const f = fixture();
  try {
    f.write(OTHER_FROZEN_FILE, 'export const Flex = () => null;\n');
    const result = f.run('--check');
    assert.equal(result.status, 1, result.stdout + result.stderr);
    assert.match(result.stdout, /UNAUTHORIZED frozen-engine change \[A\][\s\S]*\(untracked\)/);
  } finally {
    f.cleanup();
  }
});

test('--authorize records a content pin, and the SAME file drifting later fails again', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "compile fix";\n');
    f.git('commit', '-q', '-am', 'shared-contract compile fix');
    assert.equal(f.run('--check').status, 1);

    const authorized = f.run(
      '--authorize',
      FROZEN_FILE,
      '--reason',
      'minimal shared-contract compile fix; the prop type moved in the DS contract',
    );
    assert.equal(authorized.status, 0, authorized.stdout + authorized.stderr);
    const baseline = f.readBaseline();
    assert.equal(
      baseline.entries[FROZEN_FILE].blob,
      sha256('export const Box = () => "compile fix";\n'),
    );
    assert.match(baseline.entries[FROZEN_FILE].reason, /compile fix/);
    assert.equal(f.run('--check').status, 0);

    // The exception covered ONE reviewed byte-state. A further edit is not covered.
    f.write(FROZEN_FILE, 'export const Box = () => "smuggled engine work";\n');
    const drifted = f.run('--check');
    assert.equal(drifted.status, 1, drifted.stdout);
    assert.match(drifted.stdout, /DRIFTED beyond its written exception/);
  } finally {
    f.cleanup();
  }
});

test('--authorize refuses a path that has not changed (no pre-authorizing a future edit)', () => {
  const f = fixture();
  try {
    const result = f.run('--authorize', FROZEN_FILE, '--reason', 'pre-authorize the next edit');
    assert.equal(result.status, 1);
    assert.match(result.stderr, /cannot be authorized before it changes/);
  } finally {
    f.cleanup();
  }
});

test('--authorize refuses a bare path with no written reason', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    const result = f.run('--authorize', FROZEN_FILE, '--reason', 'oops');
    assert.equal(result.status, 1);
    assert.match(result.stderr, /requires --reason/);
  } finally {
    f.cleanup();
  }
});

test('--authorize refuses a GENERATED file: an artifact never authorizes its source', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, '/* @generated — regenerate with build:vertical-css */\nexport const Box = () => null;\n');
    const result = f.run(
      '--authorize',
      FROZEN_FILE,
      '--reason',
      'the build regenerated this artifact under a frozen engine',
    );
    assert.equal(result.status, 1);
    assert.match(result.stderr, /never authorization to modify the source/);
    assert.deepEqual(f.readBaseline().entries, {});
  } finally {
    f.cleanup();
  }
});

test('--write is removed: the bulk snapshot that let a change grandfather itself is gone', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    const result = f.run('--write');
    assert.equal(result.status, 1);
    assert.match(result.stderr, /--write is removed/);
    assert.deepEqual(f.readBaseline().entries, {}, 'the baseline must not have been rewritten');
  } finally {
    f.cleanup();
  }
});

test('a baseRevision pointed ahead of history is rejected, so history cannot be erased', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    f.git('commit', '-q', '-am', 'frozen edit');
    const head = f.git('rev-parse', 'HEAD');
    // Re-pointing the base at the commit that made the change hides it entirely.
    // That is legal ONLY because this is fixture mode; production runs must match
    // the source-pinned SEALED_BASE, which this asserts is enforced elsewhere.
    f.writeBaseline({}, head);
    assert.equal(f.run('--check').status, 0, 'fixture mode allows any ancestor base');

    f.writeBaseline({}, '0123456789abcdef0123456789abcdef01234567');
    const missing = f.run('--check');
    assert.equal(missing.status, 1);
    assert.match(missing.stderr, /is not a commit/);
  } finally {
    f.cleanup();
  }
});

test('ENGINE_FREEZE_BASE may widen the window but never narrow it', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    f.git('commit', '-q', '-am', 'frozen edit');
    const head = f.git('rev-parse', 'HEAD');
    const narrowed = spawnSync(
      process.execPath,
      [gate, '--repo', f.dir, '--baseline', f.baselinePath, '--check'],
      { encoding: 'utf8', env: { ...process.env, ENGINE_FREEZE_BASE: head } },
    );
    assert.equal(narrowed.status, 1);
    assert.match(narrowed.stderr, /may only WIDEN the audit window/);
  } finally {
    f.cleanup();
  }
});

/* ------------------------------------------------------------------------ */
/* negative drill: an import-only exception never covers a functional edit   */
/* ------------------------------------------------------------------------ */

/**
 * Relocating a shared engine module into a `folder/index` unit rewrites one
 * import line in every frozen delegation stub that consumes it, which is how
 * ten Classic/Rustic stubs came to be re-authorized on 2026-07-26 with an
 * "only the module path moved" reason. The hazard that creates is a hole: if
 * an import-only exception quietly covered whatever the file becomes NEXT, a
 * real Classic/Rustic edit could ride in behind a relocation. These drills
 * prove it cannot — the content pin re-fails on the following edit even when
 * that edit changes no import whatsoever.
 */
const stub = (from, extraProp = '') =>
  [
    "'use client';",
    "import React from 'react';",
    `import { BoxEngine } from '${from}';`,
    'export default function ClassicBox(props) {',
    `  return <BoxEngine {...props}${extraProp} />;`,
    '}',
    '',
  ].join('\n');

/** Lines present in one revision and not the other, in both directions. */
function changedLines(before, after) {
  const a = before.split('\n');
  const b = after.split('\n');
  return [...a.filter((l) => !b.includes(l)), ...b.filter((l) => !a.includes(l))].filter((l) =>
    l.trim(),
  );
}

const isImportLine = (line) => /^\s*(import|export)\b.*\bfrom\b/.test(line);

test('negative drill: an import-only exception does NOT cover a later FUNCTIONAL edit', () => {
  const f = fixture();
  try {
    // The base commit holds the pre-relocation stub.
    f.write(FROZEN_FILE, stub('../shared'));
    f.git('commit', '-q', '-am', 'stub before the relocation');
    // Re-seal the fixture window on that state so only the relocation is in view.
    f.writeBaseline({}, f.git('rev-parse', 'HEAD'));

    // 1. The relocation: exactly one changed line, and it is an import.
    const relocated = stub('../foundation');
    const relocationDelta = changedLines(stub('../shared'), relocated);
    assert.equal(relocationDelta.length, 2, 'the relocation is one line replaced');
    assert.ok(
      relocationDelta.every(isImportLine),
      `the relocation must touch imports only, got: ${relocationDelta.join(' | ')}`,
    );
    f.write(FROZEN_FILE, relocated);
    assert.equal(f.run('--check').status, 1, 'precondition: the relocation itself is a violation');

    const authorized = f.run(
      '--authorize',
      FROZEN_FILE,
      '--reason',
      'structural relocation only: the shared engine module moved to folder/index; one import line, zero functional lines',
    );
    assert.equal(authorized.status, 0, authorized.stdout + authorized.stderr);
    assert.equal(f.run('--check').status, 0, 'the reviewed import-only byte-state is green');

    // 2. The smuggled functional edit: a render change that touches NO import.
    const functional = stub('../foundation', ' className="smuggled-classic-restyle"');
    const functionalDelta = changedLines(relocated, functional);
    assert.ok(functionalDelta.length > 0);
    assert.ok(
      functionalDelta.every((line) => !isImportLine(line)),
      `the drill must change no import, got: ${functionalDelta.join(' | ')}`,
    );
    f.write(FROZEN_FILE, functional);

    const red = f.run('--check');
    assert.equal(red.status, 1, `the gate must redden on a functional edit\n${red.stdout}`);
    assert.match(red.stdout, /DRIFTED beyond its written exception/);
    assert.match(red.stderr, /FAIL — 1 frozen-engine violation/);
  } finally {
    f.cleanup();
  }
});

test('negative drill: re-authorizing one stub does not bless a SECOND frozen file', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, stub('../shared'));
    f.git('commit', '-q', '-am', 'stub before the relocation');
    f.writeBaseline({}, f.git('rev-parse', 'HEAD'));

    f.write(FROZEN_FILE, stub('../foundation'));
    assert.equal(
      f.run('--authorize', FROZEN_FILE, '--reason', 'structural relocation only, one import line')
        .status,
      0,
    );
    assert.equal(f.run('--check').status, 0);

    // A sibling frozen file taking the SAME relocation is still unauthorized:
    // the exception is per-path, never a glob over the relocation.
    f.write(OTHER_FROZEN_FILE, stub('../foundation'));
    const red = f.run('--check');
    assert.equal(red.status, 1, red.stdout);
    assert.match(red.stdout, /UNAUTHORIZED frozen-engine change/);
  } finally {
    f.cleanup();
  }
});

test('coverage boundary: the shared module a frozen stub delegates to is NOT frozen', () => {
  // Recorded deliberately. `engines/foundation/index.tsx` (like the
  // `engines/shared.tsx` it replaced) sits outside the freeze regex, so a
  // functional edit there changes what Classic and Rustic render without this
  // gate seeing it. Anyone reasoning about "Classic is frozen" must read the
  // delegated module too — the pin covers the stub's bytes, not its behavior.
  assert.ok(FROZEN.test('packages/core/src/ui/patterns/data/widget-board/engines/classic/index.tsx'));
  assert.ok(!FROZEN.test('packages/core/src/ui/patterns/data/widget-board/engines/foundation/index.tsx'));
  assert.ok(!FROZEN.test('packages/core/src/ui/patterns/data/widget-board/engines/shared.tsx'));
});

test('the real baseline is schema v2, pinned to the sealed base, and every entry carries a reason', () => {
  const baseline = JSON.parse(
    readFileSync(join(scriptDir, 'engine-freeze-gate.baseline.json'), 'utf8'),
  );
  assert.equal(baseline.schemaVersion, 2);
  assert.match(baseline.baseRevision, /^[0-9a-f]{40}$/);
  const entries = Object.entries(baseline.entries);
  assert.ok(entries.length > 0);
  for (const [path, entry] of entries) {
    assert.ok(FROZEN.test(path), `${path} is not a frozen path`);
    assert.match(entry.blob, /^[0-9a-f]{64}$/, `${path} has no content pin`);
    assert.ok(entry.reason.length >= 12, `${path} has no written reason`);
  }
});
