// styles/*.css staleness gate (GAT-02).
//
// The six committed bundles under packages/core/styles/ are the source-of-truth
// mirrors of the shipped dist CSS (the npm `files` list ships the byte-identical
// dist/ copies only), but nothing in CI verified they matched their build
// inputs. Worse, the
// CI `build` step runs `build:vertical-css`, which regenerates them in place --
// so by the time any later step ran, a stale committed bundle had already been
// silently overwritten and no downstream check could see the drift. This gate
// closes that hole: it recomposes the bundles IN MEMORY and diffs against the
// committed files, and it is sequenced BEFORE the build step in ci.yml.
//
// The dist/modern-engine.css input problem: build-vertical-css.mjs --check reads
// dist/modern-engine.css, a build product, so it cannot run before a build. This
// gate instead compiles the modern engine from source in memory (postcss +
// @tailwindcss/postcss on compiled.css, the exact `build:modern-css` inputs),
// with no prior build.
//
// The composition below mirrors build-vertical-css.mjs. The five tenant/index
// bundles (base + modernEngine + tenant) are byte-pinned. styles/modern.css is
// pinned only to START WITH the freshly compiled engine: its post-engine tail is
// composition-in-flux and its text is already byte-covered inside the tenant
// bundles (see the note by that assertion). Any divergence surfaces here as a
// failing diff rather than as silent drift.
//
// Run: node --test scripts/vertical-css-staleness.gate.mjs
// (Named .gate.mjs, not .test.mjs, so it stays out of the `test:scripts` glob
// and runs only at its own dedicated, clearly-attributed CI step before Build.)

import { test } from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { wrapModernFrameworkLayer } from "./lib/modern-framework-layer.mjs";

const require = createRequire(import.meta.url);
const postcss = require("postcss");
const tailwind = require("@tailwindcss/postcss");

const HERE = dirname(fileURLToPath(import.meta.url));
const root = resolve(HERE, "..");
const srcCss = resolve(root, "src/foundation/tokens/css");
const styles = resolve(root, "styles");

// --- helpers copied verbatim from build-vertical-css.mjs -------------------

function unwrapRegisteredCustomProperties(css) {
  return css.replace(
    /@layer base \{\n  @property --radialprogress \{\n    syntax: "<percentage>";\n    inherits: true;\n    initial-value: 0%;\n  \}\n\}\n/g,
    '@property --radialprogress {\n  syntax: "<percentage>";\n  inherits: true;\n  initial-value: 0%;\n}\n'
  );
}

function readFile(path) {
  if (!existsSync(path)) throw new Error(`Missing file: ${path}`);
  return readFileSync(path, "utf-8");
}

function resolveImports(css, baseDir) {
  return css.replace(
    /@import\s+['"](\.[^'"]+)['"]\s*(layer\([^)]+\))?\s*;/g,
    (match, importPath, layerDirective) => {
      const fullPath = resolve(baseDir, importPath);
      if (!existsSync(fullPath)) return `/* unresolved: ${match} */`;
      let content = readFileSync(fullPath, "utf-8");
      content = resolveImports(content, dirname(fullPath));
      if (layerDirective) {
        const layerName = layerDirective.replace("layer(", "").replace(")", "");
        return `@layer ${layerName} {\n${content}\n}`;
      }
      return content;
    }
  );
}

const verticals = [
  { name: "platform", tenantFile: "facade/artifacts/rottay/index.css" },
  { name: "bithire", tenantFile: "facade/artifacts/bithire/index.css" },
  { name: "evnto", tenantFile: "facade/artifacts/evnto/index.css" },
];

function composeVerticalBundle(name, baseCss, modernEngine, tenantCss) {
  return [
    `/* @rottay/design-system - ${name} vertical bundle */`,
    `/* Generated by build-vertical-css.mjs */`,
    `/* Structure: base tokens + modern engine + ${name} tenant (unlayered, wins by specificity) */`,
    "",
    baseCss,
    "",
    `/* === Modern Engine (DaisyUI + Tailwind utilities) === */`,
    modernEngine,
    "",
    `/* === ${name} tenant overrides (unlayered, wins by specificity + source order) === */`,
    tenantCss,
  ].join("\n");
}

function composeStylesBundle(baseCss, modernEngine, allTenantsCss) {
  return [
    `/* @rottay/design-system - full CSS bundle (all tenants) */`,
    `/* Generated by build-vertical-css.mjs */`,
    `/* Structure: base tokens + modern engine + all tenants (unlayered, wins by specificity) */`,
    `/* Production apps should use styles/platform, styles/bithire, or styles/evnto instead. */`,
    "",
    baseCss,
    "",
    `/* === Modern Engine (DaisyUI + Tailwind utilities) === */`,
    modernEngine,
    "",
    `/* === All tenant overrides (unlayered, wins by specificity + source order) === */`,
    allTenantsCss,
  ].join("\n");
}

// --- compose every bundle in memory ----------------------------------------

// Compile the modern engine from source, exactly as `build:modern-css` does
// (`postcss src/.../modern/compiled.css`), then apply the same unwrap step
// build-vertical-css.mjs applies to dist/modern-engine.css. No prior build.
const compiledPath = resolve(srcCss, "runtime/engines/modern/compiled.css");
const modernEnginePromise = postcss([tailwind()])
  .process(readFile(compiledPath), { from: compiledPath })
  .then((r) =>
    wrapModernFrameworkLayer(unwrapRegisteredCustomProperties(r.css))
  );

const modernEngine = await modernEnginePromise;

const baseCss = resolveImports(
  readFile(resolve(srcCss, "facade/entrypoints/base.css")),
  resolve(srcCss, "facade/entrypoints")
);

// Per-vertical bundles use import-resolved tenant CSS.
const expected = new Map();
for (const { name, tenantFile } of verticals) {
  const tenantPath = resolve(srcCss, tenantFile);
  const tenantCss = resolveImports(readFile(tenantPath), dirname(tenantPath));
  const bundle = composeVerticalBundle(name, baseCss, modernEngine, tenantCss);
  expected.set(`styles/${name}.css`, bundle);
  if (name === "platform") expected.set("styles/rottay.css", bundle);
}

// The all-tenants bundle joins the RAW artifact files (no import resolution),
// matching build-vertical-css.mjs.
const allTenantsCss = verticals
  .map((v) => readFile(resolve(srcCss, v.tenantFile)))
  .join("\n");
expected.set(
  "styles/index.css",
  composeStylesBundle(baseCss, modernEngine, allTenantsCss)
);

// styles/modern.css is checked separately (below). The five tenant/index
// bundles compose base + modernEngine + tenant with a formula that is stable in
// build-vertical-css.mjs, so they are byte-pinned. styles/modern.css is the
// standalone engine bundle whose post-engine TAIL is composition-in-flux (a
// reduced-motion guard is being appended to it); that tail is sourced from
// runtime/personality.css, which base.css already inlines into every tenant
// bundle above, so the tail text is byte-covered there. Here we pin only that
// the standalone bundle STARTS WITH the freshly compiled engine — the drift
// class GAT-02 targets (a stale committed engine that Build would silently
// regenerate).

// --- assertions: every committed bundle matches its recomposition ----------

function firstDiffLine(committed, generated) {
  const a = committed.split("\n");
  const b = generated.split("\n");
  const max = Math.max(a.length, b.length);
  for (let i = 0; i < max; i += 1) {
    if (a[i] !== b[i]) {
      return `line ${i + 1}\n  committed: ${JSON.stringify(
        (a[i] ?? "").slice(0, 200)
      )}\n  generated: ${JSON.stringify((b[i] ?? "").slice(0, 200))}`;
    }
  }
  return "(files differ only in trailing length)";
}

// --- spring-precompute tail (TASK S) ---------------------------------------
//
// build-vertical-css.mjs appends a tenant-scoped `--ds-motion-spring: linear()`
// override derived from each BrandTheme's tension/friction (useSpring-gated).
// That derivation imports compiled theme modules from dist/, which this
// pre-build gate cannot execute. The prefix of every bundle stays byte-pinned
// here; the tail may only be the strict spring grammar below, scoped to the
// bundle's OWN tenant root. The tail's exact bytes are pinned post-build by
// `build-vertical-css.mjs --check` (chained into pretest and lint), so a
// hand-edited spring value still fails CI — just one step later.

const SPRING_LINEAR_SOURCE = String.raw`linear\((?:-?\d+(?:\.\d+)?, )*1\)`;

function springBlockSource(name, slug) {
  return (
    String.raw`/\* === ${name} spring easing \(precomputed linear\(\) from the BrandTheme, useSpring\) === \*/\n`.replace(
      /\//g,
      "\\/"
    ) +
    String.raw`:is\(html\[data-tenant='${slug}'\], :where\(\[data-ds-root\]\[data-vertical='${name}'\]\)\) \{\n` +
    String.raw`  --ds-motion-spring: ${SPRING_LINEAR_SOURCE};\n\}`
  );
}

const SPRING_TENANTS = [
  { name: "platform", slug: "rottay" },
  { name: "bithire", slug: "bithire" },
  { name: "evnto", slug: "evnto" },
];

/** Allowed tail after the byte-pinned prefix, per committed bundle. */
function springTailRe(rel) {
  if (rel === "styles/index.css") {
    const anyBlock = SPRING_TENANTS.map(({ name, slug }) =>
      springBlockSource(name, slug)
    ).join("|");
    return new RegExp(
      String.raw`^\n\n/\* === Precomputed spring easings \(per-tenant, useSpring\) === \*/\n(?:${anyBlock})(?:\n\n(?:${anyBlock}))*$`.replace(
        "/\\*",
        "\\/\\*"
      )
    );
  }
  const tenant = SPRING_TENANTS.find(
    ({ name, slug }) =>
      rel === `styles/${name}.css` ||
      (name === "platform" && rel === "styles/rottay.css")
  );
  if (!tenant) return null;
  return new RegExp(`^\\n\\n${springBlockSource(tenant.name, tenant.slug)}$`);
}

for (const [rel, content] of expected) {
  test(`${rel} is in sync with its build inputs`, () => {
    const path = resolve(root, rel);
    const committed = existsSync(path) ? readFileSync(path, "utf-8") : "";
    if (committed !== content && committed.startsWith(content)) {
      const tail = committed.slice(content.length);
      const tailRe = springTailRe(rel);
      assert.ok(
        tailRe !== null && tailRe.test(tail),
        `${rel} carries a tail beyond its recomposed prefix that is not the sanctioned spring-precompute block (regenerate with: pnpm -C packages/core build:vertical-css). tail: ${JSON.stringify(
          tail.slice(0, 300)
        )}`
      );
      return;
    }
    assert.equal(
      committed,
      content,
      `${rel} is stale or hand-edited (regenerate with: pnpm -C packages/core build:vertical-css).\n${firstDiffLine(
        committed,
        content
      )}`
    );
  });
}

test("styles/modern.css embeds the freshly compiled modern engine", () => {
  const path = resolve(root, "styles/modern.css");
  const committed = existsSync(path) ? readFileSync(path, "utf-8") : "";
  assert.ok(
    committed.startsWith(modernEngine),
    `styles/modern.css does not begin with the current source-compiled modern engine — it is stale (regenerate with: pnpm -C packages/core build:vertical-css). committed length ${committed.length}, engine length ${modernEngine.length}.`
  );
});
