/**
 * @fileoverview Type definitions for the FilterBuilder pattern component.
 * Models a composable filter tree inspired by Airtable's filter UI:
 *
 * - **FilterRule** -- leaf node representing a single field/operator/value condition.
 * - **FilterGroup** -- branch node that combines child rules and/or nested groups
 *   with AND/OR logic.
 * - **FilterFieldDefinition** -- schema for each filterable field (type, allowed
 *   operators, select options).
 * - **FilterBuilderProps** -- top-level component props controlling the tree value,
 *   nesting depth, and UI labels.
 *
 */

import type { ReactNode } from 'react';
import type { PatternBaseProps } from '../../../../../foundation/contracts/runtime/components/patterns/core';

// ---------------------------------------------------------------------------
// Custom Operator Extensibility
// ---------------------------------------------------------------------------

/**
 * Definition for a custom operator registered by the consuming app.
 *
 * Custom operators extend the built-in set (equals, contains, between, etc.)
 * with domain-specific comparisons such as `isOverdue`, `matchesRegex`, or
 * `withinRadius`. They are merged into the operator dropdown at runtime for
 * each field type listed in `fieldTypes`.
 *
 * @example
 * ```ts
 * const customOps: CustomOperatorDefinition[] = [
 *   {
 *     key: 'matchesRegex',
 *     label: 'matches regex',
 *     fieldTypes: ['text'],
 *     valueCount: 1,
 *   },
 *   {
 *     key: 'isOverdue',
 *     label: 'is overdue',
 *     fieldTypes: ['date'],
 *     valueCount: 0,
 *   },
 *   {
 *     key: 'withinRadius',
 *     label: 'within radius',
 *     fieldTypes: ['number'],
 *     valueCount: 2,
 *     renderValue: (value, onChange) => {
 *       // custom two-input renderer for lat/lng + radius
 *     },
 *   },
 * ];
 * ```
 */
export interface CustomOperatorDefinition {
  /** Unique key identifying this operator. Must not collide with built-in keys. */
  key: string;

  /** Human-readable label shown in the operator dropdown. */
  label: string;

  /** Which field types this operator applies to. */
  fieldTypes: FilterFieldType[];

  /**
   * Number of value inputs required:
   * - `0` for unary operators like `isEmpty` or `isOverdue` (no value input).
   * - `1` for standard binary operators like `equals` or `matchesRegex`.
   * - `2` for range operators like `between` or `withinRadius`.
   */
  valueCount: 0 | 1 | 2;

  /**
   * Custom value renderer for complex inputs. When provided, replaces the
   * default type-based input widget for this operator.
   *
   * @param value - Current filter value.
   * @param onChange - Callback to update the value.
   * @param field - The field definition this operator is applied to.
   * @returns A React element rendering the value input.
   */
  renderValue?: (
    value: unknown,
    onChange: (v: unknown) => void,
    field: FilterFieldDefinition
  ) => ReactNode;

  /** Optional hint for server-side query builders describing evaluation strategy. */
  evaluationHint?: string;
}

/**
 * Built-in filter operators known at compile time. Used to narrow types in
 * the default operator registry and to provide autocomplete in IDEs.
 */
export type BuiltInFilterOperator =
  | 'equals'
  | 'notEquals'
  | 'contains'
  | 'notContains'
  | 'startsWith'
  | 'endsWith'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'between'
  | 'in'
  | 'notIn'
  | 'isEmpty'
  | 'isNotEmpty';

/**
 * Union of all comparison operators available for filter rules.
 *
 * Includes the built-in set plus an `(string & {})` escape hatch that allows
 * custom operator keys registered via `CustomOperatorDefinition` without
 * losing autocomplete for built-in operators.
 */
export type FilterOperator = BuiltInFilterOperator | (string & {});

/**
 * A single filter condition (leaf node in the filter tree).
 *
 * Each rule targets one field, applies one operator, and holds the comparison
 * value. Rules are always contained within a `FilterGroup`.
 */
export interface FilterRule {
  /** Unique identifier for this rule, generated by `generateFilterId()`. */
  id: string;

  /** Key of the field being filtered, matching `FilterFieldDefinition.key`. */
  field: string;

  /** Comparison operator to apply. */
  operator: FilterOperator;

  /**
   * The comparison value. Type depends on the field type and operator:
   * - `string` for text operators
   * - `number` for numeric operators
   * - `[min, max]` tuple for `between`
   * - `string[]` for `in` / `notIn`
   * - `undefined` for `isEmpty` / `isNotEmpty` (value is ignored)
   *
   * Typed as `any` because the concrete type varies by field; runtime
   * validation happens in the component.
   */
  value: any;
}

/**
 * A logical grouping of filter rules and/or nested groups (branch node).
 *
 * Groups combine their children with either AND or OR logic. Nesting groups
 * inside groups allows arbitrarily complex filter expressions, bounded by
 * `FilterBuilderProps.maxDepth`.
 */
export interface FilterGroup {
  /** Unique identifier for this group, generated by `generateFilterId()`. */
  id: string;

  /** Logical combinator applied between all children of this group. */
  logic: 'and' | 'or';

  /**
   * Child nodes -- a mix of individual rules and nested groups.
   * Use `isFilterGroup` / `isFilterRule` type guards to discriminate.
   */
  rules: (FilterRule | FilterGroup)[];
}

/**
 * Supported field types for the filter builder. The field type determines
 * which operators are available by default (via `DEFAULT_OPERATORS_BY_TYPE`)
 * and which value input widget the component renders.
 *
 * - `"text"` -- free-form string input
 * - `"number"` -- numeric input with min/max support
 * - `"date"` -- date picker
 * - `"select"` -- single-value dropdown (requires `options`)
 * - `"multiSelect"` -- multi-value dropdown (requires `options`)
 * - `"boolean"` -- true/false toggle
 */
export type FilterFieldType =
  | 'text'
  | 'number'
  | 'date'
  | 'select'
  | 'multiSelect'
  | 'boolean';

/**
 * Schema for a single filterable field. Each definition tells the
 * FilterBuilder what kind of input to render, which operators to offer,
 * and how to label the field in the UI.
 */
export interface FilterFieldDefinition {
  /** Unique key matching the data property this field filters on. */
  key: string;

  /** Human-readable label shown in the field selector dropdown. */
  label: string;

  /**
   * Field type that determines the default set of available operators and
   * the value input widget (text input, number input, date picker, etc.).
   */
  type: FilterFieldType;

  /**
   * Explicit list of operators allowed for this field. When provided, this
   * overrides the defaults from `DEFAULT_OPERATORS_BY_TYPE[type]`. Useful
   * for restricting operators on specific fields (e.g. disallowing
   * `contains` on an ID field). Custom operator keys are also valid here.
   */
  operators?: FilterOperator[];

  /**
   * Dropdown options for `"select"` and `"multiSelect"` field types.
   * Ignored for other field types.
   */
  options?: { label: string; value: any }[];

  /** Custom icon rendered beside the field name in the field selector. */
  icon?: ReactNode;

  /** Placeholder text for the value input. */
  placeholder?: string;
}

/**
 * Metadata for a single operator, used to render operator dropdowns and
 * to determine whether a value input should be shown.
 */
export interface OperatorDefinition {
  /** The operator key matching a `FilterOperator` value. */
  key: FilterOperator;

  /** Human-readable label shown in the operator dropdown (e.g. "contains"). */
  label: string;

  /**
   * Whether this operator requires a value input. Operators like `isEmpty`
   * and `isNotEmpty` do not require a value.
   */
  requiresValue: boolean;

  /**
   * Whether this operator requires two values (min and max). Only `true`
   * for the `"between"` operator, which renders a range input.
   */
  requiresRange: boolean;
}

/**
 * Props for the FilterBuilder pattern component.
 *
 * FilterBuilder provides a visual query builder for constructing complex
 * filter expressions. The user adds rules and groups, selects fields and
 * operators, and enters comparison values. The resulting `FilterGroup` tree
 * is emitted via `onChange` for the parent to apply to data queries.
 *
 * @example
 * ```tsx
 * <PatternFilterBuilder
 *   fields={[
 *     { key: 'name', label: 'Name', type: 'text' },
 *     { key: 'status', label: 'Status', type: 'select', options: statusOptions },
 *     { key: 'amount', label: 'Amount', type: 'number' },
 *     { key: 'createdAt', label: 'Created', type: 'date' },
 *   ]}
 *   value={filterGroup}
 *   onChange={setFilterGroup}
 *   maxDepth={2}
 *   showClear
 *   onClear={() => setFilterGroup(emptyGroup)}
 * />
 * ```
 */
export interface FilterBuilderProps extends PatternBaseProps {
  /** Array of field definitions describing what can be filtered and how. */
  fields: FilterFieldDefinition[];

  /**
   * The current filter tree value (controlled). Always a `FilterGroup` at the
   * root level, containing rules and/or nested groups.
   */
  value: FilterGroup;

  /**
   * Called whenever the filter tree changes (rule added/removed, operator
   * changed, value updated, group logic toggled, etc.).
   *
   * @param value - The updated root `FilterGroup`.
   */
  onChange: (value: FilterGroup) => void;

  /**
   * Maximum allowed nesting depth for filter groups. Prevents users from
   * creating excessively complex filter trees.
   * @default 3
   */
  maxDepth?: number;

  /**
   * Whether to allow creating nested groups (AND/OR sub-groups). When false,
   * only flat rule lists within the root group are allowed.
   * @default true
   */
  allowGrouping?: boolean;

  /** Label text for the "Add rule" button. @default "Add rule" */
  addRuleLabel?: string;

  /** Label text for the "Add group" button. @default "Add group" */
  addGroupLabel?: string;

  /**
   * Whether to show a "Clear all" button that resets the entire filter tree.
   * @default false
   */
  showClear?: boolean;

  /** Label text for the clear button. @default "Clear all" */
  clearLabel?: string;

  /**
   * Called when the clear button is clicked. The parent should reset the
   * `value` to an empty `FilterGroup`.
   */
  onClear?: () => void;

  /**
   * Compact mode reduces padding, font sizes, and spacing for denser UIs
   * like sidebars and narrow panels.
   * @default false
   */
  compact?: boolean;

  // ---------------------------------------------------------------------------
  // Custom Operator Extensibility (Wave 3)
  // ---------------------------------------------------------------------------

  /**
   * Custom operators registered by the consuming app. These are merged into
   * the operator dropdown at runtime for each field type listed in the
   * definition's `fieldTypes` array. Custom operators can provide their own
   * value renderer via `renderValue`.
   *
   * @example
   * ```tsx
   * <PatternFilterBuilder
   *   customOperators={[
   *     { key: 'matchesRegex', label: 'matches regex', fieldTypes: ['text'], valueCount: 1 },
   *     { key: 'isOverdue', label: 'is overdue', fieldTypes: ['date'], valueCount: 0 },
   *   ]}
   *   // ...other props
   * />
   * ```
   */
  customOperators?: CustomOperatorDefinition[];

  // ---------------------------------------------------------------------------
  // "Add Filter" Field Selector (Wave 3)
  // ---------------------------------------------------------------------------

  /**
   * When `true`, shows an "Add Filter" button that opens a field selector
   * dropdown. Selecting a field adds a new empty rule for that field to the
   * root filter group. This provides progressive disclosure instead of
   * requiring users to manually change the field on a new rule.
   * @default false
   */
  showAddFilter?: boolean;

  /**
   * Label for the "Add Filter" button shown when `showAddFilter` is `true`.
   * @default "Add filter"
   */
  addFilterLabel?: string;
}
