import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

// TASK S item 2: build:vertical-css precomputes a first-party --ds-motion-spring
// linear() from each theme's own tension/friction, honoring useSpring. This
// pins the generated bundle output (regenerated by build:vertical-css and
// gate-checked by vertical-css-staleness). The spring token is a timing
// function, not a duration, so it adds no motion of its own -- the reduced-motion
// guard zeroes the paired --ds-motion durations, making any spring-eased
// transition collapse to its final state.

const HERE = dirname(fileURLToPath(import.meta.url));
const STYLES = resolve(HERE, '../../../../styles');
const read = (name: string) => readFileSync(resolve(STYLES, name), 'utf8');

const TENANT_SPRING = /:is\(html\[data-tenant='(rottay|evnto)'\][^{]*\{\s*--ds-motion-spring:\s*(linear\([^;]*\));/g;

function springOverride(css: string): string | null {
  TENANT_SPRING.lastIndex = 0;
  const match = TENANT_SPRING.exec(css);
  return match ? match[2] : null;
}

describe('first-party spring precompute (useSpring-gated)', () => {
  it('platform (rottay, useSpring: true) ships a precomputed linear() --ds-motion-spring', () => {
    const spring = springOverride(read('platform.css'));
    expect(spring, 'expected a tenant-scoped linear() spring override').not.toBeNull();
    expect(spring).toMatch(/^linear\(0,/);
  });

  it('evnto (useSpring: true) ships its own distinct linear() curve', () => {
    const evnto = springOverride(read('evnto.css'));
    const platform = springOverride(read('platform.css'));
    expect(evnto).not.toBeNull();
    // evnto tunes a bouncier spring (tension 200 / friction 18) than platform
    // (170 / 26), so the curves differ.
    expect(evnto).not.toBe(platform);
  });

  it('bithire (useSpring: false) ships NO precomputed override -- keeps the foundation cubic-bezier', () => {
    const css = read('bithire.css');
    expect(css).not.toMatch(/--ds-motion-spring:\s*linear\(/);
    // The foundation default is still present (unoverridden).
    expect(css).toContain('--ds-motion-spring: cubic-bezier(0.34, 1.56, 0.64, 1);');
  });

  it('the primary spring override is scoped to the tenant root, never bare :root', () => {
    for (const name of ['platform.css', 'evnto.css']) {
      const css = read(name);
      // Every linear() --ds-motion-spring must sit inside a tenant :is(...) block,
      // never leak onto a bare :root that would cross tenant boundaries.
      const bareRootSpring = /:root\s*\{[^}]*--ds-motion-spring:\s*linear\(/;
      expect(bareRootSpring.test(css), name).toBe(false);
    }
  });
});
