/**
 * @generated by `packages/core/scripts/generate/theme/schema/index.mjs --write`.
 * Do not edit: the domains are the typed catalog's, and `--check` fails on drift.
 *
 * The DB-side value schema for a v2 decision document. The document contract
 * closes the KEY sets; this module closes the VALUES of every domain the
 * catalog states in full. `registered` domains stay with their registry and
 * `record` domains with their family contract, so neither is restated here.
 *
 * @module Compilers/Kernel/Foundation/Schemas/TenantTheme/Decisions
 * @category Compilers
 * @package @rottay/design-system
 */

import type { ThemeDecisionId } from "@/contracts/theme/foundation/decisions";

export type ThemeDecisionDomain =
  | { readonly kind: "enum"; readonly values: readonly string[] }
  | { readonly kind: "scale"; readonly min: number; readonly max: number }
  | { readonly kind: "color-set"; readonly roles: readonly string[] };

export const THEME_DECISION_DOMAIN_SCHEMA: Readonly<
  Partial<Record<ThemeDecisionId, ThemeDecisionDomain>>
> = Object.freeze({
  "palette.seeds": { kind: "color-set", roles: ["primary", "secondary", "accent", "background"] },
  "palette.status-seeds": { kind: "color-set", roles: ["success", "warning", "error", "info"] },
  "palette.neutral-temperature": { kind: "enum", values: ["cool", "neutral", "warm"] },
  "palette.contrast-posture": { kind: "enum", values: ["soft", "standard", "high"] },
  "palette.dark-mode": { kind: "enum", values: ["light", "dark", "auto"] },
  "typography.pairing": { kind: "enum", values: ["sober", "editorial", "geometric", "technical"] },
  "typography.scale": { kind: "scale", min: 0.9, max: 1.1 },
  "typography.role-weights": { kind: "enum", values: ["light", "regular", "strong"] },
  "typography.numeric": { kind: "enum", values: ["proportional", "tabular"] },
  "shape.radius-scale": { kind: "scale", min: 0.75, max: 1.25 },
  "shape.nesting": { kind: "enum", values: ["concentric", "uniform"] },
  "shape.button-style": { kind: "enum", values: ["sharp", "soft", "pill"] },
  "shape.control-height": { kind: "enum", values: ["compact", "standard", "tall"] },
  "density.mode": { kind: "enum", values: ["compact", "normal", "spacious"] },
  "spacing.rhythm": { kind: "enum", values: ["tight", "normal", "airy"] },
  "surfaces.elevation-posture": { kind: "enum", values: ["flat", "soft", "elevated"] },
  "surfaces.border-style": { kind: "enum", values: ["none", "hairline", "strong"] },
  "surfaces.effect-intensity": { kind: "scale", min: 0, max: 1 },
  "states.emphasis": { kind: "enum", values: ["subtle", "medium", "strong"] },
  "states.focus-style": { kind: "enum", values: ["ring", "underline", "glow"] },
  "motion.character": { kind: "enum", values: ["mechanical", "organic", "playful"] },
  "navigation.sidebar-tone": { kind: "enum", values: ["subtle", "strong", "inverse"] },
  "responsive.posture": { kind: "enum", values: ["compact", "balanced", "expansive"] },
});

/** Refusals name the decision, the value and the domain it left. */
export class ThemeDecisionDomainError extends Error {
  constructor(message: string) {
    super(`TenantThemeDocument v2: ${message}`);
    this.name = "ThemeDecisionDomainError";
  }
}

const HEX = /^#(?:[0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/iu;

/**
 * Closes the VALUES of a validated v2 decision map, fail-closed and by name.
 *
 * Called by the v2 admission, after the document contract has closed the key
 * sets. A value outside its domain is refused rather than clamped: clamping is
 * an envelope decision and belongs to admission, not to a schema.
 */
export function assertThemeDecisionDomains(
  decisions: Readonly<Record<string, unknown>>
): void {
  for (const [id, value] of Object.entries(decisions)) {
    if (value === undefined) continue;
    const domain = THEME_DECISION_DOMAIN_SCHEMA[id as ThemeDecisionId];
    if (!domain) continue;
    if (domain.kind === "enum") {
      if (!domain.values.includes(value as string)) {
        throw new ThemeDecisionDomainError(
          `decision "${id}" value ${JSON.stringify(value)} is outside its closed domain ` +
            domain.values.join(" | ")
        );
      }
      continue;
    }
    if (domain.kind === "scale") {
      if (typeof value !== "number" || !Number.isFinite(value)) {
        throw new ThemeDecisionDomainError(
          `decision "${id}" must be a finite number; got ${JSON.stringify(value)}`
        );
      }
      if (value < domain.min || value > domain.max) {
        throw new ThemeDecisionDomainError(
          `decision "${id}" value ${value} is outside its closed range ` +
            `[${domain.min}, ${domain.max}]`
        );
      }
      continue;
    }
    for (const [role, seed] of Object.entries(
      (value ?? {}) as Record<string, unknown>
    )) {
      if (seed === undefined) continue;
      if (typeof seed !== "string" || !HEX.test(seed)) {
        throw new ThemeDecisionDomainError(
          `decision "${id}" role "${role}" must be a hex colour; got ${JSON.stringify(seed)}`
        );
      }
    }
  }
}

/** The source this module is generated from, for a reader who lands here. */
export const THEME_DECISION_SCHEMA_SOURCE =
  "src/contracts/theme/runtime/catalog (generated into src/infrastructure/compilers/kernel/foundation/schemas/tenant-theme/decisions/index.ts)";
