/**
 * The independent oracle: expectations computed OUTSIDE the pipeline they bind.
 *
 * WHY IT EXISTS. A parity suite that compares the emitted document against the
 * same artifact declaration "run through the same resolve+evaluate pipeline"
 * has the pipeline on both sides of the comparison, so a resolver or evaluator
 * defect cancels. Two of the hardest planted mutants -- a mix that drops alpha,
 * and a cycle member that hooks its own fallback -- pass such a comparison BY
 * CONSTRUCTION, and the cycle one also survives domain parity, because the
 * channel merely moves from `unresolved` into `tokens` and the union is
 * unchanged. These rows are what makes those two die.
 *
 * Every expectation below is hand-computed and its derivation is written beside
 * it. Nothing here is generated by anything in the lot's write set, and each row
 * is asserted against `resolveChannelValue` / `evaluateCssValue` DIRECTLY rather
 * than through `emitThemeTokens`, so the oracle never inherits the emitter's own
 * assembly.
 *
 * The four custom-property semantics are O-1 to O-4, one per rule; O-5 and O-6
 * are the two interpolation spaces.
 */

import { TOKEN_EMISSION_BOUNDS } from "@/contracts/theme/runtime/compilation";

/** The semantics a row binds. The suite asserts all six are represented. */
export type OracleSubject =
  | "iacvt-fallback-hooks"
  | "cycle-member-fallback-irrelevant"
  | "open-branch-not-seen-set"
  | "depth-guard-never-hooks"
  | "mix-srgb"
  | "mix-oklab";

export interface OracleRow {
  readonly id: string;
  readonly subject: OracleSubject;
  /** Why the expectation is what it is, computed outside this pipeline. */
  readonly derivation: string;
}

export interface ResolutionOracleRow extends OracleRow {
  readonly kind: "resolution";
  readonly scope: Readonly<Record<string, string>>;
  /** The resolved literal per channel; a channel that must refuse is absent. */
  readonly resolved: Readonly<Record<string, string>>;
  readonly refusals: readonly { channel: string; reason: string }[];
}

export interface EvaluationOracleRow extends OracleRow {
  readonly kind: "evaluation";
  readonly value: string;
  readonly srgb: readonly [number, number, number];
  readonly alpha: number;
  /** ±0 for an sRGB-space mix; the declared tolerance for an oklab one. */
  readonly tolerance: number;
}

const DEPTH_CHAIN = ((): Record<string, string> => {
  // A plain chain over a literal bottom, with the fallback on the TOP link --
  // the one the guard actually fires at. With it at the bottom instead, every
  // level the guard reaches has no fallback to hook and the row cannot tell a
  // hooking guard from a refusing one.
  const ceiling = TOKEN_EMISSION_BOUNDS.maxResolutionDepth;
  const scope: Record<string, string> = { "--ds-oracle-link-0": "1px" };
  for (let index = 1; index <= ceiling + 1; index += 1) {
    scope[`--ds-oracle-link-${index}`] = `var(--ds-oracle-link-${index - 1})`;
  }
  scope[`--ds-oracle-link-${ceiling + 2}`] = `var(--ds-oracle-link-${ceiling + 1}, 7px)`;
  return scope;
})();

/**
 * Resolving `--ds-oracle-link-N` nests N levels, so the guard fires for every N
 * strictly above the ceiling. With links 0..ceiling+2 declared, that is exactly
 * the top two.
 */
export const DEPTH_CHAIN_REFUSERS: readonly string[] = Object.freeze([
  `--ds-oracle-link-${TOKEN_EMISSION_BOUNDS.maxResolutionDepth + 1}`,
  `--ds-oracle-link-${TOKEN_EMISSION_BOUNDS.maxResolutionDepth + 2}`,
]);

export const RESOLUTION_ORACLE: readonly ResolutionOracleRow[] = Object.freeze<ResolutionOracleRow[]>([
  {
    kind: "resolution",
    id: "O-1",
    subject: "iacvt-fallback-hooks",
    derivation:
      "A property nobody declares is guaranteed-invalid, and for the reference consuming it that is indistinguishable from not existing. The consuming fallback therefore HOOKS and the channel resolves to it.",
    scope: { "--ds-oracle-a": "var(--ds-oracle-nowhere, 4px)" },
    resolved: { "--ds-oracle-a": "4px" },
    refusals: [],
  },
  {
    kind: "resolution",
    id: "O-2",
    subject: "cycle-member-fallback-irrelevant",
    derivation:
      "The graph's edges are made by each reference's FIRST argument, so a fallback is not an escape: both members of the cycle compute to guaranteed-invalid and neither 1px nor 2px is ever emitted. Only the EXTERNAL consumer hooks its own fallback, so the third channel resolves to 9px. This is the row a cycle member that hooks its own fallback dies on -- domain parity cannot catch it, because the channel merely moves from unresolved into tokens.",
    scope: {
      "--ds-oracle-c1": "var(--ds-oracle-c2, 1px)",
      "--ds-oracle-c2": "var(--ds-oracle-c1, 2px)",
      "--ds-oracle-out": "var(--ds-oracle-c1, 9px)",
    },
    resolved: { "--ds-oracle-out": "9px" },
    refusals: [
      { channel: "--ds-oracle-c1", reason: "cycle" },
      { channel: "--ds-oracle-c2", reason: "cycle" },
    ],
  },
  {
    kind: "resolution",
    id: "O-3",
    subject: "open-branch-not-seen-set",
    derivation:
      "A diamond, not a loop: two sibling branches reach the same leaf. Detection by open BRANCH stack resolves it to `3px 3px`; a global seen-set would report the second branch as a false cycle, which is the class of 36 false cycles that spelling produced.",
    scope: {
      "--ds-oracle-d": "var(--ds-oracle-x) var(--ds-oracle-y)",
      "--ds-oracle-x": "var(--ds-oracle-z)",
      "--ds-oracle-y": "var(--ds-oracle-z)",
      "--ds-oracle-z": "3px",
    },
    resolved: {
      "--ds-oracle-d": "3px 3px",
      "--ds-oracle-x": "3px",
      "--ds-oracle-y": "3px",
      "--ds-oracle-z": "3px",
    },
    refusals: [],
  },
  {
    kind: "resolution",
    id: "O-4",
    subject: "depth-guard-never-hooks",
    derivation:
      "The chain bottoms out in the literal 1px and is longer than the declared ceiling, so resolving link N nests N levels and the two links above the ceiling refuse. The fallback of 7px sits on the TOP link, which is the link the guard fires at: the depth guard is the resolver's OWN guard rather than a real invalidity, so it never hooks it, and a document that emitted 7px here would be reporting the guard as a value. The fallback has to sit there and not at the bottom -- with it at the bottom every level the guard reaches carries none, so a guard that hooked one would have nothing to hook and the row would pass either way.",
    scope: DEPTH_CHAIN,
    resolved: {
      "--ds-oracle-link-0": "1px",
      [`--ds-oracle-link-${TOKEN_EMISSION_BOUNDS.maxResolutionDepth}`]: "1px",
    },
    refusals: DEPTH_CHAIN_REFUSERS.map((channel) => ({ channel, reason: "depth" })),
  },
]);

export const EVALUATION_ORACLE: readonly EvaluationOracleRow[] = Object.freeze<EvaluationOracleRow[]>([
  {
    kind: "evaluation",
    id: "O-5",
    subject: "mix-srgb",
    derivation:
      "CSS Color 5 mixes PREMULTIPLIED. `transparent` is rgb(0 0 0 / 0), so its premultiplied contribution is zero at every channel: the result is #3366ff's own channels at alpha 0.9. Two failure modes die on this one row -- a hex-only mixer returns #3366ff at alpha 1, and an un-premultiplied mix drags the colour toward the transparent operand's black (roughly [46,92,230]).",
    value: "color-mix(in srgb, #3366ff 90%, transparent)",
    srgb: [51, 102, 255],
    alpha: 0.9,
    tolerance: TOKEN_EMISSION_BOUNDS.srgbChannelTolerance,
  },
  {
    kind: "evaluation",
    id: "O-6",
    subject: "mix-oklab",
    derivation:
      "The midpoint of #3366ff and #ffffff taken in oklab, then returned to sRGB through the colour owner's own terminal, which reduces chroma until the colour re-enters the gamut (the raw midpoint leaves it: its blue is 1.0525 in linear sRGB, 1.0227 once gamma-encoded). The same midpoint CLIPPED instead of chroma-reduced is [149,184,255]; the gamma-sRGB midpoint is [153,179,255]. All three differ, so the row distinguishes the interpolation spaces rather than merely exercising the code path. Errata against the design debrief: \"§3.2 O-6: the value the row pins is the named chain's [152,184,255]; the review-time [149,184,255] was a per-channel clip the DS does not implement; the ±1/255 tolerance is premised on the named mapping.\"",
    value: "color-mix(in oklab, #3366ff 50%, #ffffff)",
    srgb: [152, 184, 255],
    alpha: 1,
    tolerance: TOKEN_EMISSION_BOUNDS.oklabSrgbChannelTolerance * 255,
  },
  {
    kind: "evaluation",
    id: "O-5b",
    subject: "mix-srgb",
    derivation:
      "The same premultiplied law with both operands opaque: an even mix of blue and white in gamma sRGB is the arithmetic midpoint, [153,179,255]. It is stated beside O-6 so the two spaces are read against ONE pair of colours.",
    value: "color-mix(in srgb, #3366ff 50%, #ffffff)",
    srgb: [153, 179, 255],
    alpha: 1,
    tolerance: TOKEN_EMISSION_BOUNDS.srgbChannelTolerance,
  },
]);

export const ORACLE_ROWS: readonly OracleRow[] = Object.freeze([
  ...RESOLUTION_ORACLE,
  ...EVALUATION_ORACLE,
]);

export const ORACLE_SUBJECTS: readonly OracleSubject[] = Object.freeze([
  "iacvt-fallback-hooks",
  "cycle-member-fallback-irrelevant",
  "open-branch-not-seen-set",
  "depth-guard-never-hooks",
  "mix-srgb",
  "mix-oklab",
]);
