/**
 * The human views of the derived graph.
 *
 * SAME LAW AS THE GRAPH: nothing here is authored. Both files are rendered from
 * `by-control.json` and `by-family.json`, which are themselves rendered from the
 * derivation, so a row can only say what the compiler and the tree said. A view
 * a person could edit and keep is the failure this whole WO exists against --
 * `--check` re-renders and compares bytes, so a hand-edit is a red, not a habit.
 *
 * WHY MARKDOWN AND NOT MORE JSON. The two JSON views already answer the machine.
 * These answer the question a person actually arrives with -- "what does this
 * control move, and why does this family not change" -- and they answer it with
 * counts that are traceable back to the graph by the digest each file carries.
 *
 * ENGLISH, because `scripts/check/docs` refuses a Spanish public document, and
 * these are public documents.
 */
import { createHash } from "node:crypto";

const sha256 = (text) => createHash("sha256").update(text).digest("hex");

/** A table cell that can never break the row: pipes escaped, empty marked. */
function cell(value) {
  if (Array.isArray(value)) return value.length === 0 ? "—" : value.map((item) => `\`${item}\``).join(", ");
  if (value === undefined || value === "") return "—";
  return String(value).replace(/[|]/g, "\\|");
}

/** The banner every generated document in this tree carries, plus this one's inputs. */
function banner(title, command, source, digest, lines) {
  return [
    `# ${title} (generated)`,
    "",
    `> Generated by \`${command}\`. Do not hand-edit.`,
    `> Source: \`${source}\`, itself derived by \`scripts/generate/theme-graph\` from a dry-run of the`,
    "> compiler over 3 verticals x 2 modes plus the measured read census. Every number below is measured;",
    "> a fact that was not measured has no row rather than a cell saying so.",
    ...lines.map((line) => `> ${line}`),
    "",
    `digest: ${digest}`,
    "",
    "",
  ].join("\n");
}

/**
 * One row per decision.
 *
 * `produced` and `via aliases` are BOTH published because they answer different
 * questions and conflating them overstates reach: a deriver produces
 * `--ds-radius-md`, and the card skin reads `--ds-card-radius`, which aliases to
 * it. The first column is what the decision emits; the second is what it can
 * still reach once the measured alias chain is walked.
 */
export function renderControlsView(document) {
  const rows = [...document.controls].sort((a, b) => a.decision.localeCompare(b.decision));
  const reaching = rows.filter((row) => row.families.length > 0);
  const inert = rows.filter((row) => row.families.length === 0);

  const body = [
    "| decision | tier | derivers | produced | via aliases | families reached |",
    "|---|---|---|---|---|---|",
    ...rows.map((row) => [
      "",
      `\`${row.decision}\``,
      row.tier,
      row.derivers.length === 0 ? "—" : String(row.derivers.length),
      String(row.channels),
      String(row.channelsThroughAliases),
      row.families.length === 0 ? "**none**" : String(row.families.length),
      "",
    ].join(" | ").trim()),
    "",
    "## Decisions that reach no family",
    "",
    inert.length === 0
      ? "None: every decision in the catalog reaches at least one skin family."
      : [
          "These are measured facts, not gaps to be filled by hand. A decision reaches no family when no",
          "deriver declares a `consumes` keypath covering it, which the graph reads from the derivers",
          "themselves.",
          "",
          ...inert.map((row) => `- \`${row.decision}\` (${row.tier})`),
        ].join("\n"),
    "",
    "## Families reached, per decision",
    "",
    "| decision | families |",
    "|---|---|",
    ...reaching.map((row) => `| \`${row.decision}\` | ${cell(row.families)} |`),
    "",
  ].join("\n");

  return banner(
    "Theme graph — by control",
    "pnpm --filter @rottay/design-system ds:derive:views",
    "packages/core/artifacts/generated/theme-graph/by-control.json",
    sha256(JSON.stringify(document)),
    [
      `${rows.length} decisions; ${reaching.length} reach at least one family, ${inert.length} reach none.`,
      "`produced` counts the channels the decision's derivers emit; `via aliases` counts what those",
      "channels can still reach through the measured alias chain.",
    ],
  ) + body;
}

/** One row per skin family, with the decisions that can reach it. */
export function renderFamiliesView(document) {
  const rows = [...document.families].sort((a, b) => a.family.localeCompare(b.family));
  const reached = rows.filter((row) => row.decisions.length > 0);
  const unreached = rows.filter((row) => row.decisions.length === 0);

  const body = [
    "| family | tier | decisions reaching it |",
    "|---|---|---|",
    ...rows.map((row) => `| \`${row.family}\` | ${cell(row.tier)} | ${row.decisions.length === 0 ? "**none**" : String(row.decisions.length)} |`),
    "",
    "## Families no decision reaches",
    "",
    unreached.length === 0
      ? "None: every skin family on disk is reachable from at least one catalog decision."
      : [
          "A family appears here when no decision's channels, followed through the alias chain, are read by",
          "any of its skin's measured read sites. That is a measurement of today's derivation, not a verdict",
          "on the family.",
          "",
          ...unreached.map((row) => `- \`${row.family}\`${row.tier === undefined ? "" : ` (${row.tier})`}`),
        ].join("\n"),
    "",
    "## Which decisions reach each family",
    "",
    "| family | decisions |",
    "|---|---|",
    ...reached.map((row) => `| \`${row.family}\` | ${cell(row.decisions)} |`),
    "",
  ].join("\n");

  return banner(
    "Theme graph — by family",
    "pnpm --filter @rottay/design-system ds:derive:views",
    "packages/core/artifacts/generated/theme-graph/by-family.json",
    sha256(JSON.stringify(document)),
    [
      `${rows.length} skin families; ${reached.length} are reached by at least one decision, ${unreached.length} by none.`,
      "The tier is the component tier that owns the family; a family with no component folder carries none.",
    ],
  ) + body;
}

export const VIEWS = Object.freeze({
  "controls.md": renderControlsView,
  "families.md": renderFamiliesView,
});
