/**
 * @fileoverview Wave G0 — Regression Harness And Baseline Capture
 *
 * Safety net capturing current first-party premium outputs and shared
 * generator coverage BEFORE any structural refactoring.
 *
 * Coverage matrix (post-G1):
 * - palette: SHARED (generated via color scale)
 * - personality: SHARED (animation, chart, card, accent, typography)
 * - density: SHARED (--ds-density-scale)
 * - sidebar: SHARED (--ds-sidebar-* from BrandTheme.chrome.sidebar)
 * - controls: SHARED (--ds-button-*, --ds-input-* from BrandTheme.chrome.controls)
 * - table: SHARED (--ds-table-header-* from BrandTheme.chrome.table)
 * - layout: SHARED (--ds-layout-* from BrandTheme.chrome.layout)
 * - shell: SHARED (--ds-shell-* from BrandTheme.chrome.shell)
 *
 * When the shared pipeline is extended in G1, tests in the
 * "currently first-party-only" sections should start passing through
 * the shared path too.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import type { TenantConfig } from '../../../contracts';
import { generateTenantCss } from '../../../runtime/tenant/storage/static/generator';
import { brandThemeToChromeVariables } from '../index';
import { isBundledTenant, BUNDLED_TENANT_SLUGS } from '../../../runtime/tenant/registry';
import { bithireBrandTheme, evntoBrandTheme, rottayBrandTheme } from '../../../tokens/ts/brand-themes';

// ── Helpers ─────────────────────────────────────────────

/** Extract all CSS variable declarations from a CSS string. */
function extractVars(css: string): string[] {
  const matches = css.match(/--[\w-]+(?=\s*:)/g);
  return matches ? [...new Set(matches)] : [];
}

/** Check that a CSS string contains all expected variable prefixes. */
function expectVarPrefixes(css: string, prefixes: string[]) {
  const vars = extractVars(css);
  for (const prefix of prefixes) {
    const found = vars.some((v) => v.startsWith(prefix));
    expect(found, `expected CSS to contain vars starting with ${prefix}`).toBe(true);
  }
}

/** Read a first-party CSS file and return its content. */
function readTenantCss(tenant: string): string {
  const cssPath = resolve(
    __dirname,
    `../../../tokens/css/artifacts/${tenant}/index.css`
  );
  return readFileSync(cssPath, 'utf-8');
}

// ── First-party tenant configs for testing ──────────────

const BITHIRE_CONFIG: TenantConfig = {
  slug: 'bithire',
  name: 'BitHire',
  engine: 'classic',
  theme: 'base',
  plan: 'enterprise',
  features: ['*'],
  branding: {
    companyName: 'BitHire',
    primaryColor: '#0A66C2',
    secondaryColor: '#004182',
    accentColor: '#7FC15E',
  },
  brandTheme: bithireBrandTheme,
};

const EVNTO_CONFIG: TenantConfig = {
  slug: 'evnto',
  name: 'Evnto',
  engine: 'classic',
  theme: 'base',
  plan: 'enterprise',
  features: ['*'],
  branding: {
    companyName: 'Evnto',
    primaryColor: '#171717',
    secondaryColor: '#b8a898',
    accentColor: '#b8a898',
  },
  vertical: 'evnto',
  brandTheme: evntoBrandTheme,
};

const ROTTAY_CONFIG: TenantConfig = {
  slug: 'rottay',
  name: 'Rottay',
  engine: 'classic',
  theme: 'base',
  plan: 'enterprise',
  features: ['*'],
  branding: { companyName: 'Rottay' },
  brandTheme: rottayBrandTheme,
};

// ══════════════════════════════════════════════════════════
// SECTION 1: Shared Pipeline Baseline
// These vars are generated by generateTenantCss() today.
// If any of these break, the shared pipeline regressed.
// ══════════════════════════════════════════════════════════

describe('shared pipeline: palette baseline', () => {
  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates full primary color scale',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      for (const step of [50, 100, 200, 300, 400, 500, 600, 700, 800, 900]) {
        expect(css).toContain(`--ds-color-primary-${step}`);
      }
    }
  );
});

describe('shared pipeline: personality baseline', () => {
  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates animation personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-animation-intensity');
      expect(css).toContain('--ds-personality-animation-entrance');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates chart personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-chart-line-style');
      expect(css).toContain('--ds-personality-chart-tooltip-style');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates card personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-card-padding-density');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates accent personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-accent-bar-style');
    }
  );

  it.each(['bithire', 'evnto', 'rottay'] as const)(
    '%s generates typography personality vars',
    (tenant) => {
      const config = { bithire: BITHIRE_CONFIG, evnto: EVNTO_CONFIG, rottay: ROTTAY_CONFIG }[tenant];
      const css = generateTenantCss(config, { includeDarkSelector: false });
      expect(css).toContain('--ds-personality-typography-heading-letter-spacing');
    }
  );
});

describe('shared pipeline: density baseline', () => {
  it('bithire generates density scale from brandTheme', () => {
    const css = generateTenantCss(BITHIRE_CONFIG, { includeDarkSelector: false });
    expect(css).toContain('--ds-density-scale: 0.95');
  });

  it('evnto generates density scale from vertical + brandTheme', () => {
    const css = generateTenantCss(EVNTO_CONFIG, { includeDarkSelector: false });
    // evnto brandTheme has 1.125, evnto vertical has 1.125 too
    expect(css).toContain('--ds-density-scale: 1.125');
  });
});

// ══════════════════════════════════════════════════════════
// SECTION 2: First-Party CSS Snapshot Baseline
// These premium vars exist in handwritten CSS but are NOT yet
// generated by the shared pipeline. When G1 completes, some
// of these should move to Section 1.
// ══════════════════════════════════════════════════════════

describe('first-party CSS baseline: sidebar vars', () => {
  it('bithire CSS has sidebar chrome', () => {
    const css = readTenantCss('bithire');
    expectVarPrefixes(css, [
      '--ds-sidebar-bg',
      '--ds-sidebar-text',
      '--ds-sidebar-item-color',
      '--ds-sidebar-item-bg-active',
      '--ds-sidebar-group-font-size',
      '--ds-sidebar-icon-size',
    ]);
  });

  it('rottay CSS has sidebar chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-sidebar-bg',
      '--ds-sidebar-border',
      '--ds-sidebar-width',
      '--ds-sidebar-collapsed-width',
      '--ds-sidebar-header-height',
      '--ds-sidebar-item-font-size',
      '--ds-sidebar-footer-bg',
    ]);
  });

  it('evnto CSS has sidebar chrome', () => {
    const css = readTenantCss('evnto');
    expectVarPrefixes(css, [
      '--ds-sidebar-bg',
      '--ds-sidebar-text',
      '--ds-sidebar-item-color',
      '--ds-sidebar-group-font-size',
    ]);
  });
});

describe('first-party CSS baseline: controls vars', () => {
  it('bithire CSS has button chrome', () => {
    const css = readTenantCss('bithire');
    // First-party CSS uses the same engine-consumed -color names as the shared pipeline.
    expectVarPrefixes(css, [
      '--ds-button-primary-bg',
      '--ds-button-primary-color',
      '--ds-button-secondary-bg',
      '--ds-button-secondary-color',
    ]);
    expect(css).not.toContain('--ds-button-primary-text');
    expect(css).not.toContain('--ds-button-secondary-text');
  });

  it('bithire CSS has input chrome', () => {
    const css = readTenantCss('bithire');
    expectVarPrefixes(css, [
      '--ds-input-bg',
      '--ds-input-border',
      '--ds-input-border-focus',
    ]);
  });

  it('rottay CSS has full button variant chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-button-primary-bg',
      '--ds-button-secondary-bg',
      '--ds-button-default-bg',
      '--ds-button-ghost-bg',
      '--ds-button-success-bg',
    ]);
  });

  it('evnto CSS has button and input chrome', () => {
    const css = readTenantCss('evnto');
    expectVarPrefixes(css, [
      '--ds-button-primary-bg',
      '--ds-button-secondary-bg',
      '--ds-input-bg',
      '--ds-input-border',
    ]);
  });
});

describe('first-party CSS baseline: table vars', () => {
  it.each(['bithire', 'rottay', 'evnto'] as const)(
    '%s CSS has table header chrome',
    (tenant) => {
      const css = readTenantCss(tenant);
      expectVarPrefixes(css, ['--ds-table-header-bg']);
    }
  );
});

describe('first-party CSS baseline: layout vars', () => {
  it('rottay CSS has layout chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-layout-bg',
      '--ds-layout-header-bg',
      '--ds-layout-header-backdrop',
      '--ds-layout-sider-bg',
    ]);
  });
});

describe('first-party CSS baseline: shell vars', () => {
  it('rottay CSS has shell grid chrome', () => {
    const css = readTenantCss('rottay');
    expectVarPrefixes(css, [
      '--ds-shell-grid-size',
      '--ds-shell-grid-line',
    ]);
  });
});

// ══════════════════════════════════════════════════════════
// SECTION 3: Gap documentation
// Verify that the shared pipeline does NOT yet generate
// these categories — so we know what G1 needs to close.
// ══════════════════════════════════════════════════════════

describe('shared pipeline: chrome vars NOW generated (G1)', () => {
  const rottayCss = generateTenantCss(ROTTAY_CONFIG, { includeDarkSelector: false });
  const bithireCss = generateTenantCss(BITHIRE_CONFIG, { includeDarkSelector: false });

  it('rottay generates sidebar vars with correct values', () => {
    expect(rottayCss).toContain('--ds-sidebar-bg: #0D0D10');
    expect(rottayCss).toContain('--ds-sidebar-text: #ECECEC');
    expect(rottayCss).toContain('--ds-sidebar-width: 296px');
    expect(rottayCss).toContain('--ds-sidebar-item-color: #A0A0A5');
    expect(rottayCss).toContain('--ds-sidebar-footer-bg: #0D0D10');
  });

  it('bithire generates button variant vars with correct values', () => {
    expect(bithireCss).toContain('--ds-button-primary-bg: #0A66C2');
    expect(bithireCss).toContain('--ds-button-primary-color: #ffffff');
    expect(bithireCss).toContain('--ds-button-secondary-color: #0A66C2');
    expect(bithireCss).toContain('--ds-button-secondary-border: #0A66C2');
  });

  it('bithire generates input vars with correct values', () => {
    expect(bithireCss).toContain('--ds-input-bg: #ffffff');
    expect(bithireCss).toContain('--ds-input-border-focus: #0A66C2');
    expect(bithireCss).toContain('--ds-input-shadow-focus: 0 0 0 1px #0A66C2');
  });

  it('rottay generates layout vars with correct values', () => {
    expect(rottayCss).toContain('--ds-layout-bg: #0C0C0E');
    expect(rottayCss).toContain('--ds-layout-header-bg: rgba(12, 12, 14, 0.82)');
    expect(rottayCss).toContain('--ds-layout-sider-bg: #0D0D10');
  });

  it('rottay generates shell vars with correct values', () => {
    expect(rottayCss).toContain('--ds-shell-grid-size: 28px');
    expect(rottayCss).toContain('--ds-shell-grid-line: rgba(255, 255, 255, 0.03)');
  });

  it('rottay generates table vars with correct values', () => {
    expect(rottayCss).toContain('--ds-table-header-bg: #131316');
    expect(rottayCss).toContain('--ds-table-header-color: #A0A0A5');
  });

  it('bithire generates table vars with correct values', () => {
    expect(bithireCss).toContain('--ds-table-header-bg: #f3f2ef');
    expect(bithireCss).toContain('--ds-table-header-font-weight: 600');
  });

  it('DB-backed tenant with BrandTheme gets same chrome vars', () => {
    const dbConfig: TenantConfig = {
      slug: 'db-premium',
      name: 'DB Premium',
      engine: 'modern',
      theme: 'base',
      plan: 'enterprise',
      features: [],
      branding: { companyName: 'DB Corp' },
      brandTheme: rottayBrandTheme,
    };
    const css = generateTenantCss(dbConfig, { includeDarkSelector: false });
    expect(css).toContain('--ds-sidebar-bg: #0D0D10');
    expect(css).toContain('--ds-layout-bg: #0C0C0E');
    expect(css).toContain('--ds-shell-grid-size: 28px');
    expect(css).toContain("html[data-tenant='db-premium']");
  });
});

// ══════════════════════════════════════════════════════════
// SECTION 4: Dark mode safety + variable naming correctness
// ══════════════════════════════════════════════════════════

describe('dark mode: chrome vars NOT in dark block', () => {
  it('generated dark CSS does not contain light-mode chrome values', () => {
    const css = generateTenantCss(ROTTAY_CONFIG, { includeDarkSelector: true });
    // Split into blocks: light block is first, dark blocks follow
    const darkMatch = css.match(/\[data-theme='dark'\][^{]*\{([^}]+)\}/s);
    const darkBlock = darkMatch?.[1] ?? '';
    // Dark block should NOT contain light sidebar/layout chrome
    expect(darkBlock).not.toContain('--ds-sidebar-bg: #0D0D10');
    expect(darkBlock).not.toContain('--ds-layout-bg: #0C0C0E');
    expect(darkBlock).not.toContain('--ds-shell-grid-size: 28px');
  });

  it('light block contains chrome vars', () => {
    const css = generateTenantCss(ROTTAY_CONFIG, { includeDarkSelector: true });
    // First block (before any dark selector) should have chrome
    const lightBlock = css.split("[data-theme='dark']")[0];
    expect(lightBlock).toContain('--ds-sidebar-bg: #0D0D10');
    expect(lightBlock).toContain('--ds-layout-bg: #0C0C0E');
  });
});

describe('variable naming: engines consume --ds-button-*-color', () => {
  it('shared pipeline emits -color not -text for button text vars', () => {
    const css = generateTenantCss(BITHIRE_CONFIG, { includeDarkSelector: false });
    // Engines consume --ds-button-primary-color, NOT --ds-button-primary-text
    expect(css).toContain('--ds-button-primary-color');
    expect(css).not.toContain('--ds-button-primary-text');
    expect(css).toContain('--ds-button-secondary-color');
    expect(css).not.toContain('--ds-button-secondary-text');
  });

  it('rottay pipeline emits -color for all button variants', () => {
    const css = generateTenantCss(ROTTAY_CONFIG, { includeDarkSelector: false });
    expect(css).toContain('--ds-button-primary-color');
    expect(css).toContain('--ds-button-secondary-color');
    expect(css).toContain('--ds-button-default-color');
    expect(css).toContain('--ds-button-ghost-color');
    expect(css).not.toContain('--ds-button-primary-text');
  });
});

describe('dynamic tenant runtime chrome: scoped <style> path', () => {
  it('brandThemeToChromeVariables produces vars for scoped injection', () => {
    // This is what DesignSystemProvider uses to build the <style> tag
    // for dynamic tenants (skipCssLoading=false)
    const vars = brandThemeToChromeVariables(rottayBrandTheme);
    expect(vars['--ds-sidebar-bg']).toBe('#0D0D10');
    expect(vars['--ds-layout-bg']).toBe('#0C0C0E');
    expect(vars['--ds-button-primary-color']).toBe('#0C0C0E');
    expect(vars['--ds-shell-grid-size']).toBe('28px');
    expect(vars['--ds-table-header-bg']).toBe('#131316');
  });

  it('scoped CSS string uses tenant selector (dark-mode safe)', () => {
    const vars = brandThemeToChromeVariables(bithireBrandTheme);
    const entries = Object.entries(vars).filter(([, v]) => v != null);
    const declarations = entries.map(([k, v]) => `  ${k}: ${v};`).join('\n');
    const scopedCss = `html[data-tenant='db-customer'] {\n${declarations}\n}`;

    // Scoped selector — will NOT override dark-mode tenant CSS
    expect(scopedCss).toContain("html[data-tenant='db-customer']");
    expect(scopedCss).toContain('--ds-button-primary-bg: #0A66C2');
    expect(scopedCss).toContain('--ds-sidebar-bg: #ffffff');
    // NOT inline on :root — proper specificity
    expect(scopedCss).not.toContain(':root');
  });

  it('dynamic tenant without brandTheme produces no chrome CSS', () => {
    const plainConfig: TenantConfig = {
      slug: 'plain',
      name: 'Plain',
      engine: 'modern',
      theme: 'base',
      plan: 'pro',
      features: [],
      branding: { companyName: 'Plain Corp', primaryColor: '#333' },
    };
    // No brandTheme -> no chrome vars
    const vars = brandThemeToChromeVariables(plainConfig.brandTheme ?? { id: '', name: '' });
    expect(Object.keys(vars).length).toBe(0);
  });
});

describe('DesignSystemProvider chrome injection logic', () => {
  // These tests verify the condition logic used by DesignSystemProvider
  // to decide when to pass generatedChromeCss to ThemeProvider.
  // The actual injection is: brandTheme exists AND tenant is NOT bundled.

  it('BUNDLED_TENANT_SLUGS matches CSS bundle (tokens/css/artifacts/index.css)', () => {
    // Must include all tenants whose CSS is in the bundle
    expect(BUNDLED_TENANT_SLUGS.has('rottay')).toBe(true);
    expect(BUNDLED_TENANT_SLUGS.has('bithire')).toBe(true);
    expect(BUNDLED_TENANT_SLUGS.has('evnto')).toBe(true);
    expect(BUNDLED_TENANT_SLUGS.has('themanagementmiami')).toBe(true);
    expect(BUNDLED_TENANT_SLUGS.size).toBe(4);
  });

  it('bundled tenants do NOT get generated chrome CSS', () => {
    expect(isBundledTenant('bithire')).toBe(true);
    expect(isBundledTenant('rottay')).toBe(true);
    expect(isBundledTenant('evnto')).toBe(true);
    expect(isBundledTenant('themanagementmiami')).toBe(true);
  });

  it('unknown DB tenants DO get generated chrome CSS', () => {
    expect(isBundledTenant('acme-corp')).toBe(false);
    expect(isBundledTenant('db-customer')).toBe(false);
  });

  it('the full condition: brandTheme + not-bundled = chrome CSS', () => {
    // Simulating the DesignSystemProvider condition:
    // normalizedConfig.brandTheme && !isBundledTenant(normalizedConfig.slug)

    // DB tenant with brandTheme -> gets chrome
    const dbWithBrand = { brandTheme: bithireBrandTheme, slug: 'acme-corp' };
    expect(!!dbWithBrand.brandTheme && !isBundledTenant(dbWithBrand.slug)).toBe(true);

    // Bundled tenant with brandTheme -> NO chrome (already in CSS)
    const bundledWithBrand = { brandTheme: bithireBrandTheme, slug: 'bithire' };
    expect(!!bundledWithBrand.brandTheme && !isBundledTenant(bundledWithBrand.slug)).toBe(false);

    // themanagementmiami (bundled CSS, no runtime config) -> NO chrome
    const tmm = { brandTheme: bithireBrandTheme, slug: 'themanagementmiami' };
    expect(!!tmm.brandTheme && !isBundledTenant(tmm.slug)).toBe(false);

    // DB tenant without brandTheme -> NO chrome (nothing to generate)
    const dbNoBrand = { brandTheme: undefined, slug: 'acme-corp' };
    expect(!!dbNoBrand.brandTheme && !isBundledTenant(dbNoBrand.slug)).toBe(false);
  });
});
