/**
 * Types for `@rottay/design-system/hooks-manifest` — the published application
 * customization contract.
 *
 * The artifact is generated by `pnpm hooks:generate` and kept honest by
 * `pnpm hooks:check` (chained into `prebuild`). Do not hand-edit either file.
 *
 * What the contract answers, for an application that never opens this repo:
 *   - `publicHooks`      the `--ds-*` properties an app may assign under its own
 *                        feature scope.
 *   - `declaredSlots`    the subset promoted by owner review, each with the terms
 *                        of use — who reads it, what may be assigned, what a
 *                        tenant still controls, and how far the repaint reaches.
 *   - `foundationTokens` / `tenantChannel` the closed sets. Assigning one from an
 *                        application re-derives a DS-owned value or overrides the
 *                        tenant's brand.
 *
 * App-owned composition and feature styling uses the `--rt-*` namespace, which is
 * always legal and is not described here.
 */

/**
 * How much of a tenant's white-label control survives an application assigning
 * this slot inside its scope.
 *
 * - `not-tenant-emitted`  the chrome compiler never writes this name; nothing a
 *   tenant configures can be overridden.
 * - `propagates-channel`  the assignment reads the tenant's own channel, so the
 *   tenant's value still lands inside the scope.
 * - `derives-from-palette`  the assignment chains through tenant palette/surface
 *   tokens, so brand colour propagates — but a tenant's explicit override of this
 *   particular channel does not reach the scope. This is declared residual risk.
 */
export type WhiteLabelCompat =
  | "not-tenant-emitted"
  | "propagates-channel"
  | "derives-from-palette";

/** The seven declared terms of one promoted slot, plus the reason it was promoted. */
export interface DeclaredSlot {
  /** Grouping id shared by slots promoted under one rationale. */
  readonly family: string;
  /** The component or family that actually reads the property. */
  readonly owner: string;
  /** The scope under which assigning the property is supported. */
  readonly slot: string;
  /** What may be assigned. */
  readonly valueType: string;
  /** What resolves when no application assigns it. */
  readonly fallback: string;
  /** Package version in which the slot became public. */
  readonly sinceVersion: string;
  readonly whiteLabelCompat: WhiteLabelCompat;
  /** The blast radius of an assignment, stated rather than left unknown. */
  readonly subtreeRepaint: string;
  readonly rationale: string;
}

export interface HookManifestAnchor {
  readonly id: string;
  readonly path: string;
  readonly describes: string;
}

export interface HookManifest {
  readonly schemaVersion: 4;
  readonly generatedBy: string;
  /** The DS sources the contract is derived from. */
  readonly generatedFrom: readonly HookManifestAnchor[];
  readonly derivation: {
    readonly publicHook: string;
    readonly unadjudicatedRead: string;
    readonly componentToken: string;
    readonly foundationToken: string;
    readonly tenantChannel: string;
  };
  readonly contract: {
    readonly mayAssign: string;
    readonly mustNotAssign: string;
    readonly appNamespace: string;
    /** Enforced: an assignment to a hook may not contain a raw colour literal. */
    readonly valueConstraint: string;
  };
  readonly counts: Readonly<Record<string, number>>;
  readonly declaredSlots: Readonly<Record<string, DeclaredSlot>>;
  /** Explicitly promoted `--ds-*` properties an application may assign. */
  readonly publicHooks: readonly string[];
  /** Decrease-only DS reads with no canonical owner; debt, never application API. */
  readonly unadjudicatedReads: readonly string[];
  /** Closed channels supplied by DS component CSS/source. */
  readonly componentTokens: readonly string[];
  /** Closed: root-declared in authored DS CSS; the DS owns the value. */
  readonly foundationTokens: readonly string[];
  /**
   * Closed: written at `:root` per tenant by the governed chrome, static
   * BrandTheme, or DB Appearance compiler.
   */
  readonly tenantChannel: readonly string[];
}

declare const manifest: HookManifest;
export default manifest;
