/**
 * Self-test for engine-freeze-gate.mjs.
 *
 * The gate's whole value is that it audits HISTORY against a sealed base rather
 * than the dirty worktree, so the fixture is a real throwaway Git repository:
 * a base commit, then a second commit that edits a frozen-engine file. A
 * dirty-tree linter reports that repo as clean (nothing is uncommitted); this
 * gate must fail it. Pure-function tests drill the collectors and the verdict
 * in isolation, mirroring container-query-gate.test.mjs's direct-import style.
 *
 * Nothing here touches the real repository: every fixture lives in a temp dir
 * and the gate is always invoked with --repo/--baseline overrides.
 */
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

import {
  BASELINE_SCHEMA_VERSION,
  DISCHARGED,
  FROZEN,
  OBLIGATIONS,
  blankModuleSpecifiers,
  evaluateDischarged,
  deriveRelocationSubstitutions,
  evaluateFreeze,
  evaluateObligations,
  relocationDigestOf,
  relocationKey,
  relocationNormalize,
  resolveMisKeyed,
  resolveRelocations,
  isGeneratedPath,
  mergeChangeSets,
  parseNameStatus,
  parsePorcelainUntracked,
  sha256,
} from './index.mjs';
import { FROZEN_ENGINE_PATH } from '../../../tokens/cascade/channels/consumers/index.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const gate = join(scriptDir, 'index.mjs');

const FROZEN_FILE = 'packages/core/src/components/primitives/layout/Box/engines/classic/index.tsx';
const OTHER_FROZEN_FILE = 'packages/core/src/components/primitives/layout/Flex/engines/rustic/index.tsx';
const MODERN_FILE = 'packages/core/src/components/primitives/layout/Box/engines/modern/index.tsx';

/* ------------------------------------------------------------------------ */
/* pure functions                                                           */
/* ------------------------------------------------------------------------ */

test('FROZEN matches classic/rustic engine folders and nothing else', () => {
  assert.ok(FROZEN.test(FROZEN_FILE));
  assert.ok(FROZEN.test(OTHER_FROZEN_FILE));
  assert.ok(!FROZEN.test(MODERN_FILE));
  // A folder that merely CONTAINS the word is not an engine folder.
  assert.ok(!FROZEN.test('packages/core/src/components/classic-layouts/index.tsx'));
  assert.ok(!FROZEN.test('packages/core/src/components/engines/custom/index.tsx'));
});

test('the freeze law and the consumer gate restate the SAME frozen-path regex', () => {
  // The two gates deliberately keep their own copy rather than importing each
  // other; this assertion is what stops the copies from drifting apart.
  assert.equal(FROZEN.source, FROZEN_ENGINE_PATH.source);
  assert.equal(FROZEN.flags, FROZEN_ENGINE_PATH.flags);
});

test('parseNameStatus keeps frozen paths with their status letter and drops the rest', () => {
  const rows = parseNameStatus(
    [`M\t${FROZEN_FILE}`, `A\t${OTHER_FROZEN_FILE}`, `M\t${MODERN_FILE}`, ''].join('\n'),
  );
  assert.deepEqual(rows, [
    { status: 'M', path: FROZEN_FILE, untracked: false },
    { status: 'A', path: OTHER_FROZEN_FILE, untracked: false },
  ]);
});

test('parsePorcelainUntracked reads only ?? rows (tracked edits come from the diff)', () => {
  const rows = parsePorcelainUntracked(
    [`?? ${FROZEN_FILE}`, ` M ${OTHER_FROZEN_FILE}`, `?? ${MODERN_FILE}`].join('\n'),
  );
  assert.deepEqual(rows, [{ status: 'A', path: FROZEN_FILE, untracked: true }]);
});

test('mergeChangeSets deduplicates a path reported by both collectors', () => {
  const merged = mergeChangeSets(
    [{ status: 'M', path: FROZEN_FILE, untracked: false }],
    [{ status: 'A', path: FROZEN_FILE, untracked: true }],
  );
  assert.equal(merged.length, 1);
  assert.equal(merged[0].untracked, false);
});

test('isGeneratedPath catches artifact paths and generation markers', () => {
  assert.ok(isGeneratedPath('packages/core/src/foundation/tokens/css/facade/artifacts/x.css', ''));
  assert.ok(isGeneratedPath(FROZEN_FILE, '/* @generated by the vertical CSS builder */'));
  assert.ok(isGeneratedPath(FROZEN_FILE, '// DO NOT EDIT — regenerate with pnpm icons:generate'));
  assert.ok(!isGeneratedPath(FROZEN_FILE, 'export const Box = () => null;'));
  assert.ok(!isGeneratedPath(FROZEN_FILE, null));
});

test('evaluateFreeze: an unlisted change is unauthorized, a pinned one passes', () => {
  const content = 'export const Box = () => null;\n';
  const entries = { [FROZEN_FILE]: { blob: sha256(content), reason: 'sealed' } };
  const verdict = evaluateFreeze({
    changes: [
      { status: 'M', path: FROZEN_FILE, untracked: false },
      { status: 'M', path: OTHER_FROZEN_FILE, untracked: false },
    ],
    entries,
    read: (path) => (path === FROZEN_FILE ? content : 'anything else'),
  });
  assert.deepEqual(verdict.unauthorized.map((c) => c.path), [OTHER_FROZEN_FILE]);
  assert.equal(verdict.drifted.length, 0);
});

test('evaluateFreeze: an authorized path that changed AGAIN drifts past its exception', () => {
  const entries = { [FROZEN_FILE]: { blob: sha256('reviewed'), reason: 'sealed' } };
  const verdict = evaluateFreeze({
    changes: [{ status: 'M', path: FROZEN_FILE, untracked: false }],
    entries,
    read: () => 'reviewed + a new edit',
  });
  assert.equal(verdict.unauthorized.length, 0);
  assert.deepEqual(verdict.drifted.map((c) => c.path), [FROZEN_FILE]);
});

test('evaluateFreeze: deleting an authorized file is a violation; a generated file never authorizes', () => {
  const entries = {
    [FROZEN_FILE]: { blob: sha256('reviewed'), reason: 'sealed' },
    [OTHER_FROZEN_FILE]: { blob: sha256('gen'), reason: 'sealed' },
  };
  const verdict = evaluateFreeze({
    changes: [
      { status: 'D', path: FROZEN_FILE, untracked: false },
      { status: 'M', path: OTHER_FROZEN_FILE, untracked: false },
    ],
    entries,
    read: (path) => (path === FROZEN_FILE ? null : '/* @generated */ gen'),
  });
  assert.deepEqual(verdict.deletedAuthorized.map((c) => c.path), [FROZEN_FILE]);
  assert.deepEqual(verdict.generated.map((c) => c.path), [OTHER_FROZEN_FILE]);
});

test('evaluateFreeze: an explicitly authorized deletion is stable, while an unlisted deletion stays red', () => {
  const verdict = evaluateFreeze({
    changes: [
      { status: 'D', path: FROZEN_FILE, untracked: false },
      { status: 'D', path: OTHER_FROZEN_FILE, untracked: false },
    ],
    entries: {
      [FROZEN_FILE]: {
        blob: null,
        reason: 'reviewed deletion of a superseded duplicate owner',
      },
    },
    read: () => null,
  });
  assert.equal(verdict.deletedAuthorized.length, 0);
  assert.deepEqual(verdict.unauthorized.map((change) => change.path), [
    OTHER_FROZEN_FILE,
  ]);
});

test('evaluateFreeze: an entry whose path no longer differs from the base is stale, not a failure', () => {
  const verdict = evaluateFreeze({
    changes: [],
    entries: { [FROZEN_FILE]: { blob: sha256('x'), reason: 'sealed' } },
    read: () => 'x',
  });
  assert.deepEqual(verdict.stale, [FROZEN_FILE]);
  assert.equal(verdict.unauthorized.length, 0);
});

/* ------------------------------------------------------------------------ */
/* fixture repository (CLI, end to end)                                     */
/* ------------------------------------------------------------------------ */

function fixture() {
  // The baseline lives OUTSIDE the fixture repository so the repo's worktree
  // stays pristine — the tests below assert on `git status` being empty.
  const home = mkdtempSync(join(tmpdir(), 'engine-freeze-gate-'));
  const dir = join(home, 'repo');
  mkdirSync(dir, { recursive: true });
  const git = (...args) =>
    execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8' }).trim();
  const write = (rel, source) => {
    const full = join(dir, rel);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, source);
    return full;
  };
  git('init', '-q');
  git('config', 'user.email', 'gate@rottay.test');
  git('config', 'user.name', 'gate');
  git('config', 'commit.gpgsign', 'false');
  write(FROZEN_FILE, 'export const Box = () => null;\n');
  write(MODERN_FILE, 'export const Box = () => null;\n');
  git('add', '-A');
  git('commit', '-q', '-m', 'base');
  const base = git('rev-parse', 'HEAD');

  const baselinePath = join(home, 'baseline.json');
  const writeBaseline = (entries, baseRevision = base) =>
    writeFileSync(
      baselinePath,
      `${JSON.stringify({ schemaVersion: BASELINE_SCHEMA_VERSION, baseRevision, entries }, null, 2)}\n`,
    );
  writeBaseline({});

  const run = (...args) =>
    spawnSync(process.execPath, [gate, '--repo', dir, '--baseline', baselinePath, ...args], {
      encoding: 'utf8',
    });

  return {
    dir,
    base,
    git,
    write,
    baselinePath,
    writeBaseline,
    readBaseline: () => JSON.parse(readFileSync(baselinePath, 'utf8')),
    run,
    cleanup: () => rmSync(home, { recursive: true, force: true }),
  };
}

test('a COMMITTED classic edit fails --check even though the worktree is clean', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    f.git('commit', '-q', '-am', 'edit a frozen engine after the freeze');
    assert.equal(f.git('status', '--porcelain'), '', 'precondition: the worktree is clean');

    const result = f.run('--check');
    assert.equal(result.status, 1, result.stdout + result.stderr);
    assert.match(result.stdout, /UNAUTHORIZED frozen-engine change \[M\]/);
    assert.match(result.stdout, new RegExp(FROZEN_FILE.replace(/[/.]/g, '\\$&')));
    assert.match(result.stderr, /FAIL — 1 frozen-engine violation/);
  } finally {
    f.cleanup();
  }
});

test('an edit to a MODERN engine file is never a violation', () => {
  const f = fixture();
  try {
    f.write(MODERN_FILE, 'export const Box = () => "modern work is allowed";\n');
    f.git('commit', '-q', '-am', 'modern work');
    const result = f.run('--check');
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.match(result.stdout, /changed since base: 0/);
  } finally {
    f.cleanup();
  }
});

test('an UNTRACKED frozen file is a violation (a diff against a commit cannot see it)', () => {
  const f = fixture();
  try {
    f.write(OTHER_FROZEN_FILE, 'export const Flex = () => null;\n');
    const result = f.run('--check');
    assert.equal(result.status, 1, result.stdout + result.stderr);
    assert.match(result.stdout, /UNAUTHORIZED frozen-engine change \[A\][\s\S]*\(untracked\)/);
  } finally {
    f.cleanup();
  }
});

test('--authorize records a content pin, and the SAME file drifting later fails again', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "compile fix";\n');
    f.git('commit', '-q', '-am', 'shared-contract compile fix');
    assert.equal(f.run('--check').status, 1);

    const authorized = f.run(
      '--authorize',
      FROZEN_FILE,
      '--reason',
      'minimal shared-contract compile fix; the prop type moved in the DS contract',
    );
    assert.equal(authorized.status, 0, authorized.stdout + authorized.stderr);
    const baseline = f.readBaseline();
    assert.equal(
      baseline.entries[FROZEN_FILE].blob,
      sha256('export const Box = () => "compile fix";\n'),
    );
    assert.match(baseline.entries[FROZEN_FILE].reason, /compile fix/);
    assert.equal(f.run('--check').status, 0);

    // The exception covered ONE reviewed byte-state. A further edit is not covered.
    f.write(FROZEN_FILE, 'export const Box = () => "smuggled engine work";\n');
    const drifted = f.run('--check');
    assert.equal(drifted.status, 1, drifted.stdout);
    assert.match(drifted.stdout, /DRIFTED beyond its written exception/);
  } finally {
    f.cleanup();
  }
});

test('--authorize refuses a path that has not changed (no pre-authorizing a future edit)', () => {
  const f = fixture();
  try {
    const result = f.run('--authorize', FROZEN_FILE, '--reason', 'pre-authorize the next edit');
    assert.equal(result.status, 1);
    assert.match(result.stderr, /cannot be authorized before it changes/);
  } finally {
    f.cleanup();
  }
});

test('--authorize refuses a bare path with no written reason', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    const result = f.run('--authorize', FROZEN_FILE, '--reason', 'oops');
    assert.equal(result.status, 1);
    assert.match(result.stderr, /requires --reason/);
  } finally {
    f.cleanup();
  }
});

test('--authorize refuses a GENERATED file: an artifact never authorizes its source', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, '/* @generated — regenerate with build:vertical-css */\nexport const Box = () => null;\n');
    const result = f.run(
      '--authorize',
      FROZEN_FILE,
      '--reason',
      'the build regenerated this artifact under a frozen engine',
    );
    assert.equal(result.status, 1);
    assert.match(result.stderr, /never authorization to modify the source/);
    assert.deepEqual(f.readBaseline().entries, {});
  } finally {
    f.cleanup();
  }
});

test('--write is removed: the bulk snapshot that let a change grandfather itself is gone', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    const result = f.run('--write');
    assert.equal(result.status, 1);
    assert.match(result.stderr, /--write is removed/);
    assert.deepEqual(f.readBaseline().entries, {}, 'the baseline must not have been rewritten');
  } finally {
    f.cleanup();
  }
});

test('a baseRevision pointed ahead of history is rejected, so history cannot be erased', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    f.git('commit', '-q', '-am', 'frozen edit');
    const head = f.git('rev-parse', 'HEAD');
    // Re-pointing the base at the commit that made the change hides it entirely.
    // That is legal ONLY because this is fixture mode; production runs must match
    // the source-pinned SEALED_BASE, which this asserts is enforced elsewhere.
    f.writeBaseline({}, head);
    assert.equal(f.run('--check').status, 0, 'fixture mode allows any ancestor base');

    f.writeBaseline({}, '0123456789abcdef0123456789abcdef01234567');
    const missing = f.run('--check');
    assert.equal(missing.status, 1);
    assert.match(missing.stderr, /is not a commit/);
  } finally {
    f.cleanup();
  }
});

test('ENGINE_FREEZE_BASE may widen the window but never narrow it', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, 'export const Box = () => "edited";\n');
    f.git('commit', '-q', '-am', 'frozen edit');
    const head = f.git('rev-parse', 'HEAD');
    const narrowed = spawnSync(
      process.execPath,
      [gate, '--repo', f.dir, '--baseline', f.baselinePath, '--check'],
      { encoding: 'utf8', env: { ...process.env, ENGINE_FREEZE_BASE: head } },
    );
    assert.equal(narrowed.status, 1);
    assert.match(narrowed.stderr, /may only WIDEN the audit window/);
  } finally {
    f.cleanup();
  }
});

/* ------------------------------------------------------------------------ */
/* negative drill: an import-only exception never covers a functional edit   */
/* ------------------------------------------------------------------------ */

/**
 * Relocating a shared engine module into a `folder/index` unit rewrites one
 * import line in every frozen delegation stub that consumes it, which is how
 * ten Classic/Rustic stubs came to be re-authorized on 2026-07-26 with an
 * "only the module path moved" reason. The hazard that creates is a hole: if
 * an import-only exception quietly covered whatever the file becomes NEXT, a
 * real Classic/Rustic edit could ride in behind a relocation. These drills
 * prove it cannot — the content pin re-fails on the following edit even when
 * that edit changes no import whatsoever.
 */
const stub = (from, extraProp = '') =>
  [
    "'use client';",
    "import React from 'react';",
    `import { BoxEngine } from '${from}';`,
    'export default function ClassicBox(props) {',
    `  return <BoxEngine {...props}${extraProp} />;`,
    '}',
    '',
  ].join('\n');

/** Lines present in one revision and not the other, in both directions. */
function changedLines(before, after) {
  const a = before.split('\n');
  const b = after.split('\n');
  return [...a.filter((l) => !b.includes(l)), ...b.filter((l) => !a.includes(l))].filter((l) =>
    l.trim(),
  );
}

const isImportLine = (line) => /^\s*(import|export)\b.*\bfrom\b/.test(line);

test('negative drill: an import-only exception does NOT cover a later FUNCTIONAL edit', () => {
  const f = fixture();
  try {
    // The base commit holds the pre-relocation stub.
    f.write(FROZEN_FILE, stub('../shared'));
    f.git('commit', '-q', '-am', 'stub before the relocation');
    // Re-seal the fixture window on that state so only the relocation is in view.
    f.writeBaseline({}, f.git('rev-parse', 'HEAD'));

    // 1. The relocation: exactly one changed line, and it is an import.
    const relocated = stub('../foundation');
    const relocationDelta = changedLines(stub('../shared'), relocated);
    assert.equal(relocationDelta.length, 2, 'the relocation is one line replaced');
    assert.ok(
      relocationDelta.every(isImportLine),
      `the relocation must touch imports only, got: ${relocationDelta.join(' | ')}`,
    );
    f.write(FROZEN_FILE, relocated);
    assert.equal(f.run('--check').status, 1, 'precondition: the relocation itself is a violation');

    const authorized = f.run(
      '--authorize',
      FROZEN_FILE,
      '--reason',
      'structural relocation only: the shared engine module moved to folder/index; one import line, zero functional lines',
    );
    assert.equal(authorized.status, 0, authorized.stdout + authorized.stderr);
    assert.equal(f.run('--check').status, 0, 'the reviewed import-only byte-state is green');

    // 2. The smuggled functional edit: a render change that touches NO import.
    const functional = stub('../foundation', ' className="smuggled-classic-restyle"');
    const functionalDelta = changedLines(relocated, functional);
    assert.ok(functionalDelta.length > 0);
    assert.ok(
      functionalDelta.every((line) => !isImportLine(line)),
      `the drill must change no import, got: ${functionalDelta.join(' | ')}`,
    );
    f.write(FROZEN_FILE, functional);

    const red = f.run('--check');
    assert.equal(red.status, 1, `the gate must redden on a functional edit\n${red.stdout}`);
    assert.match(red.stdout, /DRIFTED beyond its written exception/);
    assert.match(red.stderr, /FAIL — 1 frozen-engine violation/);
  } finally {
    f.cleanup();
  }
});

test('negative drill: re-authorizing one stub does not bless a SECOND frozen file', () => {
  const f = fixture();
  try {
    f.write(FROZEN_FILE, stub('../shared'));
    f.git('commit', '-q', '-am', 'stub before the relocation');
    f.writeBaseline({}, f.git('rev-parse', 'HEAD'));

    f.write(FROZEN_FILE, stub('../foundation'));
    assert.equal(
      f.run('--authorize', FROZEN_FILE, '--reason', 'structural relocation only, one import line')
        .status,
      0,
    );
    assert.equal(f.run('--check').status, 0);

    // A sibling frozen file taking the SAME relocation is still unauthorized:
    // the exception is per-path, never a glob over the relocation.
    f.write(OTHER_FROZEN_FILE, stub('../foundation'));
    const red = f.run('--check');
    assert.equal(red.status, 1, red.stdout);
    assert.match(red.stdout, /UNAUTHORIZED frozen-engine change/);
  } finally {
    f.cleanup();
  }
});

test('coverage boundary: the shared module a frozen stub delegates to is NOT frozen', () => {
  // Recorded deliberately. `engines/foundation/index.tsx` (like the
  // `engines/shared.tsx` it replaced) sits outside the freeze regex, so a
  // functional edit there changes what Classic and Rustic render without this
  // gate seeing it. Anyone reasoning about "Classic is frozen" must read the
  // delegated module too — the pin covers the stub's bytes, not its behavior.
  assert.ok(FROZEN.test('packages/core/src/components/patterns/data/widget-board/engines/classic/index.tsx'));
  assert.ok(!FROZEN.test('packages/core/src/components/patterns/data/widget-board/engines/foundation/index.tsx'));
  assert.ok(!FROZEN.test('packages/core/src/components/patterns/data/widget-board/engines/shared.tsx'));
});

test('the real baseline is schema v3, pinned to the sealed base, and every entry carries a reason', () => {
  const baseline = JSON.parse(
    readFileSync(join(scriptDir, 'baseline/index.json'), 'utf8'),
  );
  assert.equal(baseline.schemaVersion, BASELINE_SCHEMA_VERSION);
  assert.match(baseline.baseRevision, /^[0-9a-f]{40}$/);
  const entries = Object.entries(baseline.entries);
  assert.ok(entries.length > 0);
  for (const [path, entry] of entries) {
    assert.ok(FROZEN.test(path), `${path} is not a frozen path`);
    assert.ok(
      entry.blob === null || /^[0-9a-f]{64}$/.test(entry.blob),
      `${path} has neither a content pin nor an explicit deletion pin`,
    );
    assert.ok(entry.reason.length >= 12, `${path} has no written reason`);
    // v3 adds the relocation pin. It is what lets a written exception survive
    // its file moving without being re-reviewed, so an entry without one is
    // half-migrated rather than merely older.
    assert.ok(
      entry.relocationDigest === null || /^[0-9a-f]{64}$/.test(entry.relocationDigest),
      `${path} has no relocation pin`,
    );
    assert.equal(
      entry.blob === null,
      entry.relocationDigest === null,
      `${path} pins one of the two digests and not the other`,
    );
  }
});

/* ------------------------------------------------------------------------ */
/* relocation identity, mis-keyed entries, obligations                       */
/* ------------------------------------------------------------------------ */

const OLD_FROZEN_FILE = 'packages/core/src/ui/primitives/layout/Box/engines/classic/index.tsx';

/**
 * Two moves in one window: a pair of byte-identical siblings, which is the
 * evidence the root substitution is DERIVED from, and the pair under test.
 * Without the proven siblings there is no substitution, and the subject reads
 * as two unrelated changes -- which is itself the correct behaviour and is
 * asserted separately below.
 */
const PROVEN_OLD = [
  'packages/core/src/ui/primitives/layout/Flex/engines/rustic/index.tsx',
  'packages/core/src/ui/primitives/layout/Stack/engines/rustic/index.tsx',
];
const PROVEN_NEW = [
  'packages/core/src/components/primitives/layout/flex/engines/rustic/index.tsx',
  'packages/core/src/components/primitives/layout/stack/engines/rustic/index.tsx',
];
const PROVEN_SOURCE = 'export const Proven = () => null;\n';

function relocationVerdict({ before, after, entries = {}, proven = true }) {
  const changes = [
    { status: 'D', path: OLD_FROZEN_FILE, untracked: false },
    { status: 'A', path: FROZEN_FILE, untracked: false },
  ];
  if (proven) {
    for (const path of PROVEN_OLD) changes.push({ status: 'D', path, untracked: false });
    for (const path of PROVEN_NEW) changes.push({ status: 'A', path, untracked: false });
  }
  const current = new Map([[FROZEN_FILE, after], ...PROVEN_NEW.map((path) => [path, PROVEN_SOURCE])]);
  const sealed = new Map([[OLD_FROZEN_FILE, before], ...PROVEN_OLD.map((path) => [path, PROVEN_SOURCE])]);
  return evaluateFreeze({
    changes,
    entries,
    read: (path) => current.get(path) ?? null,
    readBase: (path) => sealed.get(path) ?? null,
    tracked: new Set([FROZEN_FILE, ...PROVEN_NEW]),
  });
}

test('DRILL: a byte-identical move is ONE relocation and zero violations', () => {
  const source = 'export const Box = () => null;\n';
  const verdict = relocationVerdict({ before: source, after: source });
  const subject = verdict.relocations.find((pair) => pair.added === FROZEN_FILE);
  assert.ok(subject);
  assert.equal(subject.identity, 'byte-identical');
  assert.deepEqual(verdict.unauthorized, []);
  assert.deepEqual(verdict.drifted, []);
});

test('DRILL: a rename carrying a ONE-BYTE functional change still demands a written exception', () => {
  // The anti-laundering property. If a rename could absorb an edit, every
  // frozen-engine change would be one `git mv` away from invisible. The pairing
  // removes the DOUBLE COUNT, never the requirement.
  const verdict = relocationVerdict({
    before: 'export const Box = () => null;\n',
    after: 'export const Box = () => 1;\n',
  });
  const subject = verdict.relocationPairs.find((pair) => pair.added === FROZEN_FILE);
  assert.equal(subject.identity, 'content-changed');
  assert.equal(
    verdict.relocations.some((pair) => pair.added === FROZEN_FILE),
    false,
    'an edited file must not be resolved as a relocation',
  );
  assert.deepEqual(
    verdict.unauthorized.map((change) => change.path),
    [FROZEN_FILE],
    'the new path must still demand a written exception',
  );
});

test('DRILL: without a proven substitution a rename is two independent changes', () => {
  // The pairing is evidence-bound. With nothing in the window proving the root
  // moved, the gate refuses to guess: the deletion and the addition are two
  // changes, and both are reported.
  const verdict = relocationVerdict({
    before: 'export const Box = () => null;\n',
    after: 'export const Box = () => 1;\n',
    proven: false,
  });
  assert.deepEqual(verdict.substitutions, []);
  assert.deepEqual(
    verdict.unauthorized.map((change) => change.path).sort(),
    [FROZEN_FILE, OLD_FROZEN_FILE].sort(),
  );
});

test('DRILL: a move that only rewrites module specifiers and comments is mechanical', () => {
  const verdict = relocationVerdict({
    before: "import { Box } from '../../layout/Box';\n// old note\nexport const Box = () => null;\n",
    after: "import { Box } from '../../layout/box';\n// new note\nexport const Box = () => null;\n",
  });
  const subject = verdict.relocations.find((pair) => pair.added === FROZEN_FILE);
  assert.ok(subject, 'the specifier-and-comment-only move must resolve as a relocation');
  assert.equal(subject.identity, 'mechanical');
  assert.deepEqual(verdict.unauthorized, []);

  // The BINDING is not blanked: importing a different symbol is a real change.
  const bindingChanged = relocationVerdict({
    before: "import { Box } from '../../layout/Box';\nexport const Box = () => null;\n",
    after: "import { Flex } from '../../layout/box';\nexport const Box = () => null;\n",
  });
  assert.equal(
    bindingChanged.relocations.some((pair) => pair.added === FROZEN_FILE),
    false,
  );
  assert.deepEqual(bindingChanged.unauthorized.map((c) => c.path), [FROZEN_FILE]);
});

test('DRILL: a mis-keyed exception is a VIOLATION, and a case-only difference is mis-keyed', () => {
  // The defect that hid 43 written exceptions. `.../layout/Box/...` resolves to
  // `.../layout/box/...` on a case-insensitive filesystem, so `existsSync`
  // called it present while git had never contained it. Judged against the
  // index, the key authorizes nothing.
  const verdict = evaluateFreeze({
    changes: [{ status: 'M', path: FROZEN_FILE, untracked: false }],
    entries: {
      'packages/core/src/components/primitives/layout/BOX/engines/classic/index.tsx': {
        blob: sha256('x'),
        relocationDigest: relocationDigestOf('x', FROZEN_FILE),
        reason: 'a key git has never contained',
      },
    },
    read: () => 'x',
    tracked: new Set([FROZEN_FILE]),
  });
  assert.equal(verdict.misKeyed.length, 1);
  assert.match(verdict.misKeyed[0].reason, /not a tracked path/);
  assert.deepEqual(verdict.stale, [], 'a mis-keyed entry must not degrade to a stale note');
  assert.deepEqual(verdict.unauthorized.map((c) => c.path), [FROZEN_FILE]);
});

test('DRILL: an ambiguous canonical fold is reported, never silently resolved', () => {
  const tracked = new Set([
    'packages/core/src/components/primitives/layout/box/engines/classic/index.tsx',
    'packages/core/src/components/primitives/layout/b-ox/engines/classic/index.tsx',
  ]);
  const ambiguous = resolveMisKeyed(
    'packages/core/src/components/primitives/layout/BOX/engines/classic/index.tsx',
    tracked,
  );
  assert.equal(ambiguous.ambiguous, true);
  assert.equal(ambiguous.resolved, null);
  assert.equal(ambiguous.candidates.length, 2);

  const unique = resolveMisKeyed(
    'packages/core/src/components/primitives/layout/BOX/engines/classic/index.tsx',
    new Set(['packages/core/src/components/primitives/layout/box/engines/classic/index.tsx']),
  );
  assert.equal(unique.ambiguous, false);
  assert.equal(unique.resolved, 'packages/core/src/components/primitives/layout/box/engines/classic/index.tsx');
});

test('DRILL: a blob:null entry on a path that is not a deletion is mis-keyed', () => {
  const verdict = evaluateFreeze({
    changes: [{ status: 'M', path: FROZEN_FILE, untracked: false }],
    entries: {
      [FROZEN_FILE]: { blob: null, relocationDigest: null, reason: 'authorizes an absence' },
    },
    read: () => 'x',
    tracked: new Set([FROZEN_FILE]),
  });
  assert.equal(verdict.misKeyed.length, 1);
  assert.match(verdict.misKeyed[0].reason, /not a deletion in this window/);
});

test('DRILL: every stale and mis-keyed entry is emitted, never a truncated head', () => {
  // The report used to print `stale.slice(0, 20)`, which is how 43 findings
  // read as 20 and why nobody re-derived them.
  const entries = {};
  for (let index = 0; index < 25; index += 1) {
    entries[`packages/core/src/components/primitives/layout/box${index}/engines/classic/index.tsx`] = {
      blob: sha256('x'),
      relocationDigest: relocationDigestOf('x', FROZEN_FILE),
      reason: 'sealed at the freeze revision',
    };
  }
  const verdict = evaluateFreeze({
    changes: [],
    entries,
    read: () => 'x',
    tracked: new Set(Object.keys(entries)),
  });
  assert.equal(verdict.stale.length, 25);
  assert.equal(verdict.misKeyed.length, 0);
});

test('DRILL: substitutions are DERIVED from proven pairs, and a single pair mints nothing', () => {
  const proven = deriveRelocationSubstitutions([
    { deleted: 'a/ui/x/index.ts', added: 'a/components/x/index.ts' },
    { deleted: 'a/ui/y/index.ts', added: 'a/components/y/index.ts' },
    { deleted: 'a/ui/z/index.ts', added: 'a/elsewhere/z/index.ts' },
  ]);
  assert.deepEqual(
    proven.map(({ oldPrefix, newPrefix }) => [oldPrefix, newPrefix]),
    [['a/ui', 'a/components']],
    'a substitution seen once is a coincidence, not a proven relocation',
  );
});

test('DRILL: the obligation has three mechanical states and no override', () => {
  // Every REAL entry must be well formed. The roster is legitimately empty once
  // every obligation has been discharged, so the three-state law is drilled
  // against a synthetic entry rather than against whatever happens to be left.
  for (const entry of OBLIGATIONS) {
    for (const field of ['id', 'owner', 'phase', 'expires', 'assertion', 'symbolFile', 'symbol', 'why']) {
      assert.ok(entry[field], `obligation ${entry.id ?? '<unnamed>'} is missing "${field}"`);
    }
  }

  const obligation = Object.freeze({
    id: 'synthetic-three-state-probe',
    owner: 'DT / coordinator seat',
    phase: 'drill',
    expires: '2026-12-31',
    assertion: 'a synthetic symbol is exported from a synthetic file.',
    symbolFile: 'packages/core/src/synthetic/index.ts',
    symbol: 'SyntheticProbeSymbol',
    why: 'the three-state law must stay drilled after the roster empties.',
  });

  const pending = evaluateObligations([obligation], { readRepoFile: () => null, today: '2026-01-01' });
  assert.equal(pending[0].state, 'pending');
  assert.equal(pending[0].blocking, false);

  const expired = evaluateObligations([obligation], { readRepoFile: () => null, today: '2099-01-01' });
  assert.equal(expired[0].state, 'expired');
  assert.equal(expired[0].blocking, true);

  const satisfied = evaluateObligations([obligation], {
    readRepoFile: () => `export type ${obligation.symbol} = 'native';`,
    today: '2026-01-01',
  });
  assert.equal(satisfied[0].state, 'satisfied');
  assert.equal(satisfied[0].blocking, true, 'a satisfied obligation must be deleted, not carried');
});

test('DRILL: engine-posture-totality was migrated to the foundation owner, not dropped', () => {
  const repoRoot = join(scriptDir, '../../../../../../..');
  const readRepoFile = (relativePath) => {
    try {
      return readFileSync(join(repoRoot, relativePath), 'utf8');
    } catch {
      return null;
    }
  };

  // 1. it left the roster
  assert.ok(OBLIGATIONS.every((o) => o.id !== 'engine-posture-totality'));

  // 2. exactly one ledger row carries it, with the retired text intact
  const rows = DISCHARGED.filter((row) => row.id === 'engine-posture-totality');
  assert.equal(rows.length, 1);
  const [row] = rows;
  assert.match(row.assertion, /TOTAL posture record/);
  assert.equal(row.expires, '2026-12-31');
  assert.ok(row.why.length > 0);
  assert.ok(row.relocationReason.length > 0);

  // 3. the rejected path was never created
  assert.equal(readRepoFile(row.pinnedSymbolFile), null);

  // 4. the obligation's OWN regex, re-pointed at the successor owner
  assert.match(
    readRepoFile(row.successorSymbolFile) ?? '',
    new RegExp(`\\bexport\\b[^\\n]*\\b${row.symbol}\\b`),
  );

  // 5. every named successor assertion exists
  for (const path of row.successorAssertions) {
    assert.ok(readRepoFile(path) !== null, `successor assertion missing: ${path}`);
  }

  // 6. the successors are the files that carry the totality claim, not merely
  //    files that happen to exist
  assert.match(readRepoFile(row.successorAssertions[0]) ?? '', /TENANT_CAPABILITY_REGISTRY/);
  assert.match(readRepoFile(row.successorAssertions[1]) ?? '', /posture/);

  // 7. the ledger is EVALUATED, not merely stored: a vanished successor and a
  //    vanished successor assertion each produce exactly one blocking finding
  assert.deepEqual(evaluateDischarged(DISCHARGED, { readRepoFile }), []);

  const wrongSymbolFile = evaluateDischarged(
    [{ ...row, successorSymbolFile: 'packages/core/package.json' }],
    { readRepoFile },
  );
  assert.equal(wrongSymbolFile.length, 1);
  assert.equal(wrongSymbolFile[0].state, 'successor-missing');
  assert.equal(wrongSymbolFile[0].blocking, true);

  const missingAssertion = evaluateDischarged(
    [{ ...row, successorAssertions: ['packages/core/src/does-not-exist/index.ts'] }],
    { readRepoFile },
  );
  assert.equal(missingAssertion.length, 1);
  assert.equal(missingAssertion[0].state, 'successor-assertion-missing');
  assert.equal(missingAssertion[0].blocking, true);
});

test('the relocation normalizer keeps behaviour and drops only layout, comments and specifiers', () => {
  const path = 'packages/core/src/components/primitives/layout/box/engines/classic/index.tsx';
  assert.equal(relocationKey('a/b/index.tsx'), 'a/b.tsx');
  assert.equal(relocationKey('a/B_c/index.tsx'), 'a/bc.tsx');
  assert.match(blankModuleSpecifiers("from './x'", 'tsx'), /RELOCATED_SPECIFIER/);
  assert.equal(
    relocationNormalize("const a = 1;\n/* note */\nconst b = 'x';\n", path),
    relocationNormalize('const a = 1;   const b = "x";', path),
  );
  assert.notEqual(
    relocationNormalize('const a = 1;', path),
    relocationNormalize('const a = 2;', path),
    'a value change must survive normalization, or the ladder launders edits',
  );
});
