#!/usr/bin/env node
/**
 * engine-freeze-gate — Classic/Rustic are FROZEN (engine policy 2026-07-25,
 * independent code audit): implementation and visual-excellence effort is exclusively Modern.
 * Classic/Rustic are read-only except a minimal shared-contract compile fix.
 *
 * WHAT THIS GATE AUDITS
 * ---------------------
 * Every difference between the SEALED BASE REVISION and the current worktree
 * under `engines/classic/` or `engines/rustic/` — committed history included.
 * The base is a 40-character commit pinned in THIS FILE (`SEALED_BASE`), not in
 * data a change can rewrite: a contract lock belongs in source. It is the
 * PARENT of the commit that declared the freeze, so the freeze commit's own
 * frozen-engine edits are inside the audit window and had to be authorized by
 * name rather than snapshotted by the act of sealing.
 *
 * The previous revision of this gate read only `git status --porcelain`. That
 * made it a dirty-tree linter, not a freeze gate: committing a frozen-engine
 * edit removed it from the report forever, and its allowlist had been produced
 * by `--write` inside the very commit that made the edits (every allowlisted
 * path was modified by that commit). On a clean tree it printed 0 violations no
 * matter what history contained. Both holes are closed here.
 *
 * AUTHORIZATION MODEL (why self-grandfathering is no longer expressible)
 * ---------------------------------------------------------------------
 *   • There is no bulk snapshot mode. `--write` is gone. The only way a frozen
 *     path becomes allowed is `--authorize <path...> --reason "<text>"`, which
 *     names each path and demands a written reason — an act that shows up in the
 *     baseline diff as prose a reviewer reads, not as a silent path list that
 *     regenerated itself from whatever happened to be dirty.
 *   • Every entry is CONTENT-PINNED (sha256 of the authorized bytes). An entry
 *     authorizes exactly one reviewed byte-state; the next edit to that same
 *     file fails again until it is re-authorized. A path is never blessed
 *     forever.
 *   • The audit window cannot be moved by a change. `--check` refuses to run
 *     unless the baseline echoes `SEALED_BASE` exactly, so re-pointing the base
 *     at HEAD to erase history requires editing this source file.
 *   • `--authorize` refuses paths that are not actually changed against the base
 *     (no pre-authorizing a future edit) and refuses GENERATED paths outright:
 *     a build product is never evidence that its authored source may change.
 *
 * Usage:
 *   node scripts/check/engine/lifecycle/freeze/index.mjs            # print the report
 *   node scripts/check/engine/lifecycle/freeze/index.mjs --check    # exit 1 on any violation
 *   node scripts/check/engine/lifecycle/freeze/index.mjs --authorize <path...> --reason "<text>"
 *
 * `ENGINE_FREEZE_BASE` may WIDEN the audit window (it must be an ancestor of the
 * sealed base); it can never narrow it. `--repo`/`--baseline` exist for the
 * fixture-mode self-test only, mirroring container-query-gate.mjs.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { packageRoot as findPackageRoot, repoRoot as findRepoRoot } from '../../../../libraries/repo-root/index.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = findPackageRoot(scriptDir);

/**
 * Parent of 6ce8cd54 ("feat(design-system): advance modern platform quality
 * foundation"), the commit that declared the freeze policy. Sealing at the
 * parent — not at the freeze commit — is what forced that commit's own 61
 * frozen-engine paths through `--authorize` instead of letting them ride in as
 * "already in the base".
 */
export const SEALED_BASE = 'ef269d71db916d0063ea8a87b08240f8b13e99ca';

export const BASELINE_SCHEMA_VERSION = 3;

/** A path is frozen when it lives under a classic/rustic engine folder. The
 *  same law is restated in tenant-channel-consumer-gate.mjs (FROZEN_ENGINE_PATH);
 *  the two are asserted equal by engine-freeze-gate.test.mjs. */
export const FROZEN = /(^|\/)engines\/(classic|rustic)\//;

/** Build products. They are regenerated from an authored source, so they are
 *  never authorizable: allowlisting an artifact would launder an edit to the
 *  source it was generated from. Nothing under the frozen engines matches today
 *  — the predicate exists so that path stays closed. */
const GENERATED_PATH = /(^|\/)(facade\/artifacts|dist|node_modules|__generated__)\//;
const GENERATED_MARKER = /@generated|DO NOT EDIT|AUTO-?GENERATED|Generated by /i;

/* -------------------------------------------------------------------------- */
/* relocation identity                                                        */
/* -------------------------------------------------------------------------- */

/**
 * `--no-renames` is deliberate: a renamed frozen file is a deletion and an
 * addition, and both sides must be accounted for. But a repository-wide
 * reorganisation then reads as two violations per file, and 62% of this
 * window's rows are exactly that. A freeze gate that cannot survive a
 * relocation does not measure the freeze; it measures the tree layout.
 *
 * Identity is therefore resolved in two ordered passes, both of which leave the
 * anti-laundering property intact:
 *
 *   1. BYTE-IDENTICAL. A deletion and an addition with the same sha256 are one
 *      file that moved. Nothing can be laundered through this: the bytes are
 *      equal.
 *   2. RELOCATION KEY. The remaining deletions are matched to additions through
 *      a canonical key plus the root substitutions DERIVED from pass 1 — never
 *      a hardcoded historical fact and never a similarity heuristic. A pair
 *      found this way is still a CHANGE: it needs a written, content-pinned
 *      exception exactly as before. What the pairing removes is the double
 *      count, not the requirement.
 *
 * A paired change whose only difference is module specifiers, comments,
 * quoting or whitespace is mechanical relocation residue, not engine work: the
 * specifier is blanked rather than rewritten, so a changed import BINDING still
 * shows, and whether the specifier resolves is `import-binding-integrity`'s
 * question, which is a separate blocking gate.
 */
const RELOCATION_SPECIFIER = 'RELOCATED_SPECIFIER';

/** Canonical key: drop a trailing `/index.<ext>`, fold case and separators. */
export function relocationKey(path) {
  return path
    .replace(/\/index(\.[a-z]+)$/, '$1')
    .toLowerCase()
    .replace(/[^a-z0-9/.]/g, '');
}

export function stripComments(text, extension) {
  let out = text.replace(/\/\*[\s\S]*?\*\//g, ' ');
  if (extension !== 'css') out = out.replace(/(^|[^:"'`\\])\/\/[^\r\n]*/g, '$1');
  return out;
}

export function blankModuleSpecifiers(text, extension) {
  if (extension === 'css') {
    return text
      .replace(/@import\s+(['"])[^'"]*\1/g, `@import ${RELOCATION_SPECIFIER}`)
      .replace(/url\(\s*(['"]?)[^)'"]*\1\s*\)/g, `url(${RELOCATION_SPECIFIER})`);
  }
  return text
    .replace(/(\bfrom\s*)(['"])[^'"]*\2/g, `$1${RELOCATION_SPECIFIER}`)
    .replace(/(\bimport\s*)(['"])[^'"]*\2/g, `$1${RELOCATION_SPECIFIER}`)
    .replace(/(\brequire\s*\(\s*)(['"])[^'"]*\2(\s*\))/g, `$1${RELOCATION_SPECIFIER}$3`)
    .replace(/(\bimport\s*\(\s*)(['"])[^'"]*\2(\s*\))/g, `$1${RELOCATION_SPECIFIER}$3`);
}

/** The bytes a relocation may not change: everything but specifiers, comments and layout. */
export function relocationNormalize(text, path) {
  const extension = path.split('.').pop();
  let out = blankModuleSpecifiers(text, extension);
  out = stripComments(out, extension);
  out = out.replace(/['"]/g, '"');
  out = out.replace(/,(\s*[)\]}])/g, '$1');
  out = out.replace(/\s+/g, ' ');
  return out.trim();
}

export function relocationDigestOf(text, path) {
  return text === null ? null : sha256(relocationNormalize(text, path));
}

/**
 * Root substitutions the window itself proves. Each byte-identical pair states
 * one old-prefix/new-prefix substitution under the canonical key; only those
 * seen at least twice are adopted, so a single coincidental pair cannot mint a
 * rewrite rule. Longest prefix wins.
 */
export function deriveRelocationSubstitutions(byteIdenticalPairs) {
  const support = new Map();
  for (const { deleted, added } of byteIdenticalPairs) {
    const from = relocationKey(deleted).split('/');
    const to = relocationKey(added).split('/');
    let head = 0;
    while (head < from.length && head < to.length && from[head] === to[head]) head += 1;
    let tail = 0;
    while (
      tail < from.length - head
      && tail < to.length - head
      && from[from.length - 1 - tail] === to[to.length - 1 - tail]
    ) {
      tail += 1;
    }
    const oldPrefix = from.slice(0, from.length - tail).join('/');
    const newPrefix = to.slice(0, to.length - tail).join('/');
    if (oldPrefix === newPrefix) continue;
    const key = `${oldPrefix}\u0000${newPrefix}`;
    support.set(key, (support.get(key) ?? 0) + 1);
  }
  return [...support.entries()]
    .filter(([, count]) => count >= 2)
    .map(([key, count]) => {
      const [oldPrefix, newPrefix] = key.split('\u0000');
      return { oldPrefix, newPrefix, support: count };
    })
    .sort((left, right) => right.oldPrefix.length - left.oldPrefix.length);
}

function applySubstitutions(key, substitutions) {
  for (const { oldPrefix, newPrefix } of substitutions) {
    if (key === oldPrefix || key.startsWith(`${oldPrefix}/`)) {
      return newPrefix + key.slice(oldPrefix.length);
    }
  }
  return key;
}

/**
 * Pair every deletion with the addition that is the same file at a new path.
 * Returns the pairing plus the derived substitutions, so the report can state
 * on what evidence a relocation was recognised.
 */
export function resolveRelocations({ changes, readBase, readCurrent }) {
  const deletions = changes.filter((change) => change.status === 'D');
  const additions = changes.filter((change) => change.status === 'A');
  const deletedText = new Map();
  for (const change of deletions) deletedText.set(change.path, readBase(change.path));
  const addedText = new Map();
  for (const change of additions) addedText.set(change.path, readCurrent(change.path));

  const byDigest = new Map();
  for (const [path, text] of deletedText) {
    if (text === null) continue;
    const digest = sha256(text);
    if (!byDigest.has(digest)) byDigest.set(digest, []);
    byDigest.get(digest).push(path);
  }
  for (const bucket of byDigest.values()) bucket.sort();

  const pairs = [];
  const pairedOld = new Set();
  const pairedNew = new Set();
  for (const path of [...addedText.keys()].sort()) {
    const text = addedText.get(path);
    if (text === null) continue;
    const bucket = byDigest.get(sha256(text));
    if (!bucket || bucket.length === 0) continue;
    const deleted = bucket.shift();
    pairs.push({ deleted, added: path, identity: 'byte-identical' });
    pairedOld.add(deleted);
    pairedNew.add(path);
  }

  const substitutions = deriveRelocationSubstitutions(pairs);
  const remainingAdds = new Map();
  for (const path of [...addedText.keys()].sort()) {
    if (pairedNew.has(path)) continue;
    const key = relocationKey(path);
    if (!remainingAdds.has(key)) remainingAdds.set(key, []);
    remainingAdds.get(key).push(path);
  }
  for (const path of [...deletedText.keys()].sort()) {
    if (pairedOld.has(path)) continue;
    const key = applySubstitutions(relocationKey(path), substitutions);
    const bucket = remainingAdds.get(key);
    if (!bucket || bucket.length === 0) continue;
    const added = bucket.shift();
    const before = deletedText.get(path);
    const after = addedText.get(added);
    const mechanical =
      before !== null
      && after !== null
      && relocationNormalize(before, path) === relocationNormalize(after, added);
    pairs.push({ deleted: path, added, identity: mechanical ? 'mechanical' : 'content-changed' });
    pairedOld.add(path);
    pairedNew.add(added);
  }

  return { pairs, pairedOld, pairedNew, substitutions };
}

function argValue(flag, fallback) {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const REPO_OVERRIDE = argValue('--repo', null);
const repoRoot = REPO_OVERRIDE ? resolve(REPO_OVERRIDE) : findRepoRoot(scriptDir);
const BASELINE_PATH = resolve(
  argValue('--baseline', join(scriptDir, 'baseline/index.json')),
);
/** Fixture mode: a self-test repo has its own history and cannot contain the
 *  sealed base, so the source-pinned equality check is replaced by "the
 *  baseline's base must be a real ancestor of that repo's HEAD". Requires BOTH
 *  overrides, so no production invocation can slip into it. */
const FIXTURE_MODE = Boolean(REPO_OVERRIDE) && process.argv.includes('--baseline');

const MODE = process.argv.includes('--authorize')
  ? 'authorize'
  : process.argv.includes('--check')
    ? 'check'
    : process.argv.includes('--write')
      ? 'write'
      : 'report';

function git(args) {
  return execFileSync('git', ['-C', repoRoot, ...args], {
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  });
}

function gitOk(args) {
  try {
    git(args);
    return true;
  } catch {
    return false;
  }
}

export function sha256(text) {
  return createHash('sha256').update(text).digest('hex');
}

function toPosix(p) {
  return p.split(sep).join('/');
}

/* -------------------------------------------------------------------------- */
/* change collection                                                          */
/* -------------------------------------------------------------------------- */

/**
 * `git diff --name-status <base>` compares the base commit to the WORKTREE, so a
 * single call covers committed history, staged work and unstaged edits. Renames
 * are disabled: a renamed frozen file is two changes (a deletion and an
 * addition) and both sides must be authorized.
 */
export function parseNameStatus(text) {
  const rows = [];
  for (const line of text.split('\n')) {
    if (!line.trim()) continue;
    const [status, path] = line.split('\t');
    if (!path) continue;
    const clean = path.replace(/^"|"$/g, '');
    if (FROZEN.test(clean)) rows.push({ status: status.trim()[0], path: clean, untracked: false });
  }
  return rows;
}

/**
 * `git status --porcelain --untracked-files=all` supplies what a diff against a
 * commit cannot see: untracked files. (`-uall` matters — the default collapses a
 * brand-new directory to a single entry, which would hide every frozen file
 * inside it.)
 */
export function parsePorcelainUntracked(text) {
  const rows = [];
  for (const line of text.split('\n')) {
    if (!line.startsWith('?? ')) continue;
    const path = line.slice(3).replace(/^"|"$/g, '');
    if (FROZEN.test(path)) rows.push({ status: 'A', path, untracked: true });
  }
  return rows;
}

/** Union of the two collectors, deduplicated by path, sorted for stable output. */
export function mergeChangeSets(diffRows, untrackedRows) {
  const byPath = new Map();
  for (const row of [...diffRows, ...untrackedRows]) {
    if (!byPath.has(row.path)) byPath.set(row.path, row);
  }
  return [...byPath.values()].sort((a, b) => a.path.localeCompare(b.path));
}

/** `headText` is the first bytes of the file, or null when it no longer exists. */
export function isGeneratedPath(path, headText) {
  if (GENERATED_PATH.test(path)) return true;
  return typeof headText === 'string' && GENERATED_MARKER.test(headText);
}

/* -------------------------------------------------------------------------- */
/* evaluation                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Pure verdict. `entries` is the baseline map (path -> {blob, reason}); `read`
 * returns the current bytes of a path or null when it is gone.
 *
 *   relocation       — one file that moved. Byte-identical, or differing only in
 *                      module specifiers, comments and layout. Not a violation.
 *   unauthorized     — changed against the base with no allowlist entry
 *   drifted          — allowlisted, but the bytes are no longer the reviewed ones
 *   deletedAuthorized— a file pinned to authored bytes was later deleted without
 *                      re-authorizing that exact absence (`blob: null`)
 *   generated        — a build product changed under a frozen engine
 *   misKeyed         — an allowlist entry whose key is neither a tracked path nor
 *                      a deletion in this window. It authorizes NOTHING, and it
 *                      is a VIOLATION rather than a stale note: 43 written
 *                      exceptions went dark this way, under a green drill suite,
 *                      because a key that resolves on a case-insensitive
 *                      filesystem is invisible to `existsSync` and absent from
 *                      the change set git computes.
 *   stale            — an entry that no longer differs from the base
 *                      (tighten it out; never a failure)
 */
export function evaluateFreeze({ changes, entries, read, readBase = () => null, tracked = null }) {
  const unauthorized = [];
  const drifted = [];
  const deletedAuthorized = [];
  const generated = [];
  const misKeyed = [];
  const changedPaths = new Set(changes.map((c) => c.path));

  const { pairs, pairedOld, pairedNew, substitutions } = resolveRelocations({
    changes,
    readBase,
    readCurrent: read,
  });
  const relocationOf = new Map();
  for (const pair of pairs) {
    relocationOf.set(pair.deleted, pair);
    relocationOf.set(pair.added, pair);
  }
  const relocations = pairs.filter((pair) => pair.identity !== 'content-changed');
  const resolvedByRelocation = new Set();
  for (const pair of relocations) {
    resolvedByRelocation.add(pair.deleted);
    resolvedByRelocation.add(pair.added);
  }
  // A content-changed pair is ONE change, located at the new path. The deletion
  // side is the same file and is not a second, independent violation; the
  // addition side still needs its written, content-pinned exception.
  for (const pair of pairs) {
    if (pair.identity === 'content-changed') resolvedByRelocation.add(pair.deleted);
  }

  for (const change of changes) {
    if (resolvedByRelocation.has(change.path)) continue;
    const content = read(change.path);
    if (isGeneratedPath(change.path, content)) {
      generated.push(change);
      continue;
    }
    const entry = entries[change.path];
    if (!entry) {
      unauthorized.push(change);
      continue;
    }
    if (content === null) {
      if (entry.blob !== null) deletedAuthorized.push(change);
      continue;
    }
    if (sha256(content) === entry.blob) continue;
    // The pin may have been recorded before this file moved. A pin is satisfied
    // through the relocation ladder ONLY when the path really is the new side of
    // a pair in this window, so this is a relocation allowance and never a
    // general licence to reformat an authorized frozen file.
    const movedHere = pairedNew.has(change.path);
    if (
      movedHere
      && typeof entry.relocationDigest === 'string'
      && relocationDigestOf(content, change.path) === entry.relocationDigest
    ) {
      continue;
    }
    drifted.push({ ...change, authorizedBlob: entry.blob, actualBlob: sha256(content) });
  }

  const isResolvable = (path) => (tracked ? tracked.has(path) : true);
  const deletedInWindow = new Set(
    changes.filter((change) => change.status === 'D').map((change) => change.path),
  );
  const stale = [];
  for (const path of Object.keys(entries).sort()) {
    if (isResolvable(path) || deletedInWindow.has(path)) {
      if (!changedPaths.has(path)) stale.push(path);
      continue;
    }
    misKeyed.push({ path, reason: 'not a tracked path and not a deletion in this window' });
  }
  // A `blob: null` entry authorizes an ABSENCE, so it must name a real deletion.
  for (const [path, entry] of Object.entries(entries)) {
    if (entry.blob !== null) continue;
    if (deletedInWindow.has(path)) continue;
    if (misKeyed.some((finding) => finding.path === path)) continue;
    misKeyed.push({ path, reason: 'authorizes a deletion (blob: null) that is not a deletion in this window' });
  }

  return {
    unauthorized,
    drifted,
    deletedAuthorized,
    generated,
    misKeyed: misKeyed.sort((a, b) => a.path.localeCompare(b.path)),
    stale,
    relocations,
    relocationPairs: pairs,
    substitutions,
  };
}

/**
 * Advisory re-key resolution, for REPORTING only.
 *
 * A mis-keyed entry stays a violation (above). This resolves what it probably
 * meant, so the remediation is printed rather than guessed at, and it FAILS
 * LOUD when a fold is ambiguous: silently picking one of two tracked paths
 * would let a written exception migrate to the wrong file.
 */
export function resolveMisKeyed(path, tracked) {
  const fold = (value) => value.toLowerCase().replace(/[^a-z0-9/]/g, '');
  const wanted = fold(path);
  const candidates = [...tracked].filter((candidate) => fold(candidate) === wanted);
  if (candidates.length === 0) return { resolved: null, ambiguous: false };
  if (candidates.length > 1) return { resolved: null, ambiguous: true, candidates: candidates.sort() };
  return { resolved: candidates[0], ambiguous: false };
}

/* -------------------------------------------------------------------------- */
/* obligations                                                                */
/* -------------------------------------------------------------------------- */

/**
 * Contract locks the freeze gate cannot satisfy yet, pinned in SOURCE for the
 * same reason `SEALED_BASE` is: extending one has to be a reviewed source edit,
 * never a data edit a change can make about itself.
 *
 * An obligation has three mechanical states and no override flag:
 *   symbol absent, before expiry -> printed, non-blocking
 *   symbol absent, past expiry   -> hard failure
 *   symbol present               -> hard failure until the obligation is deleted
 *                                   in the same commit that satisfies it
 */
export const OBLIGATIONS = Object.freeze([
  Object.freeze({
    id: 'engine-posture-totality',
    owner: 'DT / coordinator seat',
    phase: 'C1 (contract freeze)',
    expires: '2026-12-31',
    assertion:
      'EnginePosture is exported from infrastructure/compilers/theme/presentation/engines/contract/, '
      + 'and classic/rustic/modern each declare a TOTAL posture record.',
    symbolFile: 'packages/core/src/infrastructure/compilers/theme/presentation/engines/contract/index.ts',
    symbol: 'EnginePosture',
    why:
      'This gate is a CONTENT freeze. It must not grow a posture checker it cannot satisfy, and the '
      + 'adapter posture policy cannot be resolved before C1 — so the obligation is recorded where it '
      + 'fails loud instead of being carried as prose.',
  }),
]);

export function evaluateObligations(obligations, { readRepoFile, today }) {
  const findings = [];
  for (const obligation of obligations) {
    const source = readRepoFile(obligation.symbolFile);
    const present =
      typeof source === 'string'
      && new RegExp(`\\bexport\\b[^\\n]*\\b${obligation.symbol}\\b`).test(source);
    const expired = today > obligation.expires;
    if (present) {
      findings.push({
        id: obligation.id,
        state: 'satisfied',
        blocking: true,
        message:
          `${obligation.id}: ${obligation.symbol} now exists. The obligation has been met and must be `
          + 'deleted in the same commit that met it; a stale obligation is a claim nobody re-reads.',
      });
      continue;
    }
    findings.push({
      id: obligation.id,
      state: expired ? 'expired' : 'pending',
      blocking: expired,
      message: expired
        ? `${obligation.id}: PAST DUE (expired ${obligation.expires}, owner ${obligation.owner}). ${obligation.assertion}`
        : `${obligation.id}: pending until ${obligation.expires} (owner ${obligation.owner}, phase ${obligation.phase}).`,
    });
  }
  return findings;
}

/* -------------------------------------------------------------------------- */
/* baseline + base revision                                                   */
/* -------------------------------------------------------------------------- */

function readBaseline() {
  if (!existsSync(BASELINE_PATH)) {
    fail(`baseline missing at ${BASELINE_PATH}`);
  }
  const parsed = JSON.parse(readFileSync(BASELINE_PATH, 'utf8'));
  if (parsed.schemaVersion !== BASELINE_SCHEMA_VERSION) {
    fail(
      `baseline schemaVersion must be ${BASELINE_SCHEMA_VERSION} (found ${parsed.schemaVersion ?? 'none'}). ` +
        'A v1 path-list baseline cannot express the content pin this gate requires.',
    );
  }
  if (!parsed.entries || typeof parsed.entries !== 'object') {
    fail('baseline must carry an `entries` object keyed by path');
  }
  return parsed;
}

function writeBaseline(baseline) {
  const entries = Object.fromEntries(
    Object.keys(baseline.entries)
      .sort()
      .map((path) => [path, baseline.entries[path]]),
  );
  const payload = {
    _comment:
      'Written exceptions to the Classic/Rustic engine freeze (policy 2026-07-25). Each entry ' +
      'authorizes ONE reviewed byte-state of ONE path: the next edit to an authorized file fails ' +
      'again until it is re-authorized. Entries are added only by ' +
      '`engine-freeze-gate.mjs --authorize <path> --reason "<text>"`; there is no bulk snapshot ' +
      'mode, and generated files are never authorizable.',
    policy:
      'Classic/Rustic are read-only; implementation effort is exclusively Modern. Every difference ' +
      'between baseRevision and the worktree under engines/classic or engines/rustic — committed ' +
      'history included — must be listed here with a matching content pin.',
    schemaVersion: BASELINE_SCHEMA_VERSION,
    baseRevision: baseline.baseRevision,
    entries,
  };
  writeFileSync(BASELINE_PATH, `${JSON.stringify(payload, null, 2)}\n`);
  return payload;
}

function fail(message) {
  console.error(`engine-freeze-gate: ${message}`);
  process.exit(1);
}

/**
 * The audit window. Order: the baseline's `baseRevision` (which must equal the
 * source-pinned SEALED_BASE outside fixture mode) and then an optional
 * ENGINE_FREEZE_BASE override that may only WIDEN it. Every candidate must be a
 * real commit and an ancestor of HEAD, so no run can point the window forward.
 */
export function resolveBase(baselineBase) {
  if (!/^[0-9a-f]{40}$/.test(baselineBase ?? '')) {
    fail('baseline.baseRevision must be a full 40-character commit');
  }
  if (!FIXTURE_MODE && baselineBase !== SEALED_BASE) {
    fail(
      `baseline.baseRevision ${baselineBase} does not equal the source-pinned SEALED_BASE ${SEALED_BASE}. ` +
        'The audit window is locked in engine-freeze-gate.mjs; moving it is a reviewed source edit, ' +
        'never a baseline edit.',
    );
  }
  if (!gitOk(['cat-file', '-e', `${baselineBase}^{commit}`])) {
    fail(`baseRevision ${baselineBase} is not a commit in ${repoRoot}`);
  }
  if (!gitOk(['merge-base', '--is-ancestor', baselineBase, 'HEAD'])) {
    fail(
      `baseRevision ${baselineBase} is not an ancestor of HEAD; the freeze window cannot start ahead of history`,
    );
  }
  const override = process.env.ENGINE_FREEZE_BASE?.trim();
  if (!override) return { base: baselineBase, widened: false };
  if (!gitOk(['cat-file', '-e', `${override}^{commit}`])) {
    fail(`ENGINE_FREEZE_BASE ${override} is not a commit in ${repoRoot}`);
  }
  if (!gitOk(['merge-base', '--is-ancestor', override, baselineBase])) {
    fail(
      `ENGINE_FREEZE_BASE ${override} is not an ancestor of the sealed base ${baselineBase}. ` +
        'The override may only WIDEN the audit window; narrowing it would hide frozen-engine history.',
    );
  }
  return { base: git(['rev-parse', override]).trim(), widened: true };
}

function collectChanges(base) {
  const diff = parseNameStatus(git(['diff', '--name-status', '--no-renames', base]));
  const untracked = parsePorcelainUntracked(git(['status', '--porcelain', '--untracked-files=all']));
  return mergeChangeSets(diff, untracked);
}

/**
 * Tracked paths under the frozen engines, plus the untracked ones the porcelain
 * collector found. PRESENCE MEANS TRACKED AT THIS EXACT PATH.
 *
 * `existsSync` answered "the OS found something close": on a case-insensitive
 * filesystem `.../display/Tag/...` resolves to `.../display/tag/...`, which is
 * how 43 written exceptions keyed at paths git has never contained looked
 * healthy on macOS and would have behaved differently on the runner.
 */
let trackedCache = null;
function trackedPaths() {
  if (trackedCache) return trackedCache;
  const NUL = String.fromCharCode(0);
  const listed = git(['ls-files', '-z']).split(NUL).filter(Boolean);
  trackedCache = new Set(listed);
  return trackedCache;
}

let presentCache = null;
function presentPaths(changes) {
  if (presentCache) return presentCache;
  presentCache = new Set(trackedPaths());
  for (const change of changes) if (change.untracked) presentCache.add(change.path);
  return presentCache;
}

function makeReadWorktree(changes) {
  const present = presentPaths(changes);
  return (relativePath) => {
    if (!present.has(relativePath)) return null;
    const full = join(repoRoot, relativePath);
    if (!existsSync(full)) return null;
    return readFileSync(full, 'utf8');
  };
}

/** The bytes a path carried in the sealed base, or null when it did not exist there. */
function makeReadBase(base) {
  return (relativePath) => {
    try {
      return git(['show', `${base}:${relativePath}`]);
    } catch {
      return null;
    }
  };
}

function readRepoFile(relativePath) {
  const full = join(repoRoot, relativePath);
  if (!existsSync(full)) return null;
  return readFileSync(full, 'utf8');
}

/* -------------------------------------------------------------------------- */
/* modes                                                                      */
/* -------------------------------------------------------------------------- */

function authorize(baseline, base, changes, readWorktree) {
  const reason = argValue('--reason', '').trim();
  if (reason.length < 12) {
    fail(
      '--authorize requires --reason "<why this frozen-engine edit is a minimal compile fix>" (12+ characters). ' +
        'The reason is the written exception a reviewer reads in the baseline diff.',
    );
  }
  if (process.env.ENGINE_FREEZE_BASE) {
    fail('--authorize refuses to run with ENGINE_FREEZE_BASE set; authorize against the sealed base only');
  }
  const flags = new Set(['--authorize', '--reason', '--repo', '--baseline', '--check', '--write']);
  const paths = [];
  for (let i = 2; i < process.argv.length; i += 1) {
    const token = process.argv[i];
    if (flags.has(token)) {
      if (token !== '--authorize') i += 1;
      continue;
    }
    paths.push(toPosix(token));
  }
  if (paths.length === 0) fail('--authorize needs at least one path');

  const changedByPath = new Map(changes.map((change) => [change.path, change]));
  const entries = { ...baseline.entries };
  for (const path of paths) {
    if (!FROZEN.test(path)) fail(`${path} is not under a frozen engine; nothing to authorize`);
    const change = changedByPath.get(path);
    if (!change) {
      fail(
        `${path} does not differ from ${base.slice(0, 8)}; a path cannot be authorized before it changes`,
      );
    }
    const content = readWorktree(path);
    if (isGeneratedPath(path, content)) {
      fail(
        `${path} is a generated file. A build product is never authorization to modify the source it ` +
          'came from; authorize the authored source and regenerate.',
      );
    }
    entries[path] = {
      blob: content === null ? null : sha256(content),
      // The same reviewed bytes under the relocation ladder, so a later move of
      // THIS path can be recognised as the same file without re-review. It is
      // consulted only when the path is the new side of a relocation pair.
      relocationDigest: relocationDigestOf(content, path),
      reason,
      authorizedAgainst: base,
    };
  }
  const payload = writeBaseline({ ...baseline, entries });
  console.log(
    `engine-freeze-gate: authorized ${paths.length} path(s); baseline now holds ${Object.keys(payload.entries).length} written exception(s)`,
  );
}

function main() {
  if (MODE === 'write') {
    fail(
      '--write is removed. It regenerated the allowlist from whatever happened to be dirty, which let a ' +
        'change grandfather itself. Use: --authorize <path...> --reason "<text>".',
    );
  }

  const baseline = readBaseline();
  const { base, widened } = resolveBase(baseline.baseRevision);
  const changes = collectChanges(base);

  const readWorktree = makeReadWorktree(changes);
  const readBase = makeReadBase(base);

  if (MODE === 'authorize') {
    authorize(baseline, base, changes, readWorktree);
    return;
  }

  const verdict = evaluateFreeze({
    changes,
    entries: baseline.entries,
    read: readWorktree,
    readBase,
    tracked: presentPaths(changes),
  });
  const { unauthorized, drifted, deletedAuthorized, generated, misKeyed, stale, relocations, substitutions } =
    verdict;
  const obligationFindings = evaluateObligations(OBLIGATIONS, {
    readRepoFile,
    today: new Date().toISOString().slice(0, 10),
  });
  const blockingObligations = obligationFindings.filter((finding) => finding.blocking);
  const violations =
    unauthorized.length
    + drifted.length
    + deletedAuthorized.length
    + generated.length
    + misKeyed.length
    + blockingObligations.length;

  console.log(
    'engine-freeze-gate — frozen dirs: engines/classic, engines/rustic | ' +
      `base: ${base.slice(0, 8)}${widened ? ' (WIDENED by ENGINE_FREEZE_BASE)' : ''} | ` +
      `changed since base: ${changes.length} | written exceptions: ${Object.keys(baseline.entries).length} | ` +
      `relocations: ${relocations.length} | violations: ${violations} | ` +
      `stale exceptions: ${stale.length} | mis-keyed: ${misKeyed.length}`,
  );
  for (const { oldPrefix, newPrefix, support } of substitutions) {
    console.log(`  relocation substitution proven by ${support} byte-identical pair(s): ${oldPrefix} -> ${newPrefix}`);
  }

  for (const change of unauthorized) {
    console.log(
      `  UNAUTHORIZED frozen-engine change [${change.status}] ${change.path}\n` +
        `    differs from the sealed base ${base.slice(0, 8)}${change.untracked ? ' (untracked)' : ''}.\n` +
        '    Classic/Rustic are read-only. If this is a minimal shared-contract compile fix, record a\n' +
        '    written exception:\n' +
        `      node scripts/check/engine/lifecycle/freeze/index.mjs --authorize ${change.path} --reason "<why>"`,
    );
  }
  for (const change of drifted) {
    console.log(
      `  DRIFTED beyond its written exception ${change.path}\n` +
        `    authorized bytes ${change.authorizedBlob.slice(0, 12)}, current bytes ${change.actualBlob.slice(0, 12)}.\n` +
        '    An exception authorizes ONE reviewed byte-state. Revert the new edit, or re-authorize it\n' +
        '    with a reason that covers what changed.',
    );
  }
  for (const change of deletedAuthorized) {
    console.log(
      `  DELETED frozen-engine file ${change.path}\n` +
        '    Deleting a frozen-engine file is also a change; re-authorize it if the deletion is intentional.',
    );
  }
  for (const change of generated) {
    console.log(
      `  GENERATED file changed under a frozen engine ${change.path}\n` +
        '    Build products are not authorizable: regenerate it from an authored source that is itself\n' +
        '    authorized, rather than editing the artifact.',
    );
  }
  for (const finding of misKeyed) {
    const resolution = resolveMisKeyed(finding.path, presentPaths(changes));
    const remedy = resolution.ambiguous
      ? `    the canonical fold matches MORE THAN ONE tracked path (${resolution.candidates.join(', ')});\n` +
        '    resolve it by hand — picking one would migrate a written exception to the wrong file.'
      : resolution.resolved
        ? `    RE-KEY REQUIRED: ${finding.path} -> ${resolution.resolved}`
        : '    no tracked path resolves this key; the exception authorizes nothing.';
    console.log(
      `  MIS-KEYED written exception ${finding.path}\n` +
        `    ${finding.reason}.\n` +
        `${remedy}`,
    );
  }
  // Every stale and mis-keyed entry, never a truncated head: a gate that
  // truncates the list of its own broken authorizations cannot be audited, and
  // the previous `slice(0, 20)` is why 43 findings read as 20.
  for (const path of stale) {
    console.log(`  STALE exception (no longer differs from base; tighten it out) ${path}`);
  }
  for (const finding of obligationFindings) {
    console.log(`  OBLIGATION ${finding.state.toUpperCase()} — ${finding.message}`);
  }

  if (MODE === 'check' && violations > 0) {
    console.error(`engine-freeze-gate: FAIL — ${violations} frozen-engine violation(s)`);
    process.exit(1);
  }
  console.log('engine-freeze-gate: OK');
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) main();
