/**
 * @fileoverview Type definitions for the FilterBuilder pattern component.
 * Models a composable filter tree inspired by Airtable's filter UI:
 *
 * - **FilterRule** -- leaf node representing a single field/operator/value condition.
 * - **FilterGroup** -- branch node that combines child rules and/or nested groups
 *   with AND/OR logic.
 * - **FilterFieldDefinition** -- schema for each filterable field (type, allowed
 *   operators, select options).
 * - **FilterBuilderProps** -- top-level component props controlling the tree value,
 *   nesting depth, and UI labels.
 *
 * Also exports type guards (`isFilterGroup`, `isFilterRule`), the operator
 * registry (`OPERATOR_DEFINITIONS`), per-type operator defaults, and helper
 * utilities (`getOperatorsForField`, `generateFilterId`).
 */

import type { ReactNode } from 'react';
import type { PatternBaseProps } from '../types';

/**
 * Union of all comparison operators available for filter rules.
 *
 * The operators are deliberately generic and field-type-agnostic at this level.
 * `DEFAULT_OPERATORS_BY_TYPE` narrows which operators are valid for each
 * `FilterFieldType`, and individual fields can further restrict the set via
 * `FilterFieldDefinition.operators`.
 */
export type FilterOperator =
  | 'equals'
  | 'notEquals'
  | 'contains'
  | 'notContains'
  | 'startsWith'
  | 'endsWith'
  | 'gt'
  | 'gte'
  | 'lt'
  | 'lte'
  | 'between'
  | 'in'
  | 'notIn'
  | 'isEmpty'
  | 'isNotEmpty';

/**
 * A single filter condition (leaf node in the filter tree).
 *
 * Each rule targets one field, applies one operator, and holds the comparison
 * value. Rules are always contained within a `FilterGroup`.
 */
export interface FilterRule {
  /** Unique identifier for this rule, generated by `generateFilterId()`. */
  id: string;

  /** Key of the field being filtered, matching `FilterFieldDefinition.key`. */
  field: string;

  /** Comparison operator to apply. */
  operator: FilterOperator;

  /**
   * The comparison value. Type depends on the field type and operator:
   * - `string` for text operators
   * - `number` for numeric operators
   * - `[min, max]` tuple for `between`
   * - `string[]` for `in` / `notIn`
   * - `undefined` for `isEmpty` / `isNotEmpty` (value is ignored)
   *
   * Typed as `any` because the concrete type varies by field; runtime
   * validation happens in the component.
   */
  value: any;
}

/**
 * A logical grouping of filter rules and/or nested groups (branch node).
 *
 * Groups combine their children with either AND or OR logic. Nesting groups
 * inside groups allows arbitrarily complex filter expressions, bounded by
 * `FilterBuilderProps.maxDepth`.
 */
export interface FilterGroup {
  /** Unique identifier for this group, generated by `generateFilterId()`. */
  id: string;

  /** Logical combinator applied between all children of this group. */
  logic: 'and' | 'or';

  /**
   * Child nodes -- a mix of individual rules and nested groups.
   * Use `isFilterGroup` / `isFilterRule` type guards to discriminate.
   */
  rules: (FilterRule | FilterGroup)[];
}

/**
 * Type guard to check if a filter tree node is a `FilterGroup` (branch node).
 *
 * @param node - A node from the filter tree.
 * @returns `true` if the node has `logic` and `rules` properties.
 */
export function isFilterGroup(
  node: FilterRule | FilterGroup
): node is FilterGroup {
  return 'logic' in node && 'rules' in node;
}

/**
 * Type guard to check if a filter tree node is a `FilterRule` (leaf node).
 *
 * @param node - A node from the filter tree.
 * @returns `true` if the node has `field` and `operator` properties.
 */
export function isFilterRule(
  node: FilterRule | FilterGroup
): node is FilterRule {
  return 'field' in node && 'operator' in node;
}

/**
 * Supported field types for the filter builder. The field type determines
 * which operators are available by default (via `DEFAULT_OPERATORS_BY_TYPE`)
 * and which value input widget the component renders.
 *
 * - `"text"` -- free-form string input
 * - `"number"` -- numeric input with min/max support
 * - `"date"` -- date picker
 * - `"select"` -- single-value dropdown (requires `options`)
 * - `"multiSelect"` -- multi-value dropdown (requires `options`)
 * - `"boolean"` -- true/false toggle
 */
export type FilterFieldType =
  | 'text'
  | 'number'
  | 'date'
  | 'select'
  | 'multiSelect'
  | 'boolean';

/**
 * Schema for a single filterable field. Each definition tells the
 * FilterBuilder what kind of input to render, which operators to offer,
 * and how to label the field in the UI.
 */
export interface FilterFieldDefinition {
  /** Unique key matching the data property this field filters on. */
  key: string;

  /** Human-readable label shown in the field selector dropdown. */
  label: string;

  /**
   * Field type that determines the default set of available operators and
   * the value input widget (text input, number input, date picker, etc.).
   */
  type: FilterFieldType;

  /**
   * Explicit list of operators allowed for this field. When provided, this
   * overrides the defaults from `DEFAULT_OPERATORS_BY_TYPE[type]`. Useful
   * for restricting operators on specific fields (e.g. disallowing
   * `contains` on an ID field).
   */
  operators?: FilterOperator[];

  /**
   * Dropdown options for `"select"` and `"multiSelect"` field types.
   * Ignored for other field types.
   */
  options?: { label: string; value: any }[];

  /** Custom icon rendered beside the field name in the field selector. */
  icon?: ReactNode;

  /** Placeholder text for the value input. */
  placeholder?: string;
}

/**
 * Metadata for a single operator, used to render operator dropdowns and
 * to determine whether a value input should be shown.
 */
export interface OperatorDefinition {
  /** The operator key matching a `FilterOperator` value. */
  key: FilterOperator;

  /** Human-readable label shown in the operator dropdown (e.g. "contains"). */
  label: string;

  /**
   * Whether this operator requires a value input. Operators like `isEmpty`
   * and `isNotEmpty` do not require a value.
   */
  requiresValue: boolean;

  /**
   * Whether this operator requires two values (min and max). Only `true`
   * for the `"between"` operator, which renders a range input.
   */
  requiresRange: boolean;
}

/**
 * Registry of all supported operators with their display labels and
 * input requirements. Used as the source of truth when rendering operator
 * dropdowns and determining value input visibility.
 */
export const OPERATOR_DEFINITIONS: OperatorDefinition[] = [
  { key: 'equals', label: 'equals', requiresValue: true, requiresRange: false },
  { key: 'notEquals', label: 'does not equal', requiresValue: true, requiresRange: false },
  { key: 'contains', label: 'contains', requiresValue: true, requiresRange: false },
  { key: 'notContains', label: 'does not contain', requiresValue: true, requiresRange: false },
  { key: 'startsWith', label: 'starts with', requiresValue: true, requiresRange: false },
  { key: 'endsWith', label: 'ends with', requiresValue: true, requiresRange: false },
  { key: 'gt', label: 'greater than', requiresValue: true, requiresRange: false },
  { key: 'gte', label: 'greater or equal', requiresValue: true, requiresRange: false },
  { key: 'lt', label: 'less than', requiresValue: true, requiresRange: false },
  { key: 'lte', label: 'less or equal', requiresValue: true, requiresRange: false },
  { key: 'between', label: 'is between', requiresValue: true, requiresRange: true },
  { key: 'in', label: 'is any of', requiresValue: true, requiresRange: false },
  { key: 'notIn', label: 'is none of', requiresValue: true, requiresRange: false },
  { key: 'isEmpty', label: 'is empty', requiresValue: false, requiresRange: false },
  { key: 'isNotEmpty', label: 'is not empty', requiresValue: false, requiresRange: false },
];

/**
 * Default operator sets for each field type. When a `FilterFieldDefinition`
 * does not specify custom `operators`, this map is used to determine which
 * operators appear in the dropdown.
 *
 * - `text` fields get string-oriented operators (contains, startsWith, etc.)
 * - `number` fields get comparison operators (gt, gte, lt, lte, between)
 * - `date` fields get a subset of comparison operators
 * - `select` fields get equality and set-membership operators
 * - `multiSelect` fields only get set-membership operators
 * - `boolean` fields only get equality operators
 */
export const DEFAULT_OPERATORS_BY_TYPE: Record<FilterFieldType, FilterOperator[]> = {
  text: ['equals', 'notEquals', 'contains', 'notContains', 'startsWith', 'endsWith', 'isEmpty', 'isNotEmpty'],
  number: ['equals', 'notEquals', 'gt', 'gte', 'lt', 'lte', 'between', 'isEmpty', 'isNotEmpty'],
  date: ['equals', 'notEquals', 'gt', 'lt', 'between', 'isEmpty', 'isNotEmpty'],
  select: ['equals', 'notEquals', 'in', 'notIn', 'isEmpty', 'isNotEmpty'],
  multiSelect: ['in', 'notIn', 'isEmpty', 'isNotEmpty'],
  boolean: ['equals', 'notEquals'],
};

/**
 * Returns the list of `OperatorDefinition` objects available for a given
 * field. Checks the field's custom `operators` array first, then falls back
 * to `DEFAULT_OPERATORS_BY_TYPE`.
 *
 * @param field - The field definition to get operators for.
 * @returns Filtered array of operator definitions.
 */
export function getOperatorsForField(field: FilterFieldDefinition): OperatorDefinition[] {
  const allowedKeys = field.operators ?? DEFAULT_OPERATORS_BY_TYPE[field.type];
  return OPERATOR_DEFINITIONS.filter((op) => allowedKeys.includes(op.key));
}

/**
 * Generates a unique string ID for new filter rules and groups.
 * Uses a timestamp + random suffix to avoid collisions without requiring
 * an external UUID library.
 *
 * @returns A unique string in the format `"f-{timestamp}-{random}"`.
 */
export function generateFilterId(): string {
  return `f-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Props for the FilterBuilder pattern component.
 *
 * FilterBuilder provides a visual query builder for constructing complex
 * filter expressions. The user adds rules and groups, selects fields and
 * operators, and enters comparison values. The resulting `FilterGroup` tree
 * is emitted via `onChange` for the parent to apply to data queries.
 *
 * @example
 * ```tsx
 * <PatternFilterBuilder
 *   fields={[
 *     { key: 'name', label: 'Name', type: 'text' },
 *     { key: 'status', label: 'Status', type: 'select', options: statusOptions },
 *     { key: 'amount', label: 'Amount', type: 'number' },
 *     { key: 'createdAt', label: 'Created', type: 'date' },
 *   ]}
 *   value={filterGroup}
 *   onChange={setFilterGroup}
 *   maxDepth={2}
 *   showClear
 *   onClear={() => setFilterGroup(emptyGroup)}
 * />
 * ```
 */
export interface FilterBuilderProps extends PatternBaseProps {
  /** Array of field definitions describing what can be filtered and how. */
  fields: FilterFieldDefinition[];

  /**
   * The current filter tree value (controlled). Always a `FilterGroup` at the
   * root level, containing rules and/or nested groups.
   */
  value: FilterGroup;

  /**
   * Called whenever the filter tree changes (rule added/removed, operator
   * changed, value updated, group logic toggled, etc.).
   *
   * @param value - The updated root `FilterGroup`.
   */
  onChange: (value: FilterGroup) => void;

  /**
   * Maximum allowed nesting depth for filter groups. Prevents users from
   * creating excessively complex filter trees.
   * @default 3
   */
  maxDepth?: number;

  /**
   * Whether to allow creating nested groups (AND/OR sub-groups). When false,
   * only flat rule lists within the root group are allowed.
   * @default true
   */
  allowGrouping?: boolean;

  /** Label text for the "Add rule" button. @default "Add rule" */
  addRuleLabel?: string;

  /** Label text for the "Add group" button. @default "Add group" */
  addGroupLabel?: string;

  /**
   * Whether to show a "Clear all" button that resets the entire filter tree.
   * @default false
   */
  showClear?: boolean;

  /** Label text for the clear button. @default "Clear all" */
  clearLabel?: string;

  /**
   * Called when the clear button is clicked. The parent should reset the
   * `value` to an empty `FilterGroup`.
   */
  onClear?: () => void;

  /**
   * Compact mode reduces padding, font sizes, and spacing for denser UIs
   * like sidebars and narrow panels.
   * @default false
   */
  compact?: boolean;
}
