/**
 * @fileoverview Static tenant config loader from `/.designsystem/tenants/<slug>/config.json`.
 * @description Useful for deployments that publish tenant payloads as versioned
 * static assets, or local demos that do not want to run an API. Configs are
 * validated against the tenant schema before use.
 */

import type { TenantConfig } from '../../../../contracts';
import { isValidTenantConfig } from '../../../schema';

// WHY this specific path: the `/.designsystem/` convention keeps tenant
// artifacts alongside other DS build outputs (token CSS, icon sprites) in
// a single well-known directory that can be served as static assets from
// any CDN or `public/` folder.
const STATIC_PATH = '/.designsystem/tenants';

/**
 * Loads a tenant config JSON payload from the static tenant directory and
 * validates it against the tenant schema before returning.
 *
 * Expected file path: `/.designsystem/tenants/<slug>/config.json`.
 *
 * This is step 4 in the storage facade's resolution chain -- used for
 * deployments that publish tenant payloads as versioned static assets
 * rather than serving them from a live API. Common in preview deploys,
 * edge-cached sites, and local development without the platform backend.
 *
 * @param slug - Tenant identifier (e.g. `'acme'`).
 * @returns A validated TenantConfig.
 * @throws If the file is not found or the payload fails schema validation.
 */
export async function loadStaticTenantConfig(slug: string): Promise<TenantConfig> {
  const url = `${STATIC_PATH}/${slug}/config.json`;

  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Static config not found for tenant: ${slug}`);
  }

  const config = await response.json();

  // Same validation as the remote fetcher -- static files can drift out of
  // date if they were generated by an older version of the build tooling.
  if (!isValidTenantConfig(config)) {
    throw new Error(`Invalid tenant config for: ${slug}`);
  }

  return config;
}
