/**
 * bh-ranking-board - Showcase Mock Data
 *
 * Mock/demo data for storybook, playground, and development preview.
 * NOT used in production - import from here for showcase/demo purposes only.
 */

import type { RankedCandidate, ScoreDistribution, RankingFilters } from '../core';

export const DEFAULT_CANDIDATES: RankedCandidate[] = [
  {
    id: 'c-1',
    rank: 1,
    name: 'Sarah Johnson',
    avatar: 'https://i.pravatar.cc/150?u=sarah-johnson',
    overallScore: 92,
    stageScores: [
      { stage: 'Technical', score: 95 },
      { stage: 'Culture', score: 88 },
      { stage: 'Leadership', score: 93 },
    ],
    completionPercent: 100,
    hasKnockout: false,
    decisionStatus: 'pending',
    strengths: ['Deep React expertise', 'Google experience'],
    weaknesses: ['Limited backend'],
    confidence: 0.94,
    evidenceCount: 18,
    tier: 'A',
    tierColor: '#16a34a',
    scoreLevel: 'exceptional',
    weightedScore: 91.8,
    dimensionCount: 3,
    knockoutDimensions: [],
    scoredAt: '2026-02-10T14:30:00Z',
    scoredBy: 'AI Scoring Engine v3.2',
    recommendations: ['Fast-track to final round', 'Consider for team lead role'],
  },
  {
    id: 'c-2',
    rank: 2,
    name: 'Michael Chen',
    avatar: 'https://i.pravatar.cc/150?u=michael-chen',
    overallScore: 88,
    stageScores: [
      { stage: 'Technical', score: 90 },
      { stage: 'Culture', score: 91 },
      { stage: 'Leadership', score: 83 },
    ],
    completionPercent: 100,
    hasKnockout: false,
    decisionStatus: 'advanced',
    strengths: ['Full-stack', 'Strong system design'],
    weaknesses: ['Short tenure at previous roles'],
    confidence: 0.89,
    evidenceCount: 15,
    tier: 'A',
    tierColor: '#16a34a',
    scoreLevel: 'strong',
    weightedScore: 88.2,
    dimensionCount: 3,
    knockoutDimensions: [],
    scoredAt: '2026-02-10T14:32:00Z',
    scoredBy: 'AI Scoring Engine v3.2',
    recommendations: ['Schedule final interview', 'Pair with technical mentor'],
  },
  {
    id: 'c-3',
    rank: 3,
    name: 'Emily Rodriguez',
    avatar: 'https://i.pravatar.cc/150?u=emily-rodriguez',
    overallScore: 85,
    stageScores: [
      { stage: 'Technical', score: 88 },
      { stage: 'Culture', score: 80 },
      { stage: 'Leadership', score: 87 },
    ],
    completionPercent: 90,
    hasKnockout: false,
    decisionStatus: 'pending',
    strengths: ['Staff-level at Meta', 'Architecture expertise'],
    weaknesses: ['Salary expectations above budget'],
    confidence: 0.86,
    evidenceCount: 12,
    tier: 'B+',
    tierColor: '#2563eb',
    scoreLevel: 'strong',
    weightedScore: 85.4,
    dimensionCount: 3,
    knockoutDimensions: [],
    scoredAt: '2026-02-10T14:35:00Z',
    scoredBy: 'AI Scoring Engine v3.2',
    recommendations: ['Negotiate compensation package', 'Highlight growth trajectory'],
  },
  {
    id: 'c-4',
    rank: 4,
    name: 'James Kim',
    avatar: 'https://i.pravatar.cc/150?u=james-kim',
    overallScore: 72,
    stageScores: [
      { stage: 'Technical', score: 78 },
      { stage: 'Culture', score: 70 },
      { stage: 'Leadership', score: 68 },
    ],
    completionPercent: 85,
    hasKnockout: true,
    decisionStatus: 'hold',
    strengths: ['ML background', 'Strong analytical skills'],
    weaknesses: ['Knockout on culture fit', 'Junior leadership level'],
    confidence: 0.72,
    evidenceCount: 9,
    tier: 'C',
    tierColor: '#d97706',
    scoreLevel: 'moderate',
    weightedScore: 71.6,
    dimensionCount: 3,
    knockoutDimensions: ['Culture'],
    scoredAt: '2026-02-10T14:38:00Z',
    scoredBy: 'AI Scoring Engine v3.2',
    recommendations: ['Re-evaluate culture fit with second panel', 'Consider for ML-specific role'],
  },
  {
    id: 'c-5',
    rank: 5,
    name: 'Anna Kowalski',
    avatar: 'https://i.pravatar.cc/150?u=anna-kowalski',
    overallScore: 68,
    stageScores: [
      { stage: 'Technical', score: 72 },
      { stage: 'Culture', score: 65 },
      { stage: 'Leadership', score: 67 },
    ],
    completionPercent: 75,
    hasKnockout: false,
    decisionStatus: 'rejected',
    strengths: ['DevOps skills', 'CI/CD pipeline expertise'],
    weaknesses: ['Below score threshold', 'Limited frontend experience'],
    confidence: 0.65,
    evidenceCount: 7,
    tier: 'D',
    tierColor: '#dc2626',
    scoreLevel: 'below-average',
    weightedScore: 67.8,
    dimensionCount: 3,
    knockoutDimensions: [],
    scoredAt: '2026-02-10T14:40:00Z',
    scoredBy: 'AI Scoring Engine v3.2',
    recommendations: ['Archive for future DevOps openings'],
  },
];

export const DEFAULT_DISTRIBUTION: ScoreDistribution[] = [
  { score: 60, count: 1 },
  { score: 65, count: 2 },
  { score: 70, count: 3 },
  { score: 75, count: 5 },
  { score: 80, count: 4 },
  { score: 85, count: 6 },
  { score: 90, count: 3 },
  { score: 95, count: 2 },
];

export const MOCK_FILTERS: RankingFilters = {
  stages: ['Technical', 'Culture', 'Leadership'],
  knockoutOnly: false,
  decisionStatus: ['pending', 'advanced', 'hold'],
  searchQuery: '',
};

export const MOCK_FILTERS_KNOCKOUT_ONLY: RankingFilters = {
  stages: ['Technical', 'Culture', 'Leadership'],
  knockoutOnly: true,
  decisionStatus: ['hold'],
  searchQuery: '',
};

export const MOCK_FILTERS_WITH_SEARCH: RankingFilters = {
  stages: ['Technical'],
  knockoutOnly: false,
  decisionStatus: ['pending', 'advanced'],
  searchQuery: 'Sarah',
};
