/**
 * Types for `@rottay/design-system/tenant-theme-canary-fixtures` — the
 * published tenant-theme canary specimens.
 *
 * The artifact is generated by `pnpm tenant-theme-fixtures:generate` from the
 * authored TypeScript fixtures and kept honest by
 * `pnpm tenant-theme-fixtures:check`. Do not hand-edit either file.
 *
 * WHAT THIS IS FOR. An application proving a two-tenant canary needs the exact
 * customer document the design system sanctions. Without a published artifact
 * its only options are copying the specimen by hand — which silently fabricates
 * evidence as soon as the source moves — or reaching across the workspace into
 * the design-system checkout, which couples the consumer's CI to a sibling
 * repository. This subpath exists so neither is necessary.
 *
 * WHAT THIS IS NOT. Not a runtime tenant. These specimens are never registered
 * as known tenants, never compiled into a shipped bundle, and never a second
 * source of identity. They are canary material, and they must stay explicit.
 *
 * The two halves are kept separate exactly as the database stores them: the
 * JSONB payload a customer writes, and the trusted identity columns the read
 * path supplies. Joining them is the reader's job.
 */

/** Trusted row columns supplied by the read path, never customer-writable. */
export interface TenantThemeCanaryIdentity {
  tenantId: string;
  slug: string;
  verticalKey: string;
  rowVersion: number;
}

export interface TenantThemeCanarySpecimen {
  /** Package-relative path of the authored fixture this specimen came from. */
  source: string;
  /** The JSONB payload exactly as persisted in the tenant theme row. */
  document: Record<string, unknown>;
  identity: TenantThemeCanaryIdentity;
}

export interface TenantThemeCanaryFixtures {
  $comment: string;
  /** The tenant-theme document schema version these specimens are authored at. */
  schemaVersion: number;
  specimens: Record<string, TenantThemeCanarySpecimen>;
}

declare const fixtures: TenantThemeCanaryFixtures;
export default fixtures;
