/**
 * @fileoverview GENERATED -- do not edit. The foundation's own `--ds-color-*`
 * declarations, so the compiler can resolve a reference the cascade resolves.
 *
 * Source: `src/foundation/tokens/css/foundation/themes/default/index.css`
 * Regenerate: `node scripts/generate/tokens/foundation-defaults/index.mjs`
 *
 * The admission contrast floor measures the COMPILED variable map. Since the
 * neutral doctrine moved every chromatic default into the stylesheet, a pair
 * whose ink resolves through one of these channels is invisible to that map --
 * so the floor refused by form instead of by ratio. These are the same bytes
 * the runtime loads, projected, never a second hand-written table.
 *
 * @module Foundation/Tokens/Base/DeclaredDefaults
 * @category Foundation
 * @package @rottay/design-system
 */

/** The colour closure the foundation declares in its light (`:root`) scope. */
export const FOUNDATION_COLOR_DEFAULTS_LIGHT: Readonly<Record<string, string>> =
  Object.freeze({
  "--ds-color-accent": "var(--ds-color-secondary)",
  "--ds-color-accent-hover": "var(--ds-color-secondary-hover)",
  "--ds-color-accent-live": "var(--ds-color-success)",
  "--ds-color-alpha-black-10": "rgba(0, 0, 0, 0.1)",
  "--ds-color-alpha-black-100": "color-mix( in srgb, var(--ds-color-text-primary) 20%, transparent )",
  "--ds-color-alpha-black-20": "rgba(0, 0, 0, 0.2)",
  "--ds-color-alpha-black-30": "rgba(0, 0, 0, 0.3)",
  "--ds-color-alpha-black-40": "rgba(0, 0, 0, 0.4)",
  "--ds-color-alpha-black-5": "rgba(0, 0, 0, 0.05)",
  "--ds-color-alpha-black-50": "rgba(0, 0, 0, 0.5)",
  "--ds-color-alpha-black-60": "rgba(0, 0, 0, 0.6)",
  "--ds-color-alpha-black-70": "rgba(0, 0, 0, 0.7)",
  "--ds-color-alpha-black-80": "rgba(0, 0, 0, 0.8)",
  "--ds-color-alpha-black-90": "rgba(0, 0, 0, 0.9)",
  "--ds-color-alpha-error-10": "rgba(239, 68, 68, 0.10)",
  "--ds-color-alpha-error-20": "rgba(239, 68, 68, 0.20)",
  "--ds-color-alpha-info-10": "rgba(59, 130, 246, 0.10)",
  "--ds-color-alpha-primary-10": "rgba(var(--ds-color-primary-rgb), 0.10)",
  "--ds-color-alpha-primary-20": "rgba(var(--ds-color-primary-rgb), 0.20)",
  "--ds-color-alpha-secondary-10": "rgba(var(--ds-color-secondary-rgb), 0.10)",
  "--ds-color-alpha-secondary-20": "rgba(var(--ds-color-secondary-rgb), 0.20)",
  "--ds-color-alpha-success-10": "rgba(34, 197, 94, 0.10)",
  "--ds-color-alpha-success-20": "rgba(34, 197, 94, 0.20)",
  "--ds-color-alpha-warning-10": "rgba(245, 158, 11, 0.10)",
  "--ds-color-alpha-warning-20": "rgba(245, 158, 11, 0.20)",
  "--ds-color-alpha-white-10": "rgba(255, 255, 255, 0.1)",
  "--ds-color-alpha-white-20": "rgba(255, 255, 255, 0.2)",
  "--ds-color-alpha-white-30": "rgba(255, 255, 255, 0.3)",
  "--ds-color-alpha-white-40": "rgba(255, 255, 255, 0.4)",
  "--ds-color-alpha-white-5": "rgba(255, 255, 255, 0.05)",
  "--ds-color-alpha-white-50": "rgba(255, 255, 255, 0.5)",
  "--ds-color-alpha-white-60": "rgba(255, 255, 255, 0.6)",
  "--ds-color-alpha-white-70": "rgba(255, 255, 255, 0.7)",
  "--ds-color-alpha-white-80": "rgba(255, 255, 255, 0.8)",
  "--ds-color-alpha-white-90": "rgba(255, 255, 255, 0.9)",
  "--ds-color-background": "var(--ds-color-bg-primary)",
  "--ds-color-bg": "var(--ds-color-bg-primary)",
  "--ds-color-bg-canvas": "var(--ds-color-bg-primary)",
  "--ds-color-bg-elevated": "var(--ds-color-neutral-0)",
  "--ds-color-bg-hover": "var(--ds-color-neutral-100)",
  "--ds-color-bg-info": "var(--ds-color-info-50)",
  "--ds-color-bg-input": "var(--ds-color-neutral-0)",
  "--ds-color-bg-overlay": "var(--ds-color-alpha-black-50)",
  "--ds-color-bg-primary": "var(--ds-color-neutral-50)",
  "--ds-color-bg-secondary": "var(--ds-color-neutral-100)",
  "--ds-color-bg-subtle": "var(--ds-color-bg-secondary, #0D0D10)",
  "--ds-color-bg-surface": "var(--ds-color-bg-secondary)",
  "--ds-color-bg-tertiary": "var(--ds-color-neutral-200)",
  "--ds-color-black": "#000000",
  "--ds-color-border": "var(--ds-color-neutral-200)",
  "--ds-color-border-focus": "var(--ds-color-primary)",
  "--ds-color-border-primary": "var(--ds-color-neutral-200)",
  "--ds-color-border-secondary": "var(--ds-color-neutral-300)",
  "--ds-color-border-subtle": "var(--ds-color-neutral-100)",
  "--ds-color-border-tertiary": "var(--ds-color-neutral-100)",
  "--ds-color-danger": "var(--ds-color-error)",
  "--ds-color-error": "var(--ds-color-error-400)",
  "--ds-color-error-100": "#fee2e2",
  "--ds-color-error-200": "#fecaca",
  "--ds-color-error-300": "#fca5a5",
  "--ds-color-error-400": "#f87171",
  "--ds-color-error-50": "#fef2f2",
  "--ds-color-error-500": "#ef4444",
  "--ds-color-error-600": "#dc2626",
  "--ds-color-error-700": "#b91c1c",
  "--ds-color-error-800": "#991b1b",
  "--ds-color-error-900": "#7f1d1d",
  "--ds-color-error-bg": "var(--ds-color-error-50)",
  "--ds-color-error-border": "rgba(239, 68, 68, 0.2)",
  "--ds-color-error-ink": "color-mix(in srgb, var(--ds-color-error) 78%, var(--ds-color-neutral-900) 22%)",
  "--ds-color-info": "var(--ds-color-info-400)",
  "--ds-color-info-100": "#dbeafe",
  "--ds-color-info-200": "#bfdbfe",
  "--ds-color-info-300": "#93c5fd",
  "--ds-color-info-400": "#60a5fa",
  "--ds-color-info-50": "#eff6ff",
  "--ds-color-info-500": "#3b82f6",
  "--ds-color-info-600": "#2563eb",
  "--ds-color-info-700": "#1d4ed8",
  "--ds-color-info-800": "#1e40af",
  "--ds-color-info-900": "#1e3a8a",
  "--ds-color-info-bg": "var(--ds-color-info-50)",
  "--ds-color-info-border": "rgba(59, 130, 246, 0.2)",
  "--ds-color-info-ink": "var(--ds-color-info)",
  "--ds-color-interactive-bg-active": "var(--ds-color-alpha-primary-10)",
  "--ds-color-interactive-bg-hover": "var(--ds-color-bg-hover)",
  "--ds-color-link": "var(--ds-color-primary)",
  "--ds-color-link-hover": "var(--ds-color-primary-hover)",
  "--ds-color-link-visited": "var(--ds-color-neutral-600)",
  "--ds-color-neutral-0": "var(--ds-color-white)",
  "--ds-color-neutral-100": "#f5f5f5",
  "--ds-color-neutral-200": "#e5e5e5",
  "--ds-color-neutral-300": "#d4d4d4",
  "--ds-color-neutral-400": "#a3a3a3",
  "--ds-color-neutral-50": "#fafafa",
  "--ds-color-neutral-500": "#737373",
  "--ds-color-neutral-600": "#525252",
  "--ds-color-neutral-700": "#404040",
  "--ds-color-neutral-800": "#262626",
  "--ds-color-neutral-900": "#171717",
  "--ds-color-on-error": "#171717",
  "--ds-color-on-info": "#171717",
  "--ds-color-on-primary": "var(--ds-color-text-on-primary)",
  "--ds-color-on-success": "#171717",
  "--ds-color-on-warning": "#171717",
  "--ds-color-primary": "#171717",
  "--ds-color-primary-100": "#f5f5f5",
  "--ds-color-primary-200": "#e5e5e5",
  "--ds-color-primary-300": "#d4d4d4",
  "--ds-color-primary-400": "#a3a3a3",
  "--ds-color-primary-50": "#fafafa",
  "--ds-color-primary-500": "#171717",
  "--ds-color-primary-600": "#0a0a0a",
  "--ds-color-primary-700": "#000000",
  "--ds-color-primary-800": "#000000",
  "--ds-color-primary-900": "#000000",
  "--ds-color-primary-foreground": "#ffffff",
  "--ds-color-primary-hover": "var(--ds-color-primary-600)",
  "--ds-color-primary-rgb": "23, 23, 23",
  "--ds-color-primary-subtle": "var(--ds-color-primary-100)",
  "--ds-color-secondary": "var(--ds-color-secondary-500)",
  "--ds-color-secondary-100": "#f9f7f4",
  "--ds-color-secondary-200": "#f3efe8",
  "--ds-color-secondary-300": "#e8e2d9",
  "--ds-color-secondary-400": "#d4ccc0",
  "--ds-color-secondary-50": "#fdfcfb",
  "--ds-color-secondary-500": "#b8a898",
  "--ds-color-secondary-600": "#9a8a7a",
  "--ds-color-secondary-700": "#7a6a5a",
  "--ds-color-secondary-800": "#5a4a3a",
  "--ds-color-secondary-900": "#3a2a1a",
  "--ds-color-secondary-hover": "var(--ds-color-secondary-600)",
  "--ds-color-secondary-rgb": "184, 168, 152",
  "--ds-color-shadow": "var(--ds-color-alpha-black-20)",
  "--ds-color-success": "var(--ds-color-success-600)",
  "--ds-color-success-100": "#dcfce7",
  "--ds-color-success-200": "#bbf7d0",
  "--ds-color-success-300": "#86efac",
  "--ds-color-success-400": "#4ade80",
  "--ds-color-success-50": "#f0fdf4",
  "--ds-color-success-500": "#22c55e",
  "--ds-color-success-600": "#16a34a",
  "--ds-color-success-700": "#15803d",
  "--ds-color-success-800": "#166534",
  "--ds-color-success-900": "#14532d",
  "--ds-color-success-bg": "var(--ds-color-success-50)",
  "--ds-color-success-border": "rgba(34, 197, 94, 0.2)",
  "--ds-color-success-ink": "color-mix(in srgb, var(--ds-color-success) 60%, var(--ds-color-neutral-900) 40%)",
  "--ds-color-surface": "var(--ds-color-bg-primary)",
  "--ds-color-surface-secondary": "var(--ds-color-bg-secondary)",
  "--ds-color-surface-subtle": "var(--ds-surface-panel-bg)",
  "--ds-color-text": "var(--ds-color-text-primary)",
  "--ds-color-text-disabled": "#4A4A50",
  "--ds-color-text-inverse": "var(--ds-color-text-on-primary)",
  "--ds-color-text-muted": "#96969E",
  "--ds-color-text-on-primary": "#0C0C0E",
  "--ds-color-text-primary": "var(--ds-color-neutral-900)",
  "--ds-color-text-secondary": "#A0A0A5",
  "--ds-color-text-subtle": "var(--ds-color-text-muted)",
  "--ds-color-text-tertiary": "#9A9AA2",
  "--ds-color-warning": "var(--ds-color-warning-600)",
  "--ds-color-warning-100": "#fef3c7",
  "--ds-color-warning-200": "#fde68a",
  "--ds-color-warning-300": "#fcd34d",
  "--ds-color-warning-400": "#fbbf24",
  "--ds-color-warning-50": "#fffbeb",
  "--ds-color-warning-500": "#f59e0b",
  "--ds-color-warning-600": "#d97706",
  "--ds-color-warning-700": "#b45309",
  "--ds-color-warning-800": "#92400e",
  "--ds-color-warning-900": "#78350f",
  "--ds-color-warning-bg": "var(--ds-color-warning-50)",
  "--ds-color-warning-border": "rgba(245, 158, 11, 0.2)",
  "--ds-color-warning-ink": "color-mix(in srgb, var(--ds-color-warning) 55%, var(--ds-color-neutral-900) 45%)",
  "--ds-color-white": "#ffffff",
  });

/** Only what the dark scope RESTATES; everything else keeps its light value. */
export const FOUNDATION_COLOR_DEFAULTS_DARK_DELTA: Readonly<
  Record<string, string>
> = Object.freeze({
  "--ds-color-bg-canvas": "#0A0A0C",
  "--ds-color-bg-elevated": "#182235",
  "--ds-color-bg-hover": "#18181C",
  "--ds-color-bg-input": "#0F0F12",
  "--ds-color-bg-overlay": "rgba(2, 6, 23, 0.88)",
  "--ds-color-bg-tertiary": "#172033",
  "--ds-color-border": "#1C1C20",
  "--ds-color-border-focus": "var(--ds-color-primary-400)",
  "--ds-color-border-primary": "var(--ds-color-neutral-300)",
  "--ds-color-border-secondary": "#1e293b",
  "--ds-color-border-subtle": "#161619",
  "--ds-color-border-tertiary": "#161619",
  "--ds-color-link": "var(--ds-color-primary-400)",
  "--ds-color-link-hover": "var(--ds-color-primary-300)",
  "--ds-color-neutral-0": "#020617",
  "--ds-color-neutral-100": "#111827",
  "--ds-color-neutral-200": "#1f2937",
  "--ds-color-neutral-300": "#334155",
  "--ds-color-neutral-400": "#475569",
  "--ds-color-neutral-50": "#0b1220",
  "--ds-color-neutral-500": "#64748b",
  "--ds-color-neutral-600": "#94a3b8",
  "--ds-color-neutral-700": "#cbd5e1",
  "--ds-color-neutral-800": "#e2e8f0",
  "--ds-color-neutral-900": "#f8fafc",
  "--ds-color-surface": "#101826",
  "--ds-color-surface-muted": "#152033",
  "--ds-color-text-inverse": "var(--ds-color-neutral-0)",
  "--ds-color-text-muted": "var(--ds-color-neutral-600)",
  "--ds-color-text-on-primary": "#ffffff",
  "--ds-color-text-primary": "#f3f4f6",
  "--ds-color-text-secondary": "var(--ds-color-neutral-700)",
  "--ds-color-text-tertiary": "var(--ds-color-neutral-600)",
  });

/** The effective declaration set per mode, composed the way the cascade does. */
export const FOUNDATION_COLOR_DEFAULTS: Readonly<
  Record<"light" | "dark", Readonly<Record<string, string>>>
> = Object.freeze({
  light: FOUNDATION_COLOR_DEFAULTS_LIGHT,
  dark: Object.freeze({
    ...FOUNDATION_COLOR_DEFAULTS_LIGHT,
    ...FOUNDATION_COLOR_DEFAULTS_DARK_DELTA,
  }),
});
