/** Supplier-neutral, non-React expressive-effect governance kernel. */
export {
  EFFECT_DEFINITIONS,
  EFFECT_REGISTRY,
  EFFECT_REGISTRY_VERSION,
  EFFECT_RESEARCH_PROVENANCE,
  getEffectDefinition,
  isEffectDefinition,
  isEffectId,
  resolveEffect,
} from '../../../infrastructure/runtime/effects';
export { EFFECT_IDS } from '../../../foundation/contracts/runtime/effects';
export type {
  EffectAdmission,
  EffectAriaStrategy,
  EffectBudget,
  EffectDefinition,
  EffectEngine,
  EffectFallbackDefinition,
  EffectId,
  EffectLoop,
  EffectObservedRuntime,
  EffectProvenance,
  EffectPurpose,
  EffectRenderer,
  EffectResolution,
  EffectResolutionTelemetryEvent,
  EffectResolutionMode,
  EffectResolutionReason,
  EffectRuntimeContext,
  EffectRuntimeTelemetryEvent,
  EffectRuntimeTelemetryListener,
  EffectTelemetryState,
  EffectTier,
  EffectTransitionTelemetryEvent,
  EffectVertical,
  MeasuredEffectBudget,
  ReferencedEffectProvenance,
  UnmeasuredEffectBudget,
  VerifiedEffectProvenance,
} from '../../../foundation/contracts/runtime/effects';
