#!/usr/bin/env node
/**
 * Publish the tenant-theme canary specimens as a consumable package artifact.
 *
 * The sanctioned The Management row lives in the source tree as a TypeScript
 * fixture, which no consumer can reach: it is not on an exported subpath and it
 * is not emitted into `dist`. Applications that need to prove a two-tenant
 * canary therefore had only bad options — copy the specimen by hand, or reach
 * across the workspace into this repository. The first fabricates evidence the
 * moment the source moves; the second makes the consumer's CI depend on a
 * sibling checkout.
 *
 * This generator removes both. It evaluates the authored fixture and writes a
 * flat JSON artifact at the package root, published through the
 * `./tenant-theme-canary-fixtures` subpath — the same shape and lifecycle as
 * `hooks-manifest.json`. The TypeScript fixture stays the single source of
 * truth; the JSON is a build product and must never be hand-edited.
 *
 * Usage:
 *   node scripts/packaging/tenant-theme-canary-fixtures/index.mjs --write   # regenerate
 *   node scripts/packaging/tenant-theme-canary-fixtures/index.mjs --check   # fail on drift
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";
import { packageRoot as findPackageRoot } from '../../lib/repo-root/index.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = findPackageRoot(HERE);
const ARTIFACT_PATH = join(PACKAGE_ROOT, "tenant-theme-canary-fixtures.json");

const CONTRACT_ROOT = join(
  PACKAGE_ROOT,
  "src/foundation/contracts/composition/tenants/themes/tenant-theme",
);

/**
 * Specimens published to consumers.
 *
 * A specimen is admitted only when it is authored FORWARD in the document's own
 * vocabulary — the payload a customer actually writes — because a specimen
 * projected from a code-owned BrandTheme would prove the compiler is
 * deterministic and nothing about what a customer can express.
 */
const SPECIMENS = [
  {
    key: "themanagement",
    source: join(CONTRACT_ROOT, "fixtures/themanagement-db-row/index.ts"),
    documentExport: "THEMANAGEMENT_TENANT_THEME_DOCUMENT",
    identityExport: "THEMANAGEMENT_TENANT_THEME_IDENTITY",
  },
];

/** The schema-version constant the fixtures import from the contract root. */
function readSchemaVersion() {
  const rootSource = readFileSync(join(CONTRACT_ROOT, "index.ts"), "utf8");
  const direct = rootSource.match(
    /export const TENANT_THEME_SCHEMA_VERSION\s*=\s*(\d+)/,
  );
  if (direct) return Number(direct[1]);
  // The constant may live in a submodule and arrive at the root through an
  // import/re-export hop; follow whichever line names it with a `from`.
  const hop = rootSource.match(
    /(?:import|export)[^;]*TENANT_THEME_SCHEMA_VERSION[^;]*from\s+["']([^"']+)["']/s,
  );
  if (hop) {
    const target = join(CONTRACT_ROOT, hop[1], "index.ts");
    const moduleSource = readFileSync(target, "utf8");
    const nested = moduleSource.match(
      /export const TENANT_THEME_SCHEMA_VERSION\s*=\s*(\d+)/,
    );
    if (nested) return Number(nested[1]);
  }
  throw new Error(
    "Could not read TENANT_THEME_SCHEMA_VERSION from the tenant-theme contract root.",
  );
}

/**
 * Evaluate a fixture module without resolving the package's own import graph.
 *
 * Only two things cross the fixture's module boundary: erased type imports and
 * the schema-version constant. Both are substituted, so the authored literal is
 * evaluated exactly as written rather than re-typed here.
 */
function evaluateFixture(path, schemaVersion) {
  const source = readFileSync(path, "utf8")
    .replace(/import\s+type\s+\{[\s\S]*?\}\s+from\s+'[^']*';/g, "")
    .replace(
      /import\s+\{\s*TENANT_THEME_SCHEMA_VERSION\s*\}\s+from\s+'[^']*';/g,
      "",
    )
    .replace(/\bTENANT_THEME_SCHEMA_VERSION\b/g, String(schemaVersion));

  const { outputText } = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2020,
    },
  });

  const exported = {};
  new Function("exports", outputText)(exported);
  return exported;
}

function buildArtifact() {
  const schemaVersion = readSchemaVersion();
  const specimens = {};

  for (const specimen of SPECIMENS) {
    const exported = evaluateFixture(specimen.source, schemaVersion);
    const document = exported[specimen.documentExport];
    const identity = exported[specimen.identityExport];

    if (!document || !identity) {
      throw new Error(
        `Fixture ${specimen.source} did not export ${specimen.documentExport} and ${specimen.identityExport}.`,
      );
    }

    specimens[specimen.key] = {
      source: specimen.source.slice(PACKAGE_ROOT.length + 1),
      document,
      identity,
    };
  }

  return {
    $comment:
      "Generated by `pnpm tenant-theme-fixtures:generate` from the authored TypeScript fixtures. Do not hand-edit. Each specimen is the JSONB payload a customer writes plus the trusted identity columns the read path supplies; joining them is the reader's job.",
    schemaVersion,
    specimens,
  };
}

function main() {
  const check = process.argv.includes("--check");
  const write = process.argv.includes("--write");

  if (check === write) {
    console.error("Pass exactly one of --check or --write.");
    process.exit(2);
  }

  const artifact = `${JSON.stringify(buildArtifact(), null, 2)}\n`;

  if (write) {
    writeFileSync(ARTIFACT_PATH, artifact);
    console.log(`tenant-theme-canary-fixtures.json written (${artifact.length} bytes).`);
    return;
  }

  let current;
  try {
    current = readFileSync(ARTIFACT_PATH, "utf8");
  } catch {
    console.error(
      "tenant-theme-canary-fixtures.json is missing. Run `pnpm tenant-theme-fixtures:generate`.",
    );
    process.exit(1);
  }

  if (current !== artifact) {
    console.error(
      "tenant-theme-canary-fixtures.json is stale or hand-edited. Run `pnpm tenant-theme-fixtures:generate`.",
    );
    process.exit(1);
  }

  console.log("tenant-theme-canary-fixtures.json matches the authored fixtures.");
}

main();
