'use client';

/**
 * @fileoverview ChartScaffold -- shared wrapper for all D3-backed charts.
 * Standardises lifecycle states (ready/loading/empty/error), title/subtitle
 * rendering, ARIA metadata (role, roledescription, keyboard navigation), and
 * an accessible textual summary table that is visually hidden but
 * screen-reader readable.
 *
 * Three distinct feedback semantics coexist and must not be conflated:
 *
 * 1. `state='loading' | 'empty' | 'error'` -- caller-declared lifecycle
 *    states. Non-ready states never mount the plot, so a chart can never show
 *    stale or blank marks beneath feedback copy. Empty/error copy is
 *    typed-required per state; the design system hardcodes no locale.
 * 2. Automatic zero-data empty -- resolved by {@link resolveChartScaffoldState}
 *    in family shells, and ONLY when the application supplied `emptyLabel`.
 *    Zero data without app copy renders the ready plot (renderer surfaces
 *    stamp `data-empty="true"`), preserving the no-hardcoded-locale law.
 * 3. The family-computed `data-part="data-fallback"` overlay -- the
 *    INVALID-DATA semantic (unrenderable geometry: negative values, NaN).
 *    It is not an empty state and stays owned by the family.
 */

import React, { useId, useMemo, useState, type CSSProperties, type ReactNode, type RefObject } from 'react';
import { arrayValueAt } from '@/foundation/kernel/collections';
import type { ChartScaffoldState, ChartStateProps, ChartSummaryTable } from '../../contracts';

export type { ChartSummaryTable } from '../../contracts';

/**
 * Visually hidden but screen-reader-readable styles used by charts to expose
 * textual summaries without polluting the visual layout.
 */
const VISUALLY_HIDDEN_STYLE: CSSProperties = {
  position: 'absolute',
  width: 1,
  height: 1,
  padding: 0,
  margin: -1,
  overflow: 'hidden',
  clip: 'rect(0, 0, 0, 0)',
  whiteSpace: 'nowrap',
};

interface ChartScaffoldPlotContext {
  /** The hidden structured description generated by this scaffold. */
  readonly descriptionId: string;
}

type ChartScaffoldPlot = ReactNode | ((context: ChartScaffoldPlotContext) => ReactNode);

interface ChartScaffoldBaseProps {
  containerRef: RefObject<HTMLDivElement | null>;
  svgRef: RefObject<SVGSVGElement | null>;
  width?: number | string;
  height: number;
  className?: string;
  style?: CSSProperties;
  /** @deprecated Alias for `state='loading'`; an explicit `state` prop wins. */
  loading?: boolean;
  loadingLabel: string;
  /**
   * Loading presentation variant: renders static placeholder bars instead of
   * the centered loading label (the label stays screen-reader announced).
   * Skin CSS owns the placeholder paint; when the shared skeleton shimmer
   * canon lands, it upgrades this variant without an anatomy change.
   */
  skeleton?: boolean;
  title?: string;
  subtitle?: string;
  ariaLabel: string;
  ariaDescription: string;
  summary?: ChartSummaryTable;
  legend?: ReactNode;
  /** When true, the legend slot is hidden (compact mode) */
  hideLegend?: boolean;
  /** Minimum height override for compact mode (applied as CSS min-height on container) */
  minHeight?: number;
  /**
   * Absolutely-positioned overlay rendered as a sibling of the svg, inside
   * the same `position: relative` container -- the seam a chart uses to
   * mount `<ChartTooltip>`. Kept outside the svg because D3-backed charts
   * wipe and rebuild their svg subtree imperatively (`selectAll('*').remove()`
   * on every data change); a React-rendered overlay in that subtree would
   * fight D3 for DOM ownership of the same nodes.
   */
  overlay?: ReactNode;
  /**
   * A React-owned renderer replacing the legacy imperative SVG slot. The
   * scaffold still owns heading, loading, legend, and textual summary so
   * family adapters can migrate without changing their public contract.
   */
  plot?: ChartScaffoldPlot;
}

export type ChartScaffoldProps = ChartScaffoldBaseProps & ChartStateProps;

/** Input facts from which a family shell resolves its scaffold state. */
export interface ChartScaffoldStateResolution {
  /** Caller-declared state; always wins when present. */
  state?: ChartScaffoldState;
  /** Legacy loading alias threaded by every family contract. */
  loading?: boolean;
  /** Number of renderable data items the family received. */
  dataCount: number;
  /** App-supplied empty copy; its absence disarms the automatic empty state. */
  emptyLabel?: ReactNode;
}

/**
 * Single authority for the family-side state resolution law: an explicit
 * `state` wins; the deprecated `loading` alias maps to `'loading'`; zero data
 * activates `'empty'` ONLY when the application supplied `emptyLabel` (the DS
 * hardcodes no copy); otherwise the chart is `'ready'` and empty data remains
 * the renderer surface's `data-empty` concern.
 */
export function resolveChartScaffoldState({
  state,
  loading,
  dataCount,
  emptyLabel,
}: ChartScaffoldStateResolution): ChartScaffoldState {
  if (state !== undefined) return state;
  if (loading) return 'loading';
  if (dataCount === 0 && emptyLabel !== undefined && emptyLabel !== null) return 'empty';
  return 'ready';
}

/**
 * Renders the summary as an HTML `<table>` for screen readers. This table
 * lives inside a visually-hidden container so sighted users see the chart
 * while assistive technology gets structured tabular data.
 */
function renderSummary(summary?: ChartSummaryTable): ReactNode {
  if (!summary || summary.rows.length === 0) {
    return null;
  }

  return (
    <table data-part="summary-table">
      {summary.caption ? <caption data-part="summary-caption">{summary.caption}</caption> : null}
      <thead data-part="summary-head">
        <tr data-part="summary-row">
          {summary.headers.map((header, index) => (
            <th key={`${header}-${index}`} data-part="summary-header">{header}</th>
          ))}
        </tr>
      </thead>
      <tbody data-part="summary-body">
        {summary.rows.map((row, index) => (
          <tr key={`${summary.caption ?? 'summary'}-${index}`} data-part="summary-row">
            {row.map((cell, cellIndex) => (
              <td key={`${summary.caption ?? 'summary'}-${index}-${cellIndex}`} data-part="summary-cell">{String(cell)}</td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/**
 * Shared chart shell that standardizes loading, title/subtitle, ARIA metadata,
 * keyboard navigation, and an accessible textual summary for every D3-backed chart.
 *
 * Accessibility strategy:
 * - The legacy SVG slot is focusable (`tabIndex=0`) and supports keyboard
 *   summary navigation; React-owned renderers supply their own SVG semantics
 *   and can reference this scaffold's structured description.
 * - Arrow/Home/End keys cycle through legacy summary data points, announced
 *   via `aria-live="polite"` so screen reader users can explore chart data.
 * - A visually hidden `<table>` provides a full textual summary of the data.
 *
 * @param props - Chart layout, ARIA labels, optional summary table, and legend.
 * @returns A container with loading state, title bar, accessible SVG, and legend slot.
 *
 * @example
 * ```tsx
 * <ChartScaffold
 *   containerRef={containerRef}
 *   svgRef={svgRef}
 *   height={400}
 *   loading={isLoading}
 *   loadingLabel="Loading chart..."
 *   ariaLabel="Monthly revenue"
 *   ariaDescription="Bar chart showing revenue by month"
 *   summary={{ headers: ['Month', 'Revenue'], rows: data }}
 * />
 * ```
 */
export function ChartScaffold({
  containerRef,
  svgRef,
  width,
  height,
  className,
  style,
  loading = false,
  loadingLabel,
  skeleton = false,
  state,
  emptyLabel,
  emptyDescription,
  emptyAction,
  errorLabel,
  errorDescription,
  errorAction,
  title,
  subtitle,
  ariaLabel,
  ariaDescription,
  summary,
  legend,
  hideLegend = false,
  minHeight,
  overlay,
  plot,
}: ChartScaffoldProps) {
  const descriptionId = useId();
  const titleId = useId();
  const fallbackTitleId = useId();
  // Tracks which data point the user navigated to via keyboard so we can
  // announce it via aria-live for screen readers.
  const [activeSummaryIndex, setActiveSummaryIndex] = useState(0);
  // Flatten the summary table into human-readable strings for keyboard nav.
  const summaryItems = useMemo(() => {
    if (!summary) {
      return [];
    }

    return summary.rows.map((row) =>
      row
        .map((cell, index) => {
          const header = summary.headers[index];
          return header ? `${header}: ${String(cell)}` : String(cell);
        })
        .join(', ')
    );
  }, [summary]);

  const activeSummaryItem =
    summaryItems.length > 0
      ? arrayValueAt(summaryItems, Math.min(activeSummaryIndex, Math.max(summaryItems.length - 1, 0))) ?? null
      : null;
  const scaffoldClassName = ['ds-chart-scaffold', className].filter(Boolean).join(' ');

  // Arrow/Home/End keys cycle through summary items and trigger an aria-live
  // announcement, giving screen reader users a way to explore chart data.
  const handleKeyboardNavigation = (event: React.KeyboardEvent<SVGSVGElement>) => {
    if (summaryItems.length === 0) {
      return;
    }

    if (event.key === 'ArrowRight' || event.key === 'ArrowDown') {
      event.preventDefault();
      setActiveSummaryIndex((current) => (current + 1) % summaryItems.length);
      return;
    }

    if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') {
      event.preventDefault();
      setActiveSummaryIndex((current) => (current - 1 + summaryItems.length) % summaryItems.length);
      return;
    }

    if (event.key === 'Home') {
      event.preventDefault();
      setActiveSummaryIndex(0);
      return;
    }

    if (event.key === 'End') {
      event.preventDefault();
      setActiveSummaryIndex(summaryItems.length - 1);
    }
  };

  const resolvedState: ChartScaffoldState = state ?? (loading ? 'loading' : 'ready');

  if (resolvedState === 'loading') {
    return (
      <div
        ref={containerRef}
        className={scaffoldClassName}
        data-part="chart-scaffold"
        data-state="loading"
        data-skeleton={skeleton ? 'true' : undefined}
        style={{ width: width ?? '100%', height, ...style }}
      >
        {skeleton ? (
          <>
            {/* Placeholder bars are decorative; the loading label below stays
                the announced state so assistive technology loses nothing. */}
            <div
              data-part="skeleton"
              aria-hidden="true"
              style={{
                display: 'flex',
                alignItems: 'flex-end',
                gap: 8,
                height: '100%',
                padding: 16,
                boxSizing: 'border-box',
              }}
            >
              <div data-part="skeleton-bar" style={{ flex: 1, height: '40%' }} />
              <div data-part="skeleton-bar" style={{ flex: 1, height: '70%' }} />
              <div data-part="skeleton-bar" style={{ flex: 1, height: '55%' }} />
              <div data-part="skeleton-bar" style={{ flex: 1, height: '30%' }} />
            </div>
            <span data-part="loading" role="status" style={VISUALLY_HIDDEN_STYLE}>
              {loadingLabel}
            </span>
          </>
        ) : (
          <div
            data-part="loading"
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              height: '100%',
            }}
          >
            {loadingLabel}
          </div>
        )}
      </div>
    );
  }

  if (resolvedState === 'empty' || resolvedState === 'error') {
    const isError = resolvedState === 'error';

    return (
      <div
        ref={containerRef}
        className={scaffoldClassName}
        data-part="chart-scaffold"
        data-state={resolvedState}
        style={{
          position: 'relative',
          display: 'flex',
          flexDirection: 'column',
          width: width ?? '100%',
          height,
          ...style,
        }}
      >
        {title ? (
          <div data-part="heading" style={{ marginBottom: 4 }}>
            <div id={titleId} data-part="title" style={{ fontSize: 16, fontWeight: 600 }}>{title}</div>
            {subtitle ? (
              <div data-part="subtitle" style={{ fontSize: 13 }}>{subtitle}</div>
            ) : null}
          </div>
        ) : (
          <span id={fallbackTitleId} data-part="accessible-title" style={VISUALLY_HIDDEN_STYLE}>
            {ariaLabel}
          </span>
        )}
        <div
          data-part="state"
          data-state={resolvedState}
          role={isError ? 'alert' : 'status'}
          aria-live={isError ? 'assertive' : 'polite'}
          aria-atomic="true"
          style={{
            flex: 1,
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            padding: 24,
            textAlign: 'center',
            boxSizing: 'border-box',
          }}
        >
          <div data-part="state-label" style={{ fontWeight: 600 }}>
            {isError ? errorLabel : emptyLabel}
          </div>
          {(isError ? errorDescription : emptyDescription) ? (
            <div data-part="state-description" style={{ fontSize: 13 }}>
              {isError ? errorDescription : emptyDescription}
            </div>
          ) : null}
          {(isError ? errorAction : emptyAction) ? (
            <div data-part="state-action">
              {isError ? errorAction : emptyAction}
            </div>
          ) : null}
        </div>
      </div>
    );
  }

  // Resolved only on the ready path: a non-ready scaffold must never invoke
  // the plot renderer, or stale family marks could compute (and mount)
  // beneath feedback copy.
  const resolvedPlot = typeof plot === 'function'
    ? plot({ descriptionId })
    : plot;

  return (
    <div
      ref={containerRef}
      className={scaffoldClassName}
      data-part="chart-scaffold"
      data-state="ready"
      style={{ position: 'relative', width: width ?? '100%', ...(minHeight ? { minHeight } : {}), ...style }}
    >
      {title ? (
        <div data-part="heading" style={{ marginBottom: 4 }}>
          <div id={titleId} data-part="title" style={{ fontSize: 16, fontWeight: 600 }}>{title}</div>
          {subtitle ? (
            <div data-part="subtitle" style={{ fontSize: 13 }}>{subtitle}</div>
          ) : null}
        </div>
      ) : (
        <span id={fallbackTitleId} data-part="accessible-title" style={VISUALLY_HIDDEN_STYLE}>
          {ariaLabel}
        </span>
      )}

      <div id={descriptionId} data-part="accessible-summary" style={VISUALLY_HIDDEN_STYLE}>
        <p>{ariaDescription}</p>
        {summaryItems.length > 0 ? (
          <p>
            Use arrow keys to move through summary items, Home to jump to the
            first item, and End to jump to the last item.
          </p>
        ) : null}
        {activeSummaryItem ? (
          <p aria-live="polite" aria-atomic="true">
            Active data point: {activeSummaryItem}
          </p>
        ) : null}
        {summaryItems.length > 0 ? (
          <ul>
            {summaryItems.map((item, index) => (
              <li key={`${descriptionId}-${index}`} aria-current={index === activeSummaryIndex ? 'true' : undefined}>
                {item}
              </li>
            ))}
          </ul>
        ) : null}
        {renderSummary(summary)}
      </div>

      {resolvedPlot ?? (
        /* The SVG is focusable (tabIndex=0) so keyboard users can reach it,
            and aria-roledescription overrides the generic "img" semantics with
            "interactive chart" for assistive technology. */
        <svg
          ref={svgRef}
          data-part="plot"
          role="img"
          aria-roledescription="interactive chart"
          tabIndex={0}
          // WO-DES-12 (design-language §8.3 / Craft Bar A5.5): axis + value labels
          // read as tabular numerals at detail size. Both inherit to every <text>
          // descendant, so binding them once on the scaffold svg covers every
          // chart without per-screen wiring. The detail-size is a DEFAULT — charts
          // that set an explicit size (hero gauge value, sized value labels) keep
          // it; only otherwise-unsized labels snap to the detail token.
          style={{
            fontVariantNumeric: 'var(--ds-numeric-tabular)' as CSSProperties['fontVariantNumeric'],
            fontSize: 'var(--ds-font-size-xs)',
          }}
          aria-labelledby={title ? titleId : fallbackTitleId}
          aria-describedby={descriptionId}
          aria-keyshortcuts={summaryItems.length > 0 ? 'ArrowLeft ArrowRight ArrowUp ArrowDown Home End' : undefined}
          onKeyDown={handleKeyboardNavigation}
        />
      )}

      {overlay ?? null}

      {hideLegend ? null : (legend ?? null)}
    </div>
  );
}

/**
 * Builds a human-readable ARIA description string for a chart.
 *
 * Combines the chart kind, item count, optional subtitle, and any extra
 * context into a single sentence suitable for `ariaDescription`.
 *
 * @param chartKind - e.g. "bar chart", "line chart", "pie chart".
 * @param itemCount - Number of data items displayed.
 * @param subtitle - Optional subtitle text to prepend.
 * @param extra - Optional extra context to append.
 * @returns A description string like "Monthly revenue. Bar chart containing 12 data items."
 *
 * @example
 * ```tsx
 * describeChart('line chart', 30, 'Daily signups', 'Last 30 days')
 * // => "Daily signups. line chart containing 30 data items. Last 30 days"
 * ```
 */
export function describeChart(
  chartKind: string,
  itemCount: number,
  subtitle?: string,
  extra?: string
): string {
  const parts = [
    subtitle,
    `${chartKind} containing ${itemCount} data ${itemCount === 1 ? 'item' : 'items'}.`,
    extra,
  ].filter(Boolean);

  return parts.join(' ');
}
